package cn.cttic.roadtransapi.orm.waterway.domain;

import java.util.ArrayList;
import java.util.List;

public class CfgCertiBusiRelaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CFG_CERTI_BUSI_RELA
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CFG_CERTI_BUSI_RELA
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CFG_CERTI_BUSI_RELA
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_CERTI_BUSI_RELA
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    public CfgCertiBusiRelaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_CERTI_BUSI_RELA
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_CERTI_BUSI_RELA
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_CERTI_BUSI_RELA
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_CERTI_BUSI_RELA
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_CERTI_BUSI_RELA
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_CERTI_BUSI_RELA
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_CERTI_BUSI_RELA
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_CERTI_BUSI_RELA
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_CERTI_BUSI_RELA
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_CERTI_BUSI_RELA
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CFG_CERTI_BUSI_RELA
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBookIdIsNull() {
            addCriterion("BOOK_ID is null");
            return (Criteria) this;
        }

        public Criteria andBookIdIsNotNull() {
            addCriterion("BOOK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBookIdEqualTo(String value) {
            addCriterion("BOOK_ID =", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotEqualTo(String value) {
            addCriterion("BOOK_ID <>", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdGreaterThan(String value) {
            addCriterion("BOOK_ID >", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdGreaterThanOrEqualTo(String value) {
            addCriterion("BOOK_ID >=", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdLessThan(String value) {
            addCriterion("BOOK_ID <", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdLessThanOrEqualTo(String value) {
            addCriterion("BOOK_ID <=", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdLike(String value) {
            addCriterion("BOOK_ID like", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotLike(String value) {
            addCriterion("BOOK_ID not like", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdIn(List<String> values) {
            addCriterion("BOOK_ID in", values, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotIn(List<String> values) {
            addCriterion("BOOK_ID not in", values, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdBetween(String value1, String value2) {
            addCriterion("BOOK_ID between", value1, value2, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotBetween(String value1, String value2) {
            addCriterion("BOOK_ID not between", value1, value2, "bookId");
            return (Criteria) this;
        }

        public Criteria andBusiTypeIsNull() {
            addCriterion("BUSI_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andBusiTypeIsNotNull() {
            addCriterion("BUSI_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andBusiTypeEqualTo(String value) {
            addCriterion("BUSI_TYPE =", value, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeNotEqualTo(String value) {
            addCriterion("BUSI_TYPE <>", value, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeGreaterThan(String value) {
            addCriterion("BUSI_TYPE >", value, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeGreaterThanOrEqualTo(String value) {
            addCriterion("BUSI_TYPE >=", value, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeLessThan(String value) {
            addCriterion("BUSI_TYPE <", value, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeLessThanOrEqualTo(String value) {
            addCriterion("BUSI_TYPE <=", value, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeLike(String value) {
            addCriterion("BUSI_TYPE like", value, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeNotLike(String value) {
            addCriterion("BUSI_TYPE not like", value, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeIn(List<String> values) {
            addCriterion("BUSI_TYPE in", values, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeNotIn(List<String> values) {
            addCriterion("BUSI_TYPE not in", values, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeBetween(String value1, String value2) {
            addCriterion("BUSI_TYPE between", value1, value2, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeNotBetween(String value1, String value2) {
            addCriterion("BUSI_TYPE not between", value1, value2, "busiType");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("STATE in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("STATE not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("NOTE is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("NOTE is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("NOTE =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("NOTE <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("NOTE >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("NOTE >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("NOTE <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("NOTE <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("NOTE like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("NOTE not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("NOTE in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("NOTE not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("NOTE between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("NOTE not between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andEntMainIsNull() {
            addCriterion("ENT_MAIN is null");
            return (Criteria) this;
        }

        public Criteria andEntMainIsNotNull() {
            addCriterion("ENT_MAIN is not null");
            return (Criteria) this;
        }

        public Criteria andEntMainEqualTo(String value) {
            addCriterion("ENT_MAIN =", value, "entMain");
            return (Criteria) this;
        }

        public Criteria andEntMainNotEqualTo(String value) {
            addCriterion("ENT_MAIN <>", value, "entMain");
            return (Criteria) this;
        }

        public Criteria andEntMainGreaterThan(String value) {
            addCriterion("ENT_MAIN >", value, "entMain");
            return (Criteria) this;
        }

        public Criteria andEntMainGreaterThanOrEqualTo(String value) {
            addCriterion("ENT_MAIN >=", value, "entMain");
            return (Criteria) this;
        }

        public Criteria andEntMainLessThan(String value) {
            addCriterion("ENT_MAIN <", value, "entMain");
            return (Criteria) this;
        }

        public Criteria andEntMainLessThanOrEqualTo(String value) {
            addCriterion("ENT_MAIN <=", value, "entMain");
            return (Criteria) this;
        }

        public Criteria andEntMainLike(String value) {
            addCriterion("ENT_MAIN like", value, "entMain");
            return (Criteria) this;
        }

        public Criteria andEntMainNotLike(String value) {
            addCriterion("ENT_MAIN not like", value, "entMain");
            return (Criteria) this;
        }

        public Criteria andEntMainIn(List<String> values) {
            addCriterion("ENT_MAIN in", values, "entMain");
            return (Criteria) this;
        }

        public Criteria andEntMainNotIn(List<String> values) {
            addCriterion("ENT_MAIN not in", values, "entMain");
            return (Criteria) this;
        }

        public Criteria andEntMainBetween(String value1, String value2) {
            addCriterion("ENT_MAIN between", value1, value2, "entMain");
            return (Criteria) this;
        }

        public Criteria andEntMainNotBetween(String value1, String value2) {
            addCriterion("ENT_MAIN not between", value1, value2, "entMain");
            return (Criteria) this;
        }

        public Criteria andShipMainIsNull() {
            addCriterion("SHIP_MAIN is null");
            return (Criteria) this;
        }

        public Criteria andShipMainIsNotNull() {
            addCriterion("SHIP_MAIN is not null");
            return (Criteria) this;
        }

        public Criteria andShipMainEqualTo(String value) {
            addCriterion("SHIP_MAIN =", value, "shipMain");
            return (Criteria) this;
        }

        public Criteria andShipMainNotEqualTo(String value) {
            addCriterion("SHIP_MAIN <>", value, "shipMain");
            return (Criteria) this;
        }

        public Criteria andShipMainGreaterThan(String value) {
            addCriterion("SHIP_MAIN >", value, "shipMain");
            return (Criteria) this;
        }

        public Criteria andShipMainGreaterThanOrEqualTo(String value) {
            addCriterion("SHIP_MAIN >=", value, "shipMain");
            return (Criteria) this;
        }

        public Criteria andShipMainLessThan(String value) {
            addCriterion("SHIP_MAIN <", value, "shipMain");
            return (Criteria) this;
        }

        public Criteria andShipMainLessThanOrEqualTo(String value) {
            addCriterion("SHIP_MAIN <=", value, "shipMain");
            return (Criteria) this;
        }

        public Criteria andShipMainLike(String value) {
            addCriterion("SHIP_MAIN like", value, "shipMain");
            return (Criteria) this;
        }

        public Criteria andShipMainNotLike(String value) {
            addCriterion("SHIP_MAIN not like", value, "shipMain");
            return (Criteria) this;
        }

        public Criteria andShipMainIn(List<String> values) {
            addCriterion("SHIP_MAIN in", values, "shipMain");
            return (Criteria) this;
        }

        public Criteria andShipMainNotIn(List<String> values) {
            addCriterion("SHIP_MAIN not in", values, "shipMain");
            return (Criteria) this;
        }

        public Criteria andShipMainBetween(String value1, String value2) {
            addCriterion("SHIP_MAIN between", value1, value2, "shipMain");
            return (Criteria) this;
        }

        public Criteria andShipMainNotBetween(String value1, String value2) {
            addCriterion("SHIP_MAIN not between", value1, value2, "shipMain");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CFG_CERTI_BUSI_RELA
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 29 16:21:54 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CFG_CERTI_BUSI_RELA
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}