package cn.cttic.roadtransapi.orm.waterway.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ShipStatisInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SHIP_STATIS_INFO
     *
     * @mbggenerated Fri Mar 20 16:45:02 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SHIP_STATIS_INFO
     *
     * @mbggenerated Fri Mar 20 16:45:02 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SHIP_STATIS_INFO
     *
     * @mbggenerated Fri Mar 20 16:45:02 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIP_STATIS_INFO
     *
     * @mbggenerated Fri Mar 20 16:45:02 CST 2015
     */
    public ShipStatisInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIP_STATIS_INFO
     *
     * @mbggenerated Fri Mar 20 16:45:02 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIP_STATIS_INFO
     *
     * @mbggenerated Fri Mar 20 16:45:02 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIP_STATIS_INFO
     *
     * @mbggenerated Fri Mar 20 16:45:02 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIP_STATIS_INFO
     *
     * @mbggenerated Fri Mar 20 16:45:02 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIP_STATIS_INFO
     *
     * @mbggenerated Fri Mar 20 16:45:02 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIP_STATIS_INFO
     *
     * @mbggenerated Fri Mar 20 16:45:02 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIP_STATIS_INFO
     *
     * @mbggenerated Fri Mar 20 16:45:02 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIP_STATIS_INFO
     *
     * @mbggenerated Fri Mar 20 16:45:02 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIP_STATIS_INFO
     *
     * @mbggenerated Fri Mar 20 16:45:02 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIP_STATIS_INFO
     *
     * @mbggenerated Fri Mar 20 16:45:02 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SHIP_STATIS_INFO
     *
     * @mbggenerated Fri Mar 20 16:45:02 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andShipStatisIdIsNull() {
            addCriterion("SHIP_STATIS_ID is null");
            return (Criteria) this;
        }

        public Criteria andShipStatisIdIsNotNull() {
            addCriterion("SHIP_STATIS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andShipStatisIdEqualTo(Long value) {
            addCriterion("SHIP_STATIS_ID =", value, "shipStatisId");
            return (Criteria) this;
        }

        public Criteria andShipStatisIdNotEqualTo(Long value) {
            addCriterion("SHIP_STATIS_ID <>", value, "shipStatisId");
            return (Criteria) this;
        }

        public Criteria andShipStatisIdGreaterThan(Long value) {
            addCriterion("SHIP_STATIS_ID >", value, "shipStatisId");
            return (Criteria) this;
        }

        public Criteria andShipStatisIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SHIP_STATIS_ID >=", value, "shipStatisId");
            return (Criteria) this;
        }

        public Criteria andShipStatisIdLessThan(Long value) {
            addCriterion("SHIP_STATIS_ID <", value, "shipStatisId");
            return (Criteria) this;
        }

        public Criteria andShipStatisIdLessThanOrEqualTo(Long value) {
            addCriterion("SHIP_STATIS_ID <=", value, "shipStatisId");
            return (Criteria) this;
        }

        public Criteria andShipStatisIdIn(List<Long> values) {
            addCriterion("SHIP_STATIS_ID in", values, "shipStatisId");
            return (Criteria) this;
        }

        public Criteria andShipStatisIdNotIn(List<Long> values) {
            addCriterion("SHIP_STATIS_ID not in", values, "shipStatisId");
            return (Criteria) this;
        }

        public Criteria andShipStatisIdBetween(Long value1, Long value2) {
            addCriterion("SHIP_STATIS_ID between", value1, value2, "shipStatisId");
            return (Criteria) this;
        }

        public Criteria andShipStatisIdNotBetween(Long value1, Long value2) {
            addCriterion("SHIP_STATIS_ID not between", value1, value2, "shipStatisId");
            return (Criteria) this;
        }

        public Criteria andEntRepoIdIsNull() {
            addCriterion("ENT_REPO_ID is null");
            return (Criteria) this;
        }

        public Criteria andEntRepoIdIsNotNull() {
            addCriterion("ENT_REPO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEntRepoIdEqualTo(Long value) {
            addCriterion("ENT_REPO_ID =", value, "entRepoId");
            return (Criteria) this;
        }

        public Criteria andEntRepoIdNotEqualTo(Long value) {
            addCriterion("ENT_REPO_ID <>", value, "entRepoId");
            return (Criteria) this;
        }

        public Criteria andEntRepoIdGreaterThan(Long value) {
            addCriterion("ENT_REPO_ID >", value, "entRepoId");
            return (Criteria) this;
        }

        public Criteria andEntRepoIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ENT_REPO_ID >=", value, "entRepoId");
            return (Criteria) this;
        }

        public Criteria andEntRepoIdLessThan(Long value) {
            addCriterion("ENT_REPO_ID <", value, "entRepoId");
            return (Criteria) this;
        }

        public Criteria andEntRepoIdLessThanOrEqualTo(Long value) {
            addCriterion("ENT_REPO_ID <=", value, "entRepoId");
            return (Criteria) this;
        }

        public Criteria andEntRepoIdIn(List<Long> values) {
            addCriterion("ENT_REPO_ID in", values, "entRepoId");
            return (Criteria) this;
        }

        public Criteria andEntRepoIdNotIn(List<Long> values) {
            addCriterion("ENT_REPO_ID not in", values, "entRepoId");
            return (Criteria) this;
        }

        public Criteria andEntRepoIdBetween(Long value1, Long value2) {
            addCriterion("ENT_REPO_ID between", value1, value2, "entRepoId");
            return (Criteria) this;
        }

        public Criteria andEntRepoIdNotBetween(Long value1, Long value2) {
            addCriterion("ENT_REPO_ID not between", value1, value2, "entRepoId");
            return (Criteria) this;
        }

        public Criteria andEntIdIsNull() {
            addCriterion("ENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andEntIdIsNotNull() {
            addCriterion("ENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEntIdEqualTo(String value) {
            addCriterion("ENT_ID =", value, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdNotEqualTo(String value) {
            addCriterion("ENT_ID <>", value, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdGreaterThan(String value) {
            addCriterion("ENT_ID >", value, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdGreaterThanOrEqualTo(String value) {
            addCriterion("ENT_ID >=", value, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdLessThan(String value) {
            addCriterion("ENT_ID <", value, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdLessThanOrEqualTo(String value) {
            addCriterion("ENT_ID <=", value, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdLike(String value) {
            addCriterion("ENT_ID like", value, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdNotLike(String value) {
            addCriterion("ENT_ID not like", value, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdIn(List<String> values) {
            addCriterion("ENT_ID in", values, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdNotIn(List<String> values) {
            addCriterion("ENT_ID not in", values, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdBetween(String value1, String value2) {
            addCriterion("ENT_ID between", value1, value2, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdNotBetween(String value1, String value2) {
            addCriterion("ENT_ID not between", value1, value2, "entId");
            return (Criteria) this;
        }

        public Criteria andShipTypeIsNull() {
            addCriterion("SHIP_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andShipTypeIsNotNull() {
            addCriterion("SHIP_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andShipTypeEqualTo(String value) {
            addCriterion("SHIP_TYPE =", value, "shipType");
            return (Criteria) this;
        }

        public Criteria andShipTypeNotEqualTo(String value) {
            addCriterion("SHIP_TYPE <>", value, "shipType");
            return (Criteria) this;
        }

        public Criteria andShipTypeGreaterThan(String value) {
            addCriterion("SHIP_TYPE >", value, "shipType");
            return (Criteria) this;
        }

        public Criteria andShipTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SHIP_TYPE >=", value, "shipType");
            return (Criteria) this;
        }

        public Criteria andShipTypeLessThan(String value) {
            addCriterion("SHIP_TYPE <", value, "shipType");
            return (Criteria) this;
        }

        public Criteria andShipTypeLessThanOrEqualTo(String value) {
            addCriterion("SHIP_TYPE <=", value, "shipType");
            return (Criteria) this;
        }

        public Criteria andShipTypeLike(String value) {
            addCriterion("SHIP_TYPE like", value, "shipType");
            return (Criteria) this;
        }

        public Criteria andShipTypeNotLike(String value) {
            addCriterion("SHIP_TYPE not like", value, "shipType");
            return (Criteria) this;
        }

        public Criteria andShipTypeIn(List<String> values) {
            addCriterion("SHIP_TYPE in", values, "shipType");
            return (Criteria) this;
        }

        public Criteria andShipTypeNotIn(List<String> values) {
            addCriterion("SHIP_TYPE not in", values, "shipType");
            return (Criteria) this;
        }

        public Criteria andShipTypeBetween(String value1, String value2) {
            addCriterion("SHIP_TYPE between", value1, value2, "shipType");
            return (Criteria) this;
        }

        public Criteria andShipTypeNotBetween(String value1, String value2) {
            addCriterion("SHIP_TYPE not between", value1, value2, "shipType");
            return (Criteria) this;
        }

        public Criteria andShipsChnIsNull() {
            addCriterion("SHIPS_CHN is null");
            return (Criteria) this;
        }

        public Criteria andShipsChnIsNotNull() {
            addCriterion("SHIPS_CHN is not null");
            return (Criteria) this;
        }

        public Criteria andShipsChnEqualTo(Short value) {
            addCriterion("SHIPS_CHN =", value, "shipsChn");
            return (Criteria) this;
        }

        public Criteria andShipsChnNotEqualTo(Short value) {
            addCriterion("SHIPS_CHN <>", value, "shipsChn");
            return (Criteria) this;
        }

        public Criteria andShipsChnGreaterThan(Short value) {
            addCriterion("SHIPS_CHN >", value, "shipsChn");
            return (Criteria) this;
        }

        public Criteria andShipsChnGreaterThanOrEqualTo(Short value) {
            addCriterion("SHIPS_CHN >=", value, "shipsChn");
            return (Criteria) this;
        }

        public Criteria andShipsChnLessThan(Short value) {
            addCriterion("SHIPS_CHN <", value, "shipsChn");
            return (Criteria) this;
        }

        public Criteria andShipsChnLessThanOrEqualTo(Short value) {
            addCriterion("SHIPS_CHN <=", value, "shipsChn");
            return (Criteria) this;
        }

        public Criteria andShipsChnIn(List<Short> values) {
            addCriterion("SHIPS_CHN in", values, "shipsChn");
            return (Criteria) this;
        }

        public Criteria andShipsChnNotIn(List<Short> values) {
            addCriterion("SHIPS_CHN not in", values, "shipsChn");
            return (Criteria) this;
        }

        public Criteria andShipsChnBetween(Short value1, Short value2) {
            addCriterion("SHIPS_CHN between", value1, value2, "shipsChn");
            return (Criteria) this;
        }

        public Criteria andShipsChnNotBetween(Short value1, Short value2) {
            addCriterion("SHIPS_CHN not between", value1, value2, "shipsChn");
            return (Criteria) this;
        }

        public Criteria andShipCapacityChnIsNull() {
            addCriterion("SHIP_CAPACITY_CHN is null");
            return (Criteria) this;
        }

        public Criteria andShipCapacityChnIsNotNull() {
            addCriterion("SHIP_CAPACITY_CHN is not null");
            return (Criteria) this;
        }

        public Criteria andShipCapacityChnEqualTo(Short value) {
            addCriterion("SHIP_CAPACITY_CHN =", value, "shipCapacityChn");
            return (Criteria) this;
        }

        public Criteria andShipCapacityChnNotEqualTo(Short value) {
            addCriterion("SHIP_CAPACITY_CHN <>", value, "shipCapacityChn");
            return (Criteria) this;
        }

        public Criteria andShipCapacityChnGreaterThan(Short value) {
            addCriterion("SHIP_CAPACITY_CHN >", value, "shipCapacityChn");
            return (Criteria) this;
        }

        public Criteria andShipCapacityChnGreaterThanOrEqualTo(Short value) {
            addCriterion("SHIP_CAPACITY_CHN >=", value, "shipCapacityChn");
            return (Criteria) this;
        }

        public Criteria andShipCapacityChnLessThan(Short value) {
            addCriterion("SHIP_CAPACITY_CHN <", value, "shipCapacityChn");
            return (Criteria) this;
        }

        public Criteria andShipCapacityChnLessThanOrEqualTo(Short value) {
            addCriterion("SHIP_CAPACITY_CHN <=", value, "shipCapacityChn");
            return (Criteria) this;
        }

        public Criteria andShipCapacityChnIn(List<Short> values) {
            addCriterion("SHIP_CAPACITY_CHN in", values, "shipCapacityChn");
            return (Criteria) this;
        }

        public Criteria andShipCapacityChnNotIn(List<Short> values) {
            addCriterion("SHIP_CAPACITY_CHN not in", values, "shipCapacityChn");
            return (Criteria) this;
        }

        public Criteria andShipCapacityChnBetween(Short value1, Short value2) {
            addCriterion("SHIP_CAPACITY_CHN between", value1, value2, "shipCapacityChn");
            return (Criteria) this;
        }

        public Criteria andShipCapacityChnNotBetween(Short value1, Short value2) {
            addCriterion("SHIP_CAPACITY_CHN not between", value1, value2, "shipCapacityChn");
            return (Criteria) this;
        }

        public Criteria andShipSpaceChnIsNull() {
            addCriterion("SHIP_SPACE_CHN is null");
            return (Criteria) this;
        }

        public Criteria andShipSpaceChnIsNotNull() {
            addCriterion("SHIP_SPACE_CHN is not null");
            return (Criteria) this;
        }

        public Criteria andShipSpaceChnEqualTo(Short value) {
            addCriterion("SHIP_SPACE_CHN =", value, "shipSpaceChn");
            return (Criteria) this;
        }

        public Criteria andShipSpaceChnNotEqualTo(Short value) {
            addCriterion("SHIP_SPACE_CHN <>", value, "shipSpaceChn");
            return (Criteria) this;
        }

        public Criteria andShipSpaceChnGreaterThan(Short value) {
            addCriterion("SHIP_SPACE_CHN >", value, "shipSpaceChn");
            return (Criteria) this;
        }

        public Criteria andShipSpaceChnGreaterThanOrEqualTo(Short value) {
            addCriterion("SHIP_SPACE_CHN >=", value, "shipSpaceChn");
            return (Criteria) this;
        }

        public Criteria andShipSpaceChnLessThan(Short value) {
            addCriterion("SHIP_SPACE_CHN <", value, "shipSpaceChn");
            return (Criteria) this;
        }

        public Criteria andShipSpaceChnLessThanOrEqualTo(Short value) {
            addCriterion("SHIP_SPACE_CHN <=", value, "shipSpaceChn");
            return (Criteria) this;
        }

        public Criteria andShipSpaceChnIn(List<Short> values) {
            addCriterion("SHIP_SPACE_CHN in", values, "shipSpaceChn");
            return (Criteria) this;
        }

        public Criteria andShipSpaceChnNotIn(List<Short> values) {
            addCriterion("SHIP_SPACE_CHN not in", values, "shipSpaceChn");
            return (Criteria) this;
        }

        public Criteria andShipSpaceChnBetween(Short value1, Short value2) {
            addCriterion("SHIP_SPACE_CHN between", value1, value2, "shipSpaceChn");
            return (Criteria) this;
        }

        public Criteria andShipSpaceChnNotBetween(Short value1, Short value2) {
            addCriterion("SHIP_SPACE_CHN not between", value1, value2, "shipSpaceChn");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipsIsNull() {
            addCriterion("CONVENIENCE_SHIPS is null");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipsIsNotNull() {
            addCriterion("CONVENIENCE_SHIPS is not null");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipsEqualTo(Short value) {
            addCriterion("CONVENIENCE_SHIPS =", value, "convenienceShips");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipsNotEqualTo(Short value) {
            addCriterion("CONVENIENCE_SHIPS <>", value, "convenienceShips");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipsGreaterThan(Short value) {
            addCriterion("CONVENIENCE_SHIPS >", value, "convenienceShips");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipsGreaterThanOrEqualTo(Short value) {
            addCriterion("CONVENIENCE_SHIPS >=", value, "convenienceShips");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipsLessThan(Short value) {
            addCriterion("CONVENIENCE_SHIPS <", value, "convenienceShips");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipsLessThanOrEqualTo(Short value) {
            addCriterion("CONVENIENCE_SHIPS <=", value, "convenienceShips");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipsIn(List<Short> values) {
            addCriterion("CONVENIENCE_SHIPS in", values, "convenienceShips");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipsNotIn(List<Short> values) {
            addCriterion("CONVENIENCE_SHIPS not in", values, "convenienceShips");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipsBetween(Short value1, Short value2) {
            addCriterion("CONVENIENCE_SHIPS between", value1, value2, "convenienceShips");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipsNotBetween(Short value1, Short value2) {
            addCriterion("CONVENIENCE_SHIPS not between", value1, value2, "convenienceShips");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipCapacityIsNull() {
            addCriterion("CONVENIENCE_SHIP_CAPACITY is null");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipCapacityIsNotNull() {
            addCriterion("CONVENIENCE_SHIP_CAPACITY is not null");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipCapacityEqualTo(Short value) {
            addCriterion("CONVENIENCE_SHIP_CAPACITY =", value, "convenienceShipCapacity");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipCapacityNotEqualTo(Short value) {
            addCriterion("CONVENIENCE_SHIP_CAPACITY <>", value, "convenienceShipCapacity");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipCapacityGreaterThan(Short value) {
            addCriterion("CONVENIENCE_SHIP_CAPACITY >", value, "convenienceShipCapacity");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipCapacityGreaterThanOrEqualTo(Short value) {
            addCriterion("CONVENIENCE_SHIP_CAPACITY >=", value, "convenienceShipCapacity");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipCapacityLessThan(Short value) {
            addCriterion("CONVENIENCE_SHIP_CAPACITY <", value, "convenienceShipCapacity");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipCapacityLessThanOrEqualTo(Short value) {
            addCriterion("CONVENIENCE_SHIP_CAPACITY <=", value, "convenienceShipCapacity");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipCapacityIn(List<Short> values) {
            addCriterion("CONVENIENCE_SHIP_CAPACITY in", values, "convenienceShipCapacity");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipCapacityNotIn(List<Short> values) {
            addCriterion("CONVENIENCE_SHIP_CAPACITY not in", values, "convenienceShipCapacity");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipCapacityBetween(Short value1, Short value2) {
            addCriterion("CONVENIENCE_SHIP_CAPACITY between", value1, value2, "convenienceShipCapacity");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipCapacityNotBetween(Short value1, Short value2) {
            addCriterion("CONVENIENCE_SHIP_CAPACITY not between", value1, value2, "convenienceShipCapacity");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipSpaceIsNull() {
            addCriterion("CONVENIENCE_SHIP_SPACE is null");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipSpaceIsNotNull() {
            addCriterion("CONVENIENCE_SHIP_SPACE is not null");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipSpaceEqualTo(Short value) {
            addCriterion("CONVENIENCE_SHIP_SPACE =", value, "convenienceShipSpace");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipSpaceNotEqualTo(Short value) {
            addCriterion("CONVENIENCE_SHIP_SPACE <>", value, "convenienceShipSpace");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipSpaceGreaterThan(Short value) {
            addCriterion("CONVENIENCE_SHIP_SPACE >", value, "convenienceShipSpace");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipSpaceGreaterThanOrEqualTo(Short value) {
            addCriterion("CONVENIENCE_SHIP_SPACE >=", value, "convenienceShipSpace");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipSpaceLessThan(Short value) {
            addCriterion("CONVENIENCE_SHIP_SPACE <", value, "convenienceShipSpace");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipSpaceLessThanOrEqualTo(Short value) {
            addCriterion("CONVENIENCE_SHIP_SPACE <=", value, "convenienceShipSpace");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipSpaceIn(List<Short> values) {
            addCriterion("CONVENIENCE_SHIP_SPACE in", values, "convenienceShipSpace");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipSpaceNotIn(List<Short> values) {
            addCriterion("CONVENIENCE_SHIP_SPACE not in", values, "convenienceShipSpace");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipSpaceBetween(Short value1, Short value2) {
            addCriterion("CONVENIENCE_SHIP_SPACE between", value1, value2, "convenienceShipSpace");
            return (Criteria) this;
        }

        public Criteria andConvenienceShipSpaceNotBetween(Short value1, Short value2) {
            addCriterion("CONVENIENCE_SHIP_SPACE not between", value1, value2, "convenienceShipSpace");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNull() {
            addCriterion("ORG_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNotNull() {
            addCriterion("ORG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrgIdEqualTo(String value) {
            addCriterion("ORG_ID =", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotEqualTo(String value) {
            addCriterion("ORG_ID <>", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThan(String value) {
            addCriterion("ORG_ID >", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_ID >=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThan(String value) {
            addCriterion("ORG_ID <", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThanOrEqualTo(String value) {
            addCriterion("ORG_ID <=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLike(String value) {
            addCriterion("ORG_ID like", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotLike(String value) {
            addCriterion("ORG_ID not like", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdIn(List<String> values) {
            addCriterion("ORG_ID in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotIn(List<String> values) {
            addCriterion("ORG_ID not in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdBetween(String value1, String value2) {
            addCriterion("ORG_ID between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotBetween(String value1, String value2) {
            addCriterion("ORG_ID not between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andOperDateIsNull() {
            addCriterion("OPER_DATE is null");
            return (Criteria) this;
        }

        public Criteria andOperDateIsNotNull() {
            addCriterion("OPER_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andOperDateEqualTo(Date value) {
            addCriterion("OPER_DATE =", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotEqualTo(Date value) {
            addCriterion("OPER_DATE <>", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateGreaterThan(Date value) {
            addCriterion("OPER_DATE >", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateGreaterThanOrEqualTo(Date value) {
            addCriterion("OPER_DATE >=", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLessThan(Date value) {
            addCriterion("OPER_DATE <", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLessThanOrEqualTo(Date value) {
            addCriterion("OPER_DATE <=", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateIn(List<Date> values) {
            addCriterion("OPER_DATE in", values, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotIn(List<Date> values) {
            addCriterion("OPER_DATE not in", values, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateBetween(Date value1, Date value2) {
            addCriterion("OPER_DATE between", value1, value2, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotBetween(Date value1, Date value2) {
            addCriterion("OPER_DATE not between", value1, value2, "operDate");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("STATE in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("STATE not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("NOTE is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("NOTE is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("NOTE =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("NOTE <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("NOTE >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("NOTE >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("NOTE <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("NOTE <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("NOTE like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("NOTE not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("NOTE in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("NOTE not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("NOTE between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("NOTE not between", value1, value2, "note");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SHIP_STATIS_INFO
     *
     * @mbggenerated do_not_delete_during_merge Fri Mar 20 16:45:02 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SHIP_STATIS_INFO
     *
     * @mbggenerated Fri Mar 20 16:45:02 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}