package cn.cttic.roadtransapi.orm.map.dao;

import cn.cttic.roadtransapi.orm.map.domain.InterMapRectInfo;
import cn.cttic.roadtransapi.orm.map.domain.InterMapRectInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InterMapRectInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER_MAP_RECT_INFO
     *
     * @mbggenerated Sun Sep 06 20:26:39 CST 2015
     */
    int countByExample(InterMapRectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER_MAP_RECT_INFO
     *
     * @mbggenerated Sun Sep 06 20:26:39 CST 2015
     */
    int deleteByExample(InterMapRectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER_MAP_RECT_INFO
     *
     * @mbggenerated Sun Sep 06 20:26:39 CST 2015
     */
    int insert(InterMapRectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER_MAP_RECT_INFO
     *
     * @mbggenerated Sun Sep 06 20:26:39 CST 2015
     */
    int insertSelective(InterMapRectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER_MAP_RECT_INFO
     *
     * @mbggenerated Sun Sep 06 20:26:39 CST 2015
     */
    List<InterMapRectInfo> selectByExample(InterMapRectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER_MAP_RECT_INFO
     *
     * @mbggenerated Sun Sep 06 20:26:39 CST 2015
     */
    int updateByExampleSelective(@Param("record") InterMapRectInfo record, @Param("example") InterMapRectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER_MAP_RECT_INFO
     *
     * @mbggenerated Sun Sep 06 20:26:39 CST 2015
     */
    int updateByExample(@Param("record") InterMapRectInfo record, @Param("example") InterMapRectInfoExample example);
}