package cn.cttic.roadtransapi.orm.roadway.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DwBaseinfoStaffCertExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DW_BASEINFO_STAFF_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DW_BASEINFO_STAFF_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DW_BASEINFO_STAFF_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_STAFF_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public DwBaseinfoStaffCertExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_STAFF_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_STAFF_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_STAFF_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_STAFF_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_STAFF_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_STAFF_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_STAFF_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_STAFF_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_STAFF_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_STAFF_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DW_BASEINFO_STAFF_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeIsNull() {
            addCriterion("PROVINCE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeIsNotNull() {
            addCriterion("PROVINCE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeEqualTo(Integer value) {
            addCriterion("PROVINCE_CODE =", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeNotEqualTo(Integer value) {
            addCriterion("PROVINCE_CODE <>", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeGreaterThan(Integer value) {
            addCriterion("PROVINCE_CODE >", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("PROVINCE_CODE >=", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeLessThan(Integer value) {
            addCriterion("PROVINCE_CODE <", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeLessThanOrEqualTo(Integer value) {
            addCriterion("PROVINCE_CODE <=", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeIn(List<Integer> values) {
            addCriterion("PROVINCE_CODE in", values, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeNotIn(List<Integer> values) {
            addCriterion("PROVINCE_CODE not in", values, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeBetween(Integer value1, Integer value2) {
            addCriterion("PROVINCE_CODE between", value1, value2, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("PROVINCE_CODE not between", value1, value2, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andStaffIdIsNull() {
            addCriterion("STAFF_ID is null");
            return (Criteria) this;
        }

        public Criteria andStaffIdIsNotNull() {
            addCriterion("STAFF_ID is not null");
            return (Criteria) this;
        }

        public Criteria andStaffIdEqualTo(String value) {
            addCriterion("STAFF_ID =", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotEqualTo(String value) {
            addCriterion("STAFF_ID <>", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdGreaterThan(String value) {
            addCriterion("STAFF_ID >", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdGreaterThanOrEqualTo(String value) {
            addCriterion("STAFF_ID >=", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdLessThan(String value) {
            addCriterion("STAFF_ID <", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdLessThanOrEqualTo(String value) {
            addCriterion("STAFF_ID <=", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdLike(String value) {
            addCriterion("STAFF_ID like", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotLike(String value) {
            addCriterion("STAFF_ID not like", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdIn(List<String> values) {
            addCriterion("STAFF_ID in", values, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotIn(List<String> values) {
            addCriterion("STAFF_ID not in", values, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdBetween(String value1, String value2) {
            addCriterion("STAFF_ID between", value1, value2, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotBetween(String value1, String value2) {
            addCriterion("STAFF_ID not between", value1, value2, "staffId");
            return (Criteria) this;
        }

        public Criteria andIdTypeIsNull() {
            addCriterion("ID_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andIdTypeIsNotNull() {
            addCriterion("ID_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andIdTypeEqualTo(String value) {
            addCriterion("ID_TYPE =", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeNotEqualTo(String value) {
            addCriterion("ID_TYPE <>", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeGreaterThan(String value) {
            addCriterion("ID_TYPE >", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ID_TYPE >=", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeLessThan(String value) {
            addCriterion("ID_TYPE <", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeLessThanOrEqualTo(String value) {
            addCriterion("ID_TYPE <=", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeLike(String value) {
            addCriterion("ID_TYPE like", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeNotLike(String value) {
            addCriterion("ID_TYPE not like", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeIn(List<String> values) {
            addCriterion("ID_TYPE in", values, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeNotIn(List<String> values) {
            addCriterion("ID_TYPE not in", values, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeBetween(String value1, String value2) {
            addCriterion("ID_TYPE between", value1, value2, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeNotBetween(String value1, String value2) {
            addCriterion("ID_TYPE not between", value1, value2, "idType");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNull() {
            addCriterion("ID_CARD is null");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNotNull() {
            addCriterion("ID_CARD is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardEqualTo(String value) {
            addCriterion("ID_CARD =", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotEqualTo(String value) {
            addCriterion("ID_CARD <>", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThan(String value) {
            addCriterion("ID_CARD >", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("ID_CARD >=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThan(String value) {
            addCriterion("ID_CARD <", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThanOrEqualTo(String value) {
            addCriterion("ID_CARD <=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLike(String value) {
            addCriterion("ID_CARD like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotLike(String value) {
            addCriterion("ID_CARD not like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardIn(List<String> values) {
            addCriterion("ID_CARD in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotIn(List<String> values) {
            addCriterion("ID_CARD not in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardBetween(String value1, String value2) {
            addCriterion("ID_CARD between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotBetween(String value1, String value2) {
            addCriterion("ID_CARD not between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andWorkTypeCodeIsNull() {
            addCriterion("WORK_TYPE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andWorkTypeCodeIsNotNull() {
            addCriterion("WORK_TYPE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andWorkTypeCodeEqualTo(String value) {
            addCriterion("WORK_TYPE_CODE =", value, "workTypeCode");
            return (Criteria) this;
        }

        public Criteria andWorkTypeCodeNotEqualTo(String value) {
            addCriterion("WORK_TYPE_CODE <>", value, "workTypeCode");
            return (Criteria) this;
        }

        public Criteria andWorkTypeCodeGreaterThan(String value) {
            addCriterion("WORK_TYPE_CODE >", value, "workTypeCode");
            return (Criteria) this;
        }

        public Criteria andWorkTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("WORK_TYPE_CODE >=", value, "workTypeCode");
            return (Criteria) this;
        }

        public Criteria andWorkTypeCodeLessThan(String value) {
            addCriterion("WORK_TYPE_CODE <", value, "workTypeCode");
            return (Criteria) this;
        }

        public Criteria andWorkTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("WORK_TYPE_CODE <=", value, "workTypeCode");
            return (Criteria) this;
        }

        public Criteria andWorkTypeCodeLike(String value) {
            addCriterion("WORK_TYPE_CODE like", value, "workTypeCode");
            return (Criteria) this;
        }

        public Criteria andWorkTypeCodeNotLike(String value) {
            addCriterion("WORK_TYPE_CODE not like", value, "workTypeCode");
            return (Criteria) this;
        }

        public Criteria andWorkTypeCodeIn(List<String> values) {
            addCriterion("WORK_TYPE_CODE in", values, "workTypeCode");
            return (Criteria) this;
        }

        public Criteria andWorkTypeCodeNotIn(List<String> values) {
            addCriterion("WORK_TYPE_CODE not in", values, "workTypeCode");
            return (Criteria) this;
        }

        public Criteria andWorkTypeCodeBetween(String value1, String value2) {
            addCriterion("WORK_TYPE_CODE between", value1, value2, "workTypeCode");
            return (Criteria) this;
        }

        public Criteria andWorkTypeCodeNotBetween(String value1, String value2) {
            addCriterion("WORK_TYPE_CODE not between", value1, value2, "workTypeCode");
            return (Criteria) this;
        }

        public Criteria andCertificateCodeIsNull() {
            addCriterion("CERTIFICATE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCertificateCodeIsNotNull() {
            addCriterion("CERTIFICATE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCertificateCodeEqualTo(String value) {
            addCriterion("CERTIFICATE_CODE =", value, "certificateCode");
            return (Criteria) this;
        }

        public Criteria andCertificateCodeNotEqualTo(String value) {
            addCriterion("CERTIFICATE_CODE <>", value, "certificateCode");
            return (Criteria) this;
        }

        public Criteria andCertificateCodeGreaterThan(String value) {
            addCriterion("CERTIFICATE_CODE >", value, "certificateCode");
            return (Criteria) this;
        }

        public Criteria andCertificateCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CERTIFICATE_CODE >=", value, "certificateCode");
            return (Criteria) this;
        }

        public Criteria andCertificateCodeLessThan(String value) {
            addCriterion("CERTIFICATE_CODE <", value, "certificateCode");
            return (Criteria) this;
        }

        public Criteria andCertificateCodeLessThanOrEqualTo(String value) {
            addCriterion("CERTIFICATE_CODE <=", value, "certificateCode");
            return (Criteria) this;
        }

        public Criteria andCertificateCodeLike(String value) {
            addCriterion("CERTIFICATE_CODE like", value, "certificateCode");
            return (Criteria) this;
        }

        public Criteria andCertificateCodeNotLike(String value) {
            addCriterion("CERTIFICATE_CODE not like", value, "certificateCode");
            return (Criteria) this;
        }

        public Criteria andCertificateCodeIn(List<String> values) {
            addCriterion("CERTIFICATE_CODE in", values, "certificateCode");
            return (Criteria) this;
        }

        public Criteria andCertificateCodeNotIn(List<String> values) {
            addCriterion("CERTIFICATE_CODE not in", values, "certificateCode");
            return (Criteria) this;
        }

        public Criteria andCertificateCodeBetween(String value1, String value2) {
            addCriterion("CERTIFICATE_CODE between", value1, value2, "certificateCode");
            return (Criteria) this;
        }

        public Criteria andCertificateCodeNotBetween(String value1, String value2) {
            addCriterion("CERTIFICATE_CODE not between", value1, value2, "certificateCode");
            return (Criteria) this;
        }

        public Criteria andCertificateFirstIssueDateIsNull() {
            addCriterion("CERTIFICATE_FIRST_ISSUE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCertificateFirstIssueDateIsNotNull() {
            addCriterion("CERTIFICATE_FIRST_ISSUE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCertificateFirstIssueDateEqualTo(Date value) {
            addCriterion("CERTIFICATE_FIRST_ISSUE_DATE =", value, "certificateFirstIssueDate");
            return (Criteria) this;
        }

        public Criteria andCertificateFirstIssueDateNotEqualTo(Date value) {
            addCriterion("CERTIFICATE_FIRST_ISSUE_DATE <>", value, "certificateFirstIssueDate");
            return (Criteria) this;
        }

        public Criteria andCertificateFirstIssueDateGreaterThan(Date value) {
            addCriterion("CERTIFICATE_FIRST_ISSUE_DATE >", value, "certificateFirstIssueDate");
            return (Criteria) this;
        }

        public Criteria andCertificateFirstIssueDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CERTIFICATE_FIRST_ISSUE_DATE >=", value, "certificateFirstIssueDate");
            return (Criteria) this;
        }

        public Criteria andCertificateFirstIssueDateLessThan(Date value) {
            addCriterion("CERTIFICATE_FIRST_ISSUE_DATE <", value, "certificateFirstIssueDate");
            return (Criteria) this;
        }

        public Criteria andCertificateFirstIssueDateLessThanOrEqualTo(Date value) {
            addCriterion("CERTIFICATE_FIRST_ISSUE_DATE <=", value, "certificateFirstIssueDate");
            return (Criteria) this;
        }

        public Criteria andCertificateFirstIssueDateIn(List<Date> values) {
            addCriterion("CERTIFICATE_FIRST_ISSUE_DATE in", values, "certificateFirstIssueDate");
            return (Criteria) this;
        }

        public Criteria andCertificateFirstIssueDateNotIn(List<Date> values) {
            addCriterion("CERTIFICATE_FIRST_ISSUE_DATE not in", values, "certificateFirstIssueDate");
            return (Criteria) this;
        }

        public Criteria andCertificateFirstIssueDateBetween(Date value1, Date value2) {
            addCriterion("CERTIFICATE_FIRST_ISSUE_DATE between", value1, value2, "certificateFirstIssueDate");
            return (Criteria) this;
        }

        public Criteria andCertificateFirstIssueDateNotBetween(Date value1, Date value2) {
            addCriterion("CERTIFICATE_FIRST_ISSUE_DATE not between", value1, value2, "certificateFirstIssueDate");
            return (Criteria) this;
        }

        public Criteria andCertificateIssueDateIsNull() {
            addCriterion("CERTIFICATE_ISSUE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCertificateIssueDateIsNotNull() {
            addCriterion("CERTIFICATE_ISSUE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCertificateIssueDateEqualTo(Date value) {
            addCriterion("CERTIFICATE_ISSUE_DATE =", value, "certificateIssueDate");
            return (Criteria) this;
        }

        public Criteria andCertificateIssueDateNotEqualTo(Date value) {
            addCriterion("CERTIFICATE_ISSUE_DATE <>", value, "certificateIssueDate");
            return (Criteria) this;
        }

        public Criteria andCertificateIssueDateGreaterThan(Date value) {
            addCriterion("CERTIFICATE_ISSUE_DATE >", value, "certificateIssueDate");
            return (Criteria) this;
        }

        public Criteria andCertificateIssueDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CERTIFICATE_ISSUE_DATE >=", value, "certificateIssueDate");
            return (Criteria) this;
        }

        public Criteria andCertificateIssueDateLessThan(Date value) {
            addCriterion("CERTIFICATE_ISSUE_DATE <", value, "certificateIssueDate");
            return (Criteria) this;
        }

        public Criteria andCertificateIssueDateLessThanOrEqualTo(Date value) {
            addCriterion("CERTIFICATE_ISSUE_DATE <=", value, "certificateIssueDate");
            return (Criteria) this;
        }

        public Criteria andCertificateIssueDateIn(List<Date> values) {
            addCriterion("CERTIFICATE_ISSUE_DATE in", values, "certificateIssueDate");
            return (Criteria) this;
        }

        public Criteria andCertificateIssueDateNotIn(List<Date> values) {
            addCriterion("CERTIFICATE_ISSUE_DATE not in", values, "certificateIssueDate");
            return (Criteria) this;
        }

        public Criteria andCertificateIssueDateBetween(Date value1, Date value2) {
            addCriterion("CERTIFICATE_ISSUE_DATE between", value1, value2, "certificateIssueDate");
            return (Criteria) this;
        }

        public Criteria andCertificateIssueDateNotBetween(Date value1, Date value2) {
            addCriterion("CERTIFICATE_ISSUE_DATE not between", value1, value2, "certificateIssueDate");
            return (Criteria) this;
        }

        public Criteria andCertificateExpireDateIsNull() {
            addCriterion("CERTIFICATE_EXPIRE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCertificateExpireDateIsNotNull() {
            addCriterion("CERTIFICATE_EXPIRE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCertificateExpireDateEqualTo(Date value) {
            addCriterion("CERTIFICATE_EXPIRE_DATE =", value, "certificateExpireDate");
            return (Criteria) this;
        }

        public Criteria andCertificateExpireDateNotEqualTo(Date value) {
            addCriterion("CERTIFICATE_EXPIRE_DATE <>", value, "certificateExpireDate");
            return (Criteria) this;
        }

        public Criteria andCertificateExpireDateGreaterThan(Date value) {
            addCriterion("CERTIFICATE_EXPIRE_DATE >", value, "certificateExpireDate");
            return (Criteria) this;
        }

        public Criteria andCertificateExpireDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CERTIFICATE_EXPIRE_DATE >=", value, "certificateExpireDate");
            return (Criteria) this;
        }

        public Criteria andCertificateExpireDateLessThan(Date value) {
            addCriterion("CERTIFICATE_EXPIRE_DATE <", value, "certificateExpireDate");
            return (Criteria) this;
        }

        public Criteria andCertificateExpireDateLessThanOrEqualTo(Date value) {
            addCriterion("CERTIFICATE_EXPIRE_DATE <=", value, "certificateExpireDate");
            return (Criteria) this;
        }

        public Criteria andCertificateExpireDateIn(List<Date> values) {
            addCriterion("CERTIFICATE_EXPIRE_DATE in", values, "certificateExpireDate");
            return (Criteria) this;
        }

        public Criteria andCertificateExpireDateNotIn(List<Date> values) {
            addCriterion("CERTIFICATE_EXPIRE_DATE not in", values, "certificateExpireDate");
            return (Criteria) this;
        }

        public Criteria andCertificateExpireDateBetween(Date value1, Date value2) {
            addCriterion("CERTIFICATE_EXPIRE_DATE between", value1, value2, "certificateExpireDate");
            return (Criteria) this;
        }

        public Criteria andCertificateExpireDateNotBetween(Date value1, Date value2) {
            addCriterion("CERTIFICATE_EXPIRE_DATE not between", value1, value2, "certificateExpireDate");
            return (Criteria) this;
        }

        public Criteria andIssueOrganIsNull() {
            addCriterion("ISSUE_ORGAN is null");
            return (Criteria) this;
        }

        public Criteria andIssueOrganIsNotNull() {
            addCriterion("ISSUE_ORGAN is not null");
            return (Criteria) this;
        }

        public Criteria andIssueOrganEqualTo(String value) {
            addCriterion("ISSUE_ORGAN =", value, "issueOrgan");
            return (Criteria) this;
        }

        public Criteria andIssueOrganNotEqualTo(String value) {
            addCriterion("ISSUE_ORGAN <>", value, "issueOrgan");
            return (Criteria) this;
        }

        public Criteria andIssueOrganGreaterThan(String value) {
            addCriterion("ISSUE_ORGAN >", value, "issueOrgan");
            return (Criteria) this;
        }

        public Criteria andIssueOrganGreaterThanOrEqualTo(String value) {
            addCriterion("ISSUE_ORGAN >=", value, "issueOrgan");
            return (Criteria) this;
        }

        public Criteria andIssueOrganLessThan(String value) {
            addCriterion("ISSUE_ORGAN <", value, "issueOrgan");
            return (Criteria) this;
        }

        public Criteria andIssueOrganLessThanOrEqualTo(String value) {
            addCriterion("ISSUE_ORGAN <=", value, "issueOrgan");
            return (Criteria) this;
        }

        public Criteria andIssueOrganLike(String value) {
            addCriterion("ISSUE_ORGAN like", value, "issueOrgan");
            return (Criteria) this;
        }

        public Criteria andIssueOrganNotLike(String value) {
            addCriterion("ISSUE_ORGAN not like", value, "issueOrgan");
            return (Criteria) this;
        }

        public Criteria andIssueOrganIn(List<String> values) {
            addCriterion("ISSUE_ORGAN in", values, "issueOrgan");
            return (Criteria) this;
        }

        public Criteria andIssueOrganNotIn(List<String> values) {
            addCriterion("ISSUE_ORGAN not in", values, "issueOrgan");
            return (Criteria) this;
        }

        public Criteria andIssueOrganBetween(String value1, String value2) {
            addCriterion("ISSUE_ORGAN between", value1, value2, "issueOrgan");
            return (Criteria) this;
        }

        public Criteria andIssueOrganNotBetween(String value1, String value2) {
            addCriterion("ISSUE_ORGAN not between", value1, value2, "issueOrgan");
            return (Criteria) this;
        }

        public Criteria andIssueOrganZoneCodeIsNull() {
            addCriterion("ISSUE_ORGAN_ZONE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andIssueOrganZoneCodeIsNotNull() {
            addCriterion("ISSUE_ORGAN_ZONE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andIssueOrganZoneCodeEqualTo(String value) {
            addCriterion("ISSUE_ORGAN_ZONE_CODE =", value, "issueOrganZoneCode");
            return (Criteria) this;
        }

        public Criteria andIssueOrganZoneCodeNotEqualTo(String value) {
            addCriterion("ISSUE_ORGAN_ZONE_CODE <>", value, "issueOrganZoneCode");
            return (Criteria) this;
        }

        public Criteria andIssueOrganZoneCodeGreaterThan(String value) {
            addCriterion("ISSUE_ORGAN_ZONE_CODE >", value, "issueOrganZoneCode");
            return (Criteria) this;
        }

        public Criteria andIssueOrganZoneCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ISSUE_ORGAN_ZONE_CODE >=", value, "issueOrganZoneCode");
            return (Criteria) this;
        }

        public Criteria andIssueOrganZoneCodeLessThan(String value) {
            addCriterion("ISSUE_ORGAN_ZONE_CODE <", value, "issueOrganZoneCode");
            return (Criteria) this;
        }

        public Criteria andIssueOrganZoneCodeLessThanOrEqualTo(String value) {
            addCriterion("ISSUE_ORGAN_ZONE_CODE <=", value, "issueOrganZoneCode");
            return (Criteria) this;
        }

        public Criteria andIssueOrganZoneCodeLike(String value) {
            addCriterion("ISSUE_ORGAN_ZONE_CODE like", value, "issueOrganZoneCode");
            return (Criteria) this;
        }

        public Criteria andIssueOrganZoneCodeNotLike(String value) {
            addCriterion("ISSUE_ORGAN_ZONE_CODE not like", value, "issueOrganZoneCode");
            return (Criteria) this;
        }

        public Criteria andIssueOrganZoneCodeIn(List<String> values) {
            addCriterion("ISSUE_ORGAN_ZONE_CODE in", values, "issueOrganZoneCode");
            return (Criteria) this;
        }

        public Criteria andIssueOrganZoneCodeNotIn(List<String> values) {
            addCriterion("ISSUE_ORGAN_ZONE_CODE not in", values, "issueOrganZoneCode");
            return (Criteria) this;
        }

        public Criteria andIssueOrganZoneCodeBetween(String value1, String value2) {
            addCriterion("ISSUE_ORGAN_ZONE_CODE between", value1, value2, "issueOrganZoneCode");
            return (Criteria) this;
        }

        public Criteria andIssueOrganZoneCodeNotBetween(String value1, String value2) {
            addCriterion("ISSUE_ORGAN_ZONE_CODE not between", value1, value2, "issueOrganZoneCode");
            return (Criteria) this;
        }

        public Criteria andOrganCodeIsNull() {
            addCriterion("ORGAN_CODE is null");
            return (Criteria) this;
        }

        public Criteria andOrganCodeIsNotNull() {
            addCriterion("ORGAN_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andOrganCodeEqualTo(String value) {
            addCriterion("ORGAN_CODE =", value, "organCode");
            return (Criteria) this;
        }

        public Criteria andOrganCodeNotEqualTo(String value) {
            addCriterion("ORGAN_CODE <>", value, "organCode");
            return (Criteria) this;
        }

        public Criteria andOrganCodeGreaterThan(String value) {
            addCriterion("ORGAN_CODE >", value, "organCode");
            return (Criteria) this;
        }

        public Criteria andOrganCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ORGAN_CODE >=", value, "organCode");
            return (Criteria) this;
        }

        public Criteria andOrganCodeLessThan(String value) {
            addCriterion("ORGAN_CODE <", value, "organCode");
            return (Criteria) this;
        }

        public Criteria andOrganCodeLessThanOrEqualTo(String value) {
            addCriterion("ORGAN_CODE <=", value, "organCode");
            return (Criteria) this;
        }

        public Criteria andOrganCodeLike(String value) {
            addCriterion("ORGAN_CODE like", value, "organCode");
            return (Criteria) this;
        }

        public Criteria andOrganCodeNotLike(String value) {
            addCriterion("ORGAN_CODE not like", value, "organCode");
            return (Criteria) this;
        }

        public Criteria andOrganCodeIn(List<String> values) {
            addCriterion("ORGAN_CODE in", values, "organCode");
            return (Criteria) this;
        }

        public Criteria andOrganCodeNotIn(List<String> values) {
            addCriterion("ORGAN_CODE not in", values, "organCode");
            return (Criteria) this;
        }

        public Criteria andOrganCodeBetween(String value1, String value2) {
            addCriterion("ORGAN_CODE between", value1, value2, "organCode");
            return (Criteria) this;
        }

        public Criteria andOrganCodeNotBetween(String value1, String value2) {
            addCriterion("ORGAN_CODE not between", value1, value2, "organCode");
            return (Criteria) this;
        }

        public Criteria andCertificateStateIsNull() {
            addCriterion("CERTIFICATE_STATE is null");
            return (Criteria) this;
        }

        public Criteria andCertificateStateIsNotNull() {
            addCriterion("CERTIFICATE_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andCertificateStateEqualTo(String value) {
            addCriterion("CERTIFICATE_STATE =", value, "certificateState");
            return (Criteria) this;
        }

        public Criteria andCertificateStateNotEqualTo(String value) {
            addCriterion("CERTIFICATE_STATE <>", value, "certificateState");
            return (Criteria) this;
        }

        public Criteria andCertificateStateGreaterThan(String value) {
            addCriterion("CERTIFICATE_STATE >", value, "certificateState");
            return (Criteria) this;
        }

        public Criteria andCertificateStateGreaterThanOrEqualTo(String value) {
            addCriterion("CERTIFICATE_STATE >=", value, "certificateState");
            return (Criteria) this;
        }

        public Criteria andCertificateStateLessThan(String value) {
            addCriterion("CERTIFICATE_STATE <", value, "certificateState");
            return (Criteria) this;
        }

        public Criteria andCertificateStateLessThanOrEqualTo(String value) {
            addCriterion("CERTIFICATE_STATE <=", value, "certificateState");
            return (Criteria) this;
        }

        public Criteria andCertificateStateLike(String value) {
            addCriterion("CERTIFICATE_STATE like", value, "certificateState");
            return (Criteria) this;
        }

        public Criteria andCertificateStateNotLike(String value) {
            addCriterion("CERTIFICATE_STATE not like", value, "certificateState");
            return (Criteria) this;
        }

        public Criteria andCertificateStateIn(List<String> values) {
            addCriterion("CERTIFICATE_STATE in", values, "certificateState");
            return (Criteria) this;
        }

        public Criteria andCertificateStateNotIn(List<String> values) {
            addCriterion("CERTIFICATE_STATE not in", values, "certificateState");
            return (Criteria) this;
        }

        public Criteria andCertificateStateBetween(String value1, String value2) {
            addCriterion("CERTIFICATE_STATE between", value1, value2, "certificateState");
            return (Criteria) this;
        }

        public Criteria andCertificateStateNotBetween(String value1, String value2) {
            addCriterion("CERTIFICATE_STATE not between", value1, value2, "certificateState");
            return (Criteria) this;
        }

        public Criteria andCertificateTypeIsNull() {
            addCriterion("CERTIFICATE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCertificateTypeIsNotNull() {
            addCriterion("CERTIFICATE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCertificateTypeEqualTo(String value) {
            addCriterion("CERTIFICATE_TYPE =", value, "certificateType");
            return (Criteria) this;
        }

        public Criteria andCertificateTypeNotEqualTo(String value) {
            addCriterion("CERTIFICATE_TYPE <>", value, "certificateType");
            return (Criteria) this;
        }

        public Criteria andCertificateTypeGreaterThan(String value) {
            addCriterion("CERTIFICATE_TYPE >", value, "certificateType");
            return (Criteria) this;
        }

        public Criteria andCertificateTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CERTIFICATE_TYPE >=", value, "certificateType");
            return (Criteria) this;
        }

        public Criteria andCertificateTypeLessThan(String value) {
            addCriterion("CERTIFICATE_TYPE <", value, "certificateType");
            return (Criteria) this;
        }

        public Criteria andCertificateTypeLessThanOrEqualTo(String value) {
            addCriterion("CERTIFICATE_TYPE <=", value, "certificateType");
            return (Criteria) this;
        }

        public Criteria andCertificateTypeLike(String value) {
            addCriterion("CERTIFICATE_TYPE like", value, "certificateType");
            return (Criteria) this;
        }

        public Criteria andCertificateTypeNotLike(String value) {
            addCriterion("CERTIFICATE_TYPE not like", value, "certificateType");
            return (Criteria) this;
        }

        public Criteria andCertificateTypeIn(List<String> values) {
            addCriterion("CERTIFICATE_TYPE in", values, "certificateType");
            return (Criteria) this;
        }

        public Criteria andCertificateTypeNotIn(List<String> values) {
            addCriterion("CERTIFICATE_TYPE not in", values, "certificateType");
            return (Criteria) this;
        }

        public Criteria andCertificateTypeBetween(String value1, String value2) {
            addCriterion("CERTIFICATE_TYPE between", value1, value2, "certificateType");
            return (Criteria) this;
        }

        public Criteria andCertificateTypeNotBetween(String value1, String value2) {
            addCriterion("CERTIFICATE_TYPE not between", value1, value2, "certificateType");
            return (Criteria) this;
        }

        public Criteria andIcCardCertificateCodeicIsNull() {
            addCriterion("IC_CARD_CERTIFICATE_CODEIC is null");
            return (Criteria) this;
        }

        public Criteria andIcCardCertificateCodeicIsNotNull() {
            addCriterion("IC_CARD_CERTIFICATE_CODEIC is not null");
            return (Criteria) this;
        }

        public Criteria andIcCardCertificateCodeicEqualTo(String value) {
            addCriterion("IC_CARD_CERTIFICATE_CODEIC =", value, "icCardCertificateCodeic");
            return (Criteria) this;
        }

        public Criteria andIcCardCertificateCodeicNotEqualTo(String value) {
            addCriterion("IC_CARD_CERTIFICATE_CODEIC <>", value, "icCardCertificateCodeic");
            return (Criteria) this;
        }

        public Criteria andIcCardCertificateCodeicGreaterThan(String value) {
            addCriterion("IC_CARD_CERTIFICATE_CODEIC >", value, "icCardCertificateCodeic");
            return (Criteria) this;
        }

        public Criteria andIcCardCertificateCodeicGreaterThanOrEqualTo(String value) {
            addCriterion("IC_CARD_CERTIFICATE_CODEIC >=", value, "icCardCertificateCodeic");
            return (Criteria) this;
        }

        public Criteria andIcCardCertificateCodeicLessThan(String value) {
            addCriterion("IC_CARD_CERTIFICATE_CODEIC <", value, "icCardCertificateCodeic");
            return (Criteria) this;
        }

        public Criteria andIcCardCertificateCodeicLessThanOrEqualTo(String value) {
            addCriterion("IC_CARD_CERTIFICATE_CODEIC <=", value, "icCardCertificateCodeic");
            return (Criteria) this;
        }

        public Criteria andIcCardCertificateCodeicLike(String value) {
            addCriterion("IC_CARD_CERTIFICATE_CODEIC like", value, "icCardCertificateCodeic");
            return (Criteria) this;
        }

        public Criteria andIcCardCertificateCodeicNotLike(String value) {
            addCriterion("IC_CARD_CERTIFICATE_CODEIC not like", value, "icCardCertificateCodeic");
            return (Criteria) this;
        }

        public Criteria andIcCardCertificateCodeicIn(List<String> values) {
            addCriterion("IC_CARD_CERTIFICATE_CODEIC in", values, "icCardCertificateCodeic");
            return (Criteria) this;
        }

        public Criteria andIcCardCertificateCodeicNotIn(List<String> values) {
            addCriterion("IC_CARD_CERTIFICATE_CODEIC not in", values, "icCardCertificateCodeic");
            return (Criteria) this;
        }

        public Criteria andIcCardCertificateCodeicBetween(String value1, String value2) {
            addCriterion("IC_CARD_CERTIFICATE_CODEIC between", value1, value2, "icCardCertificateCodeic");
            return (Criteria) this;
        }

        public Criteria andIcCardCertificateCodeicNotBetween(String value1, String value2) {
            addCriterion("IC_CARD_CERTIFICATE_CODEIC not between", value1, value2, "icCardCertificateCodeic");
            return (Criteria) this;
        }

        public Criteria andDealTypeIsNull() {
            addCriterion("DEAL_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andDealTypeIsNotNull() {
            addCriterion("DEAL_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDealTypeEqualTo(String value) {
            addCriterion("DEAL_TYPE =", value, "dealType");
            return (Criteria) this;
        }

        public Criteria andDealTypeNotEqualTo(String value) {
            addCriterion("DEAL_TYPE <>", value, "dealType");
            return (Criteria) this;
        }

        public Criteria andDealTypeGreaterThan(String value) {
            addCriterion("DEAL_TYPE >", value, "dealType");
            return (Criteria) this;
        }

        public Criteria andDealTypeGreaterThanOrEqualTo(String value) {
            addCriterion("DEAL_TYPE >=", value, "dealType");
            return (Criteria) this;
        }

        public Criteria andDealTypeLessThan(String value) {
            addCriterion("DEAL_TYPE <", value, "dealType");
            return (Criteria) this;
        }

        public Criteria andDealTypeLessThanOrEqualTo(String value) {
            addCriterion("DEAL_TYPE <=", value, "dealType");
            return (Criteria) this;
        }

        public Criteria andDealTypeLike(String value) {
            addCriterion("DEAL_TYPE like", value, "dealType");
            return (Criteria) this;
        }

        public Criteria andDealTypeNotLike(String value) {
            addCriterion("DEAL_TYPE not like", value, "dealType");
            return (Criteria) this;
        }

        public Criteria andDealTypeIn(List<String> values) {
            addCriterion("DEAL_TYPE in", values, "dealType");
            return (Criteria) this;
        }

        public Criteria andDealTypeNotIn(List<String> values) {
            addCriterion("DEAL_TYPE not in", values, "dealType");
            return (Criteria) this;
        }

        public Criteria andDealTypeBetween(String value1, String value2) {
            addCriterion("DEAL_TYPE between", value1, value2, "dealType");
            return (Criteria) this;
        }

        public Criteria andDealTypeNotBetween(String value1, String value2) {
            addCriterion("DEAL_TYPE not between", value1, value2, "dealType");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DW_BASEINFO_STAFF_CERT
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 24 08:19:14 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DW_BASEINFO_STAFF_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}