/*
 * Project: RDTRANS
 * Copyright 2015 CTTIC
 * All right reserved.
 */
package cn.cttic.roadtransapi.orm.roadway.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * 建立日期 : 2015-7-28 下午1:43:59<br>
 * 作者 : liuzhenliang@cttic.cn<br>
 * 模块 : <br>
 * 描述 : <br>
 * 修改历史 <br>
 * 序号 日期 修改人 修改原因 <br>
 * 1 <br>
 * 2 <br>
 */
public class DwBaseinfoLineOperExample
{
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public DwBaseinfoLineOperExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }
        
        public Criteria andOwnerNameEqualTo(String value) {
            addCriterion("b.owner_name =", value, "owner_name");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeIsNull() {
            addCriterion("PROVINCE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeIsNotNull() {
            addCriterion("PROVINCE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeEqualTo(Integer value) {
            addCriterion("b.PROVINCE_CODE =", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeNotEqualTo(Integer value) {
            addCriterion("PROVINCE_CODE <>", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeGreaterThan(Integer value) {
            addCriterion("PROVINCE_CODE >", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("PROVINCE_CODE >=", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeLessThan(Integer value) {
            addCriterion("PROVINCE_CODE <", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeLessThanOrEqualTo(Integer value) {
            addCriterion("PROVINCE_CODE <=", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeIn(List<Integer> values) {
            addCriterion("PROVINCE_CODE in", values, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeNotIn(List<Integer> values) {
            addCriterion("PROVINCE_CODE not in", values, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeBetween(Integer value1, Integer value2) {
            addCriterion("PROVINCE_CODE between", value1, value2, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("PROVINCE_CODE not between", value1, value2, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andPhyLineIdIsNull() {
            addCriterion("PHY_LINE_ID is null");
            return (Criteria) this;
        }

        public Criteria andPhyLineIdIsNotNull() {
            addCriterion("PHY_LINE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPhyLineIdEqualTo(String value) {
            addCriterion("PHY_LINE_ID =", value, "phyLineId");
            return (Criteria) this;
        }

        public Criteria andPhyLineIdNotEqualTo(String value) {
            addCriterion("PHY_LINE_ID <>", value, "phyLineId");
            return (Criteria) this;
        }

        public Criteria andPhyLineIdGreaterThan(String value) {
            addCriterion("PHY_LINE_ID >", value, "phyLineId");
            return (Criteria) this;
        }

        public Criteria andPhyLineIdGreaterThanOrEqualTo(String value) {
            addCriterion("PHY_LINE_ID >=", value, "phyLineId");
            return (Criteria) this;
        }

        public Criteria andPhyLineIdLessThan(String value) {
            addCriterion("PHY_LINE_ID <", value, "phyLineId");
            return (Criteria) this;
        }

        public Criteria andPhyLineIdLessThanOrEqualTo(String value) {
            addCriterion("PHY_LINE_ID <=", value, "phyLineId");
            return (Criteria) this;
        }

        public Criteria andPhyLineIdLike(String value) {
            addCriterion("PHY_LINE_ID like", value, "phyLineId");
            return (Criteria) this;
        }

        public Criteria andPhyLineIdNotLike(String value) {
            addCriterion("PHY_LINE_ID not like", value, "phyLineId");
            return (Criteria) this;
        }

        public Criteria andPhyLineIdIn(List<String> values) {
            addCriterion("PHY_LINE_ID in", values, "phyLineId");
            return (Criteria) this;
        }

        public Criteria andPhyLineIdNotIn(List<String> values) {
            addCriterion("PHY_LINE_ID not in", values, "phyLineId");
            return (Criteria) this;
        }

        public Criteria andPhyLineIdBetween(String value1, String value2) {
            addCriterion("PHY_LINE_ID between", value1, value2, "phyLineId");
            return (Criteria) this;
        }

        public Criteria andPhyLineIdNotBetween(String value1, String value2) {
            addCriterion("PHY_LINE_ID not between", value1, value2, "phyLineId");
            return (Criteria) this;
        }

        public Criteria andOperLineIdIsNull() {
            addCriterion("OPER_LINE_ID is null");
            return (Criteria) this;
        }

        public Criteria andOperLineIdIsNotNull() {
            addCriterion("OPER_LINE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOperLineIdEqualTo(String value) {
            addCriterion("OPER_LINE_ID =", value, "operLineId");
            return (Criteria) this;
        }

        public Criteria andOperLineIdNotEqualTo(String value) {
            addCriterion("OPER_LINE_ID <>", value, "operLineId");
            return (Criteria) this;
        }

        public Criteria andOperLineIdGreaterThan(String value) {
            addCriterion("OPER_LINE_ID >", value, "operLineId");
            return (Criteria) this;
        }

        public Criteria andOperLineIdGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_LINE_ID >=", value, "operLineId");
            return (Criteria) this;
        }

        public Criteria andOperLineIdLessThan(String value) {
            addCriterion("OPER_LINE_ID <", value, "operLineId");
            return (Criteria) this;
        }

        public Criteria andOperLineIdLessThanOrEqualTo(String value) {
            addCriterion("OPER_LINE_ID <=", value, "operLineId");
            return (Criteria) this;
        }

        public Criteria andOperLineIdLike(String value) {
            addCriterion("OPER_LINE_ID like", value, "operLineId");
            return (Criteria) this;
        }

        public Criteria andOperLineIdNotLike(String value) {
            addCriterion("OPER_LINE_ID not like", value, "operLineId");
            return (Criteria) this;
        }

        public Criteria andOperLineIdIn(List<String> values) {
            addCriterion("OPER_LINE_ID in", values, "operLineId");
            return (Criteria) this;
        }

        public Criteria andOperLineIdNotIn(List<String> values) {
            addCriterion("OPER_LINE_ID not in", values, "operLineId");
            return (Criteria) this;
        }

        public Criteria andOperLineIdBetween(String value1, String value2) {
            addCriterion("OPER_LINE_ID between", value1, value2, "operLineId");
            return (Criteria) this;
        }

        public Criteria andOperLineIdNotBetween(String value1, String value2) {
            addCriterion("OPER_LINE_ID not between", value1, value2, "operLineId");
            return (Criteria) this;
        }

        public Criteria andOperLineNameIsNull() {
            addCriterion("OPER_LINE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOperLineNameIsNotNull() {
            addCriterion("OPER_LINE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOperLineNameEqualTo(String value) {
            addCriterion("OPER_LINE_NAME =", value, "operLineName");
            return (Criteria) this;
        }

        public Criteria andOperLineNameNotEqualTo(String value) {
            addCriterion("OPER_LINE_NAME <>", value, "operLineName");
            return (Criteria) this;
        }

        public Criteria andOperLineNameGreaterThan(String value) {
            addCriterion("OPER_LINE_NAME >", value, "operLineName");
            return (Criteria) this;
        }

        public Criteria andOperLineNameGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_LINE_NAME >=", value, "operLineName");
            return (Criteria) this;
        }

        public Criteria andOperLineNameLessThan(String value) {
            addCriterion("OPER_LINE_NAME <", value, "operLineName");
            return (Criteria) this;
        }

        public Criteria andOperLineNameLessThanOrEqualTo(String value) {
            addCriterion("OPER_LINE_NAME <=", value, "operLineName");
            return (Criteria) this;
        }

        public Criteria andOperLineNameLike(String value) {
            addCriterion("OPER_LINE_NAME like", value, "operLineName");
            return (Criteria) this;
        }

        public Criteria andOperLineNameNotLike(String value) {
            addCriterion("OPER_LINE_NAME not like", value, "operLineName");
            return (Criteria) this;
        }

        public Criteria andOperLineNameIn(List<String> values) {
            addCriterion("OPER_LINE_NAME in", values, "operLineName");
            return (Criteria) this;
        }

        public Criteria andOperLineNameNotIn(List<String> values) {
            addCriterion("OPER_LINE_NAME not in", values, "operLineName");
            return (Criteria) this;
        }

        public Criteria andOperLineNameBetween(String value1, String value2) {
            addCriterion("OPER_LINE_NAME between", value1, value2, "operLineName");
            return (Criteria) this;
        }

        public Criteria andOperLineNameNotBetween(String value1, String value2) {
            addCriterion("OPER_LINE_NAME not between", value1, value2, "operLineName");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIsNull() {
            addCriterion("OWNER_ID is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIsNotNull() {
            addCriterion("OWNER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdEqualTo(String value) {
            addCriterion("OWNER_ID =", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotEqualTo(String value) {
            addCriterion("OWNER_ID <>", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThan(String value) {
            addCriterion("OWNER_ID >", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThanOrEqualTo(String value) {
            addCriterion("OWNER_ID >=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThan(String value) {
            addCriterion("OWNER_ID <", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThanOrEqualTo(String value) {
            addCriterion("OWNER_ID <=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLike(String value) {
            addCriterion("OWNER_ID like", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotLike(String value) {
            addCriterion("OWNER_ID not like", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIn(List<String> values) {
            addCriterion("OWNER_ID in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotIn(List<String> values) {
            addCriterion("OWNER_ID not in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdBetween(String value1, String value2) {
            addCriterion("OWNER_ID between", value1, value2, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotBetween(String value1, String value2) {
            addCriterion("OWNER_ID not between", value1, value2, "ownerId");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeIsNull() {
            addCriterion("LINE_OP_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeIsNotNull() {
            addCriterion("LINE_OP_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeEqualTo(String value) {
            addCriterion("LINE_OP_TYPE =", value, "lineOpType");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeNotEqualTo(String value) {
            addCriterion("LINE_OP_TYPE <>", value, "lineOpType");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeGreaterThan(String value) {
            addCriterion("LINE_OP_TYPE >", value, "lineOpType");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeGreaterThanOrEqualTo(String value) {
            addCriterion("LINE_OP_TYPE >=", value, "lineOpType");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeLessThan(String value) {
            addCriterion("LINE_OP_TYPE <", value, "lineOpType");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeLessThanOrEqualTo(String value) {
            addCriterion("LINE_OP_TYPE <=", value, "lineOpType");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeLike(String value) {
            addCriterion("LINE_OP_TYPE like", value, "lineOpType");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeNotLike(String value) {
            addCriterion("LINE_OP_TYPE not like", value, "lineOpType");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeIn(List<String> values) {
            addCriterion("LINE_OP_TYPE in", values, "lineOpType");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeNotIn(List<String> values) {
            addCriterion("LINE_OP_TYPE not in", values, "lineOpType");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeBetween(String value1, String value2) {
            addCriterion("LINE_OP_TYPE between", value1, value2, "lineOpType");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeNotBetween(String value1, String value2) {
            addCriterion("LINE_OP_TYPE not between", value1, value2, "lineOpType");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeCodeIsNull() {
            addCriterion("LINE_OP_TYPE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeCodeIsNotNull() {
            addCriterion("LINE_OP_TYPE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeCodeEqualTo(String value) {
            addCriterion("LINE_OP_TYPE_CODE =", value, "lineOpTypeCode");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeCodeNotEqualTo(String value) {
            addCriterion("LINE_OP_TYPE_CODE <>", value, "lineOpTypeCode");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeCodeGreaterThan(String value) {
            addCriterion("LINE_OP_TYPE_CODE >", value, "lineOpTypeCode");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("LINE_OP_TYPE_CODE >=", value, "lineOpTypeCode");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeCodeLessThan(String value) {
            addCriterion("LINE_OP_TYPE_CODE <", value, "lineOpTypeCode");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("LINE_OP_TYPE_CODE <=", value, "lineOpTypeCode");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeCodeLike(String value) {
            addCriterion("LINE_OP_TYPE_CODE like", value, "lineOpTypeCode");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeCodeNotLike(String value) {
            addCriterion("LINE_OP_TYPE_CODE not like", value, "lineOpTypeCode");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeCodeIn(List<String> values) {
            addCriterion("LINE_OP_TYPE_CODE in", values, "lineOpTypeCode");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeCodeNotIn(List<String> values) {
            addCriterion("LINE_OP_TYPE_CODE not in", values, "lineOpTypeCode");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeCodeBetween(String value1, String value2) {
            addCriterion("LINE_OP_TYPE_CODE between", value1, value2, "lineOpTypeCode");
            return (Criteria) this;
        }

        public Criteria andLineOpTypeCodeNotBetween(String value1, String value2) {
            addCriterion("LINE_OP_TYPE_CODE not between", value1, value2, "lineOpTypeCode");
            return (Criteria) this;
        }

        public Criteria andStartStationIsNull() {
            addCriterion("START_STATION is null");
            return (Criteria) this;
        }

        public Criteria andStartStationIsNotNull() {
            addCriterion("START_STATION is not null");
            return (Criteria) this;
        }

        public Criteria andStartStationEqualTo(String value) {
            addCriterion("START_STATION =", value, "startStation");
            return (Criteria) this;
        }

        public Criteria andStartStationNotEqualTo(String value) {
            addCriterion("START_STATION <>", value, "startStation");
            return (Criteria) this;
        }

        public Criteria andStartStationGreaterThan(String value) {
            addCriterion("START_STATION >", value, "startStation");
            return (Criteria) this;
        }

        public Criteria andStartStationGreaterThanOrEqualTo(String value) {
            addCriterion("START_STATION >=", value, "startStation");
            return (Criteria) this;
        }

        public Criteria andStartStationLessThan(String value) {
            addCriterion("START_STATION <", value, "startStation");
            return (Criteria) this;
        }

        public Criteria andStartStationLessThanOrEqualTo(String value) {
            addCriterion("START_STATION <=", value, "startStation");
            return (Criteria) this;
        }

        public Criteria andStartStationLike(String value) {
            addCriterion("START_STATION like", value, "startStation");
            return (Criteria) this;
        }

        public Criteria andStartStationNotLike(String value) {
            addCriterion("START_STATION not like", value, "startStation");
            return (Criteria) this;
        }

        public Criteria andStartStationIn(List<String> values) {
            addCriterion("START_STATION in", values, "startStation");
            return (Criteria) this;
        }

        public Criteria andStartStationNotIn(List<String> values) {
            addCriterion("START_STATION not in", values, "startStation");
            return (Criteria) this;
        }

        public Criteria andStartStationBetween(String value1, String value2) {
            addCriterion("START_STATION between", value1, value2, "startStation");
            return (Criteria) this;
        }

        public Criteria andStartStationNotBetween(String value1, String value2) {
            addCriterion("START_STATION not between", value1, value2, "startStation");
            return (Criteria) this;
        }

        public Criteria andStartStationZoneIsNull() {
            addCriterion("START_STATION_ZONE is null");
            return (Criteria) this;
        }

        public Criteria andStartStationZoneIsNotNull() {
            addCriterion("START_STATION_ZONE is not null");
            return (Criteria) this;
        }

        public Criteria andStartStationZoneEqualTo(Long value) {
            addCriterion("START_STATION_ZONE =", value, "startStationZone");
            return (Criteria) this;
        }

        public Criteria andStartStationZoneNotEqualTo(Long value) {
            addCriterion("START_STATION_ZONE <>", value, "startStationZone");
            return (Criteria) this;
        }

        public Criteria andStartStationZoneGreaterThan(Long value) {
            addCriterion("START_STATION_ZONE >", value, "startStationZone");
            return (Criteria) this;
        }

        public Criteria andStartStationZoneGreaterThanOrEqualTo(Long value) {
            addCriterion("START_STATION_ZONE >=", value, "startStationZone");
            return (Criteria) this;
        }

        public Criteria andStartStationZoneLessThan(Long value) {
            addCriterion("START_STATION_ZONE <", value, "startStationZone");
            return (Criteria) this;
        }

        public Criteria andStartStationZoneLessThanOrEqualTo(Long value) {
            addCriterion("START_STATION_ZONE <=", value, "startStationZone");
            return (Criteria) this;
        }

        public Criteria andStartStationZoneIn(List<Long> values) {
            addCriterion("START_STATION_ZONE in", values, "startStationZone");
            return (Criteria) this;
        }

        public Criteria andStartStationZoneNotIn(List<Long> values) {
            addCriterion("START_STATION_ZONE not in", values, "startStationZone");
            return (Criteria) this;
        }

        public Criteria andStartStationZoneBetween(Long value1, Long value2) {
            addCriterion("START_STATION_ZONE between", value1, value2, "startStationZone");
            return (Criteria) this;
        }

        public Criteria andStartStationZoneNotBetween(Long value1, Long value2) {
            addCriterion("START_STATION_ZONE not between", value1, value2, "startStationZone");
            return (Criteria) this;
        }

        public Criteria andEndStationIsNull() {
            addCriterion("END_STATION is null");
            return (Criteria) this;
        }

        public Criteria andEndStationIsNotNull() {
            addCriterion("END_STATION is not null");
            return (Criteria) this;
        }

        public Criteria andEndStationEqualTo(String value) {
            addCriterion("END_STATION =", value, "endStation");
            return (Criteria) this;
        }

        public Criteria andEndStationNotEqualTo(String value) {
            addCriterion("END_STATION <>", value, "endStation");
            return (Criteria) this;
        }

        public Criteria andEndStationGreaterThan(String value) {
            addCriterion("END_STATION >", value, "endStation");
            return (Criteria) this;
        }

        public Criteria andEndStationGreaterThanOrEqualTo(String value) {
            addCriterion("END_STATION >=", value, "endStation");
            return (Criteria) this;
        }

        public Criteria andEndStationLessThan(String value) {
            addCriterion("END_STATION <", value, "endStation");
            return (Criteria) this;
        }

        public Criteria andEndStationLessThanOrEqualTo(String value) {
            addCriterion("END_STATION <=", value, "endStation");
            return (Criteria) this;
        }

        public Criteria andEndStationLike(String value) {
            addCriterion("END_STATION like", value, "endStation");
            return (Criteria) this;
        }

        public Criteria andEndStationNotLike(String value) {
            addCriterion("END_STATION not like", value, "endStation");
            return (Criteria) this;
        }

        public Criteria andEndStationIn(List<String> values) {
            addCriterion("END_STATION in", values, "endStation");
            return (Criteria) this;
        }

        public Criteria andEndStationNotIn(List<String> values) {
            addCriterion("END_STATION not in", values, "endStation");
            return (Criteria) this;
        }

        public Criteria andEndStationBetween(String value1, String value2) {
            addCriterion("END_STATION between", value1, value2, "endStation");
            return (Criteria) this;
        }

        public Criteria andEndStationNotBetween(String value1, String value2) {
            addCriterion("END_STATION not between", value1, value2, "endStation");
            return (Criteria) this;
        }

        public Criteria andEndStationZoneIsNull() {
            addCriterion("END_STATION_ZONE is null");
            return (Criteria) this;
        }

        public Criteria andEndStationZoneIsNotNull() {
            addCriterion("END_STATION_ZONE is not null");
            return (Criteria) this;
        }

        public Criteria andEndStationZoneEqualTo(Long value) {
            addCriterion("END_STATION_ZONE =", value, "endStationZone");
            return (Criteria) this;
        }

        public Criteria andEndStationZoneNotEqualTo(Long value) {
            addCriterion("END_STATION_ZONE <>", value, "endStationZone");
            return (Criteria) this;
        }

        public Criteria andEndStationZoneGreaterThan(Long value) {
            addCriterion("END_STATION_ZONE >", value, "endStationZone");
            return (Criteria) this;
        }

        public Criteria andEndStationZoneGreaterThanOrEqualTo(Long value) {
            addCriterion("END_STATION_ZONE >=", value, "endStationZone");
            return (Criteria) this;
        }

        public Criteria andEndStationZoneLessThan(Long value) {
            addCriterion("END_STATION_ZONE <", value, "endStationZone");
            return (Criteria) this;
        }

        public Criteria andEndStationZoneLessThanOrEqualTo(Long value) {
            addCriterion("END_STATION_ZONE <=", value, "endStationZone");
            return (Criteria) this;
        }

        public Criteria andEndStationZoneIn(List<Long> values) {
            addCriterion("END_STATION_ZONE in", values, "endStationZone");
            return (Criteria) this;
        }

        public Criteria andEndStationZoneNotIn(List<Long> values) {
            addCriterion("END_STATION_ZONE not in", values, "endStationZone");
            return (Criteria) this;
        }

        public Criteria andEndStationZoneBetween(Long value1, Long value2) {
            addCriterion("END_STATION_ZONE between", value1, value2, "endStationZone");
            return (Criteria) this;
        }

        public Criteria andEndStationZoneNotBetween(Long value1, Long value2) {
            addCriterion("END_STATION_ZONE not between", value1, value2, "endStationZone");
            return (Criteria) this;
        }

        public Criteria andLineTransPlaceIsNull() {
            addCriterion("LINE_TRANS_PLACE is null");
            return (Criteria) this;
        }

        public Criteria andLineTransPlaceIsNotNull() {
            addCriterion("LINE_TRANS_PLACE is not null");
            return (Criteria) this;
        }

        public Criteria andLineTransPlaceEqualTo(String value) {
            addCriterion("LINE_TRANS_PLACE =", value, "lineTransPlace");
            return (Criteria) this;
        }

        public Criteria andLineTransPlaceNotEqualTo(String value) {
            addCriterion("LINE_TRANS_PLACE <>", value, "lineTransPlace");
            return (Criteria) this;
        }

        public Criteria andLineTransPlaceGreaterThan(String value) {
            addCriterion("LINE_TRANS_PLACE >", value, "lineTransPlace");
            return (Criteria) this;
        }

        public Criteria andLineTransPlaceGreaterThanOrEqualTo(String value) {
            addCriterion("LINE_TRANS_PLACE >=", value, "lineTransPlace");
            return (Criteria) this;
        }

        public Criteria andLineTransPlaceLessThan(String value) {
            addCriterion("LINE_TRANS_PLACE <", value, "lineTransPlace");
            return (Criteria) this;
        }

        public Criteria andLineTransPlaceLessThanOrEqualTo(String value) {
            addCriterion("LINE_TRANS_PLACE <=", value, "lineTransPlace");
            return (Criteria) this;
        }

        public Criteria andLineTransPlaceLike(String value) {
            addCriterion("LINE_TRANS_PLACE like", "%"+value+"%", "lineTransPlace");
            return (Criteria) this;
        }

        public Criteria andLineTransPlaceNotLike(String value) {
            addCriterion("LINE_TRANS_PLACE not like", value, "lineTransPlace");
            return (Criteria) this;
        }

        public Criteria andLineTransPlaceIn(List<String> values) {
            addCriterion("LINE_TRANS_PLACE in", values, "lineTransPlace");
            return (Criteria) this;
        }

        public Criteria andLineTransPlaceNotIn(List<String> values) {
            addCriterion("LINE_TRANS_PLACE not in", values, "lineTransPlace");
            return (Criteria) this;
        }

        public Criteria andLineTransPlaceBetween(String value1, String value2) {
            addCriterion("LINE_TRANS_PLACE between", value1, value2, "lineTransPlace");
            return (Criteria) this;
        }

        public Criteria andLineTransPlaceNotBetween(String value1, String value2) {
            addCriterion("LINE_TRANS_PLACE not between", value1, value2, "lineTransPlace");
            return (Criteria) this;
        }

        public Criteria andLineFrequencyIsNull() {
            addCriterion("LINE_FREQUENCY is null");
            return (Criteria) this;
        }

        public Criteria andLineFrequencyIsNotNull() {
            addCriterion("LINE_FREQUENCY is not null");
            return (Criteria) this;
        }

        public Criteria andLineFrequencyEqualTo(Integer value) {
            addCriterion("LINE_FREQUENCY =", value, "lineFrequency");
            return (Criteria) this;
        }

        public Criteria andLineFrequencyNotEqualTo(Integer value) {
            addCriterion("LINE_FREQUENCY <>", value, "lineFrequency");
            return (Criteria) this;
        }

        public Criteria andLineFrequencyGreaterThan(Integer value) {
            addCriterion("LINE_FREQUENCY >", value, "lineFrequency");
            return (Criteria) this;
        }

        public Criteria andLineFrequencyGreaterThanOrEqualTo(Integer value) {
            addCriterion("LINE_FREQUENCY >=", value, "lineFrequency");
            return (Criteria) this;
        }

        public Criteria andLineFrequencyLessThan(Integer value) {
            addCriterion("LINE_FREQUENCY <", value, "lineFrequency");
            return (Criteria) this;
        }

        public Criteria andLineFrequencyLessThanOrEqualTo(Integer value) {
            addCriterion("LINE_FREQUENCY <=", value, "lineFrequency");
            return (Criteria) this;
        }

        public Criteria andLineFrequencyIn(List<Integer> values) {
            addCriterion("LINE_FREQUENCY in", values, "lineFrequency");
            return (Criteria) this;
        }

        public Criteria andLineFrequencyNotIn(List<Integer> values) {
            addCriterion("LINE_FREQUENCY not in", values, "lineFrequency");
            return (Criteria) this;
        }

        public Criteria andLineFrequencyBetween(Integer value1, Integer value2) {
            addCriterion("LINE_FREQUENCY between", value1, value2, "lineFrequency");
            return (Criteria) this;
        }

        public Criteria andLineFrequencyNotBetween(Integer value1, Integer value2) {
            addCriterion("LINE_FREQUENCY not between", value1, value2, "lineFrequency");
            return (Criteria) this;
        }

        public Criteria andLineMileageIsNull() {
            addCriterion("LINE_MILEAGE is null");
            return (Criteria) this;
        }

        public Criteria andLineMileageIsNotNull() {
            addCriterion("LINE_MILEAGE is not null");
            return (Criteria) this;
        }

        public Criteria andLineMileageEqualTo(Long value) {
            addCriterion("LINE_MILEAGE =", value, "lineMileage");
            return (Criteria) this;
        }

        public Criteria andLineMileageNotEqualTo(Long value) {
            addCriterion("LINE_MILEAGE <>", value, "lineMileage");
            return (Criteria) this;
        }

        public Criteria andLineMileageGreaterThan(Long value) {
            addCriterion("LINE_MILEAGE >", value, "lineMileage");
            return (Criteria) this;
        }

        public Criteria andLineMileageGreaterThanOrEqualTo(Long value) {
            addCriterion("LINE_MILEAGE >=", value, "lineMileage");
            return (Criteria) this;
        }

        public Criteria andLineMileageLessThan(Long value) {
            addCriterion("LINE_MILEAGE <", value, "lineMileage");
            return (Criteria) this;
        }

        public Criteria andLineMileageLessThanOrEqualTo(Long value) {
            addCriterion("LINE_MILEAGE <=", value, "lineMileage");
            return (Criteria) this;
        }

        public Criteria andLineMileageIn(List<Long> values) {
            addCriterion("LINE_MILEAGE in", values, "lineMileage");
            return (Criteria) this;
        }

        public Criteria andLineMileageNotIn(List<Long> values) {
            addCriterion("LINE_MILEAGE not in", values, "lineMileage");
            return (Criteria) this;
        }

        public Criteria andLineMileageBetween(Long value1, Long value2) {
            addCriterion("LINE_MILEAGE between", value1, value2, "lineMileage");
            return (Criteria) this;
        }

        public Criteria andLineMileageNotBetween(Long value1, Long value2) {
            addCriterion("LINE_MILEAGE not between", value1, value2, "lineMileage");
            return (Criteria) this;
        }

        public Criteria andLineHighwayMileageIsNull() {
            addCriterion("LINE_HIGHWAY_MILEAGE is null");
            return (Criteria) this;
        }

        public Criteria andLineHighwayMileageIsNotNull() {
            addCriterion("LINE_HIGHWAY_MILEAGE is not null");
            return (Criteria) this;
        }

        public Criteria andLineHighwayMileageEqualTo(Long value) {
            addCriterion("LINE_HIGHWAY_MILEAGE =", value, "lineHighwayMileage");
            return (Criteria) this;
        }

        public Criteria andLineHighwayMileageNotEqualTo(Long value) {
            addCriterion("LINE_HIGHWAY_MILEAGE <>", value, "lineHighwayMileage");
            return (Criteria) this;
        }

        public Criteria andLineHighwayMileageGreaterThan(Long value) {
            addCriterion("LINE_HIGHWAY_MILEAGE >", value, "lineHighwayMileage");
            return (Criteria) this;
        }

        public Criteria andLineHighwayMileageGreaterThanOrEqualTo(Long value) {
            addCriterion("LINE_HIGHWAY_MILEAGE >=", value, "lineHighwayMileage");
            return (Criteria) this;
        }

        public Criteria andLineHighwayMileageLessThan(Long value) {
            addCriterion("LINE_HIGHWAY_MILEAGE <", value, "lineHighwayMileage");
            return (Criteria) this;
        }

        public Criteria andLineHighwayMileageLessThanOrEqualTo(Long value) {
            addCriterion("LINE_HIGHWAY_MILEAGE <=", value, "lineHighwayMileage");
            return (Criteria) this;
        }

        public Criteria andLineHighwayMileageIn(List<Long> values) {
            addCriterion("LINE_HIGHWAY_MILEAGE in", values, "lineHighwayMileage");
            return (Criteria) this;
        }

        public Criteria andLineHighwayMileageNotIn(List<Long> values) {
            addCriterion("LINE_HIGHWAY_MILEAGE not in", values, "lineHighwayMileage");
            return (Criteria) this;
        }

        public Criteria andLineHighwayMileageBetween(Long value1, Long value2) {
            addCriterion("LINE_HIGHWAY_MILEAGE between", value1, value2, "lineHighwayMileage");
            return (Criteria) this;
        }

        public Criteria andLineHighwayMileageNotBetween(Long value1, Long value2) {
            addCriterion("LINE_HIGHWAY_MILEAGE not between", value1, value2, "lineHighwayMileage");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneIsNull() {
            addCriterion("LINE_OPER_ZONE is null");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneIsNotNull() {
            addCriterion("LINE_OPER_ZONE is not null");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneEqualTo(String value) {
            addCriterion("LINE_OPER_ZONE =", value, "lineOperZone");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneNotEqualTo(String value) {
            addCriterion("LINE_OPER_ZONE <>", value, "lineOperZone");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneGreaterThan(String value) {
            addCriterion("LINE_OPER_ZONE >", value, "lineOperZone");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneGreaterThanOrEqualTo(String value) {
            addCriterion("LINE_OPER_ZONE >=", value, "lineOperZone");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneLessThan(String value) {
            addCriterion("LINE_OPER_ZONE <", value, "lineOperZone");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneLessThanOrEqualTo(String value) {
            addCriterion("LINE_OPER_ZONE <=", value, "lineOperZone");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneLike(String value) {
            addCriterion("LINE_OPER_ZONE like", value, "lineOperZone");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneNotLike(String value) {
            addCriterion("LINE_OPER_ZONE not like", value, "lineOperZone");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneIn(List<String> values) {
            addCriterion("LINE_OPER_ZONE in", values, "lineOperZone");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneNotIn(List<String> values) {
            addCriterion("LINE_OPER_ZONE not in", values, "lineOperZone");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneBetween(String value1, String value2) {
            addCriterion("LINE_OPER_ZONE between", value1, value2, "lineOperZone");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneNotBetween(String value1, String value2) {
            addCriterion("LINE_OPER_ZONE not between", value1, value2, "lineOperZone");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneCodeIsNull() {
            addCriterion("LINE_OPER_ZONE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneCodeIsNotNull() {
            addCriterion("LINE_OPER_ZONE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneCodeEqualTo(String value) {
            addCriterion("LINE_OPER_ZONE_CODE =", value, "lineOperZoneCode");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneCodeNotEqualTo(String value) {
            addCriterion("LINE_OPER_ZONE_CODE <>", value, "lineOperZoneCode");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneCodeGreaterThan(String value) {
            addCriterion("LINE_OPER_ZONE_CODE >", value, "lineOperZoneCode");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneCodeGreaterThanOrEqualTo(String value) {
            addCriterion("LINE_OPER_ZONE_CODE >=", value, "lineOperZoneCode");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneCodeLessThan(String value) {
            addCriterion("LINE_OPER_ZONE_CODE <", value, "lineOperZoneCode");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneCodeLessThanOrEqualTo(String value) {
            addCriterion("LINE_OPER_ZONE_CODE <=", value, "lineOperZoneCode");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneCodeLike(String value) {
            addCriterion("LINE_OPER_ZONE_CODE like", value, "lineOperZoneCode");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneCodeNotLike(String value) {
            addCriterion("LINE_OPER_ZONE_CODE not like", value, "lineOperZoneCode");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneCodeIn(List<String> values) {
            addCriterion("LINE_OPER_ZONE_CODE in", values, "lineOperZoneCode");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneCodeNotIn(List<String> values) {
            addCriterion("LINE_OPER_ZONE_CODE not in", values, "lineOperZoneCode");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneCodeBetween(String value1, String value2) {
            addCriterion("LINE_OPER_ZONE_CODE between", value1, value2, "lineOperZoneCode");
            return (Criteria) this;
        }

        public Criteria andLineOperZoneCodeNotBetween(String value1, String value2) {
            addCriterion("LINE_OPER_ZONE_CODE not between", value1, value2, "lineOperZoneCode");
            return (Criteria) this;
        }

        public Criteria andIsCountryLineIsNull() {
            addCriterion("IS_COUNTRY_LINE is null");
            return (Criteria) this;
        }

        public Criteria andIsCountryLineIsNotNull() {
            addCriterion("IS_COUNTRY_LINE is not null");
            return (Criteria) this;
        }

        public Criteria andIsCountryLineEqualTo(String value) {
            addCriterion("IS_COUNTRY_LINE =", value, "isCountryLine");
            return (Criteria) this;
        }

        public Criteria andIsCountryLineNotEqualTo(String value) {
            addCriterion("IS_COUNTRY_LINE <>", value, "isCountryLine");
            return (Criteria) this;
        }

        public Criteria andIsCountryLineGreaterThan(String value) {
            addCriterion("IS_COUNTRY_LINE >", value, "isCountryLine");
            return (Criteria) this;
        }

        public Criteria andIsCountryLineGreaterThanOrEqualTo(String value) {
            addCriterion("IS_COUNTRY_LINE >=", value, "isCountryLine");
            return (Criteria) this;
        }

        public Criteria andIsCountryLineLessThan(String value) {
            addCriterion("IS_COUNTRY_LINE <", value, "isCountryLine");
            return (Criteria) this;
        }

        public Criteria andIsCountryLineLessThanOrEqualTo(String value) {
            addCriterion("IS_COUNTRY_LINE <=", value, "isCountryLine");
            return (Criteria) this;
        }

        public Criteria andIsCountryLineLike(String value) {
            addCriterion("IS_COUNTRY_LINE like", value, "isCountryLine");
            return (Criteria) this;
        }

        public Criteria andIsCountryLineNotLike(String value) {
            addCriterion("IS_COUNTRY_LINE not like", value, "isCountryLine");
            return (Criteria) this;
        }

        public Criteria andIsCountryLineIn(List<String> values) {
            addCriterion("IS_COUNTRY_LINE in", values, "isCountryLine");
            return (Criteria) this;
        }

        public Criteria andIsCountryLineNotIn(List<String> values) {
            addCriterion("IS_COUNTRY_LINE not in", values, "isCountryLine");
            return (Criteria) this;
        }

        public Criteria andIsCountryLineBetween(String value1, String value2) {
            addCriterion("IS_COUNTRY_LINE between", value1, value2, "isCountryLine");
            return (Criteria) this;
        }

        public Criteria andIsCountryLineNotBetween(String value1, String value2) {
            addCriterion("IS_COUNTRY_LINE not between", value1, value2, "isCountryLine");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusIsNull() {
            addCriterion("LINE_OP_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusIsNotNull() {
            addCriterion("LINE_OP_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusEqualTo(String value) {
            addCriterion("LINE_OP_STATUS =", value, "lineOpStatus");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusNotEqualTo(String value) {
            addCriterion("LINE_OP_STATUS <>", value, "lineOpStatus");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusGreaterThan(String value) {
            addCriterion("LINE_OP_STATUS >", value, "lineOpStatus");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusGreaterThanOrEqualTo(String value) {
            addCriterion("LINE_OP_STATUS >=", value, "lineOpStatus");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusLessThan(String value) {
            addCriterion("LINE_OP_STATUS <", value, "lineOpStatus");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusLessThanOrEqualTo(String value) {
            addCriterion("LINE_OP_STATUS <=", value, "lineOpStatus");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusLike(String value) {
            addCriterion("LINE_OP_STATUS like", value, "lineOpStatus");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusNotLike(String value) {
            addCriterion("LINE_OP_STATUS not like", value, "lineOpStatus");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusIn(List<String> values) {
            addCriterion("LINE_OP_STATUS in", values, "lineOpStatus");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusNotIn(List<String> values) {
            addCriterion("LINE_OP_STATUS not in", values, "lineOpStatus");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusBetween(String value1, String value2) {
            addCriterion("LINE_OP_STATUS between", value1, value2, "lineOpStatus");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusNotBetween(String value1, String value2) {
            addCriterion("LINE_OP_STATUS not between", value1, value2, "lineOpStatus");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusCodeIsNull() {
            addCriterion("LINE_OP_STATUS_CODE is null");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusCodeIsNotNull() {
            addCriterion("LINE_OP_STATUS_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusCodeEqualTo(String value) {
            addCriterion("LINE_OP_STATUS_CODE =", value, "lineOpStatusCode");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusCodeNotEqualTo(String value) {
            addCriterion("LINE_OP_STATUS_CODE <>", value, "lineOpStatusCode");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusCodeGreaterThan(String value) {
            addCriterion("LINE_OP_STATUS_CODE >", value, "lineOpStatusCode");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusCodeGreaterThanOrEqualTo(String value) {
            addCriterion("LINE_OP_STATUS_CODE >=", value, "lineOpStatusCode");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusCodeLessThan(String value) {
            addCriterion("LINE_OP_STATUS_CODE <", value, "lineOpStatusCode");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusCodeLessThanOrEqualTo(String value) {
            addCriterion("LINE_OP_STATUS_CODE <=", value, "lineOpStatusCode");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusCodeLike(String value) {
            addCriterion("LINE_OP_STATUS_CODE like", value, "lineOpStatusCode");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusCodeNotLike(String value) {
            addCriterion("LINE_OP_STATUS_CODE not like", value, "lineOpStatusCode");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusCodeIn(List<String> values) {
            addCriterion("LINE_OP_STATUS_CODE in", values, "lineOpStatusCode");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusCodeNotIn(List<String> values) {
            addCriterion("LINE_OP_STATUS_CODE not in", values, "lineOpStatusCode");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusCodeBetween(String value1, String value2) {
            addCriterion("LINE_OP_STATUS_CODE between", value1, value2, "lineOpStatusCode");
            return (Criteria) this;
        }

        public Criteria andLineOpStatusCodeNotBetween(String value1, String value2) {
            addCriterion("LINE_OP_STATUS_CODE not between", value1, value2, "lineOpStatusCode");
            return (Criteria) this;
        }

        public Criteria andLineValidDateIsNull() {
            addCriterion("LINE_VALID_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLineValidDateIsNotNull() {
            addCriterion("LINE_VALID_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLineValidDateEqualTo(Date value) {
            addCriterion("LINE_VALID_DATE =", value, "lineValidDate");
            return (Criteria) this;
        }

        public Criteria andLineValidDateNotEqualTo(Date value) {
            addCriterion("LINE_VALID_DATE <>", value, "lineValidDate");
            return (Criteria) this;
        }

        public Criteria andLineValidDateGreaterThan(Date value) {
            addCriterion("LINE_VALID_DATE >", value, "lineValidDate");
            return (Criteria) this;
        }

        public Criteria andLineValidDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LINE_VALID_DATE >=", value, "lineValidDate");
            return (Criteria) this;
        }

        public Criteria andLineValidDateLessThan(Date value) {
            addCriterion("LINE_VALID_DATE <", value, "lineValidDate");
            return (Criteria) this;
        }

        public Criteria andLineValidDateLessThanOrEqualTo(Date value) {
            addCriterion("LINE_VALID_DATE <=", value, "lineValidDate");
            return (Criteria) this;
        }

        public Criteria andLineValidDateIn(List<Date> values) {
            addCriterion("LINE_VALID_DATE in", values, "lineValidDate");
            return (Criteria) this;
        }

        public Criteria andLineValidDateNotIn(List<Date> values) {
            addCriterion("LINE_VALID_DATE not in", values, "lineValidDate");
            return (Criteria) this;
        }

        public Criteria andLineValidDateBetween(Date value1, Date value2) {
            addCriterion("LINE_VALID_DATE between", value1, value2, "lineValidDate");
            return (Criteria) this;
        }

        public Criteria andLineValidDateNotBetween(Date value1, Date value2) {
            addCriterion("LINE_VALID_DATE not between", value1, value2, "lineValidDate");
            return (Criteria) this;
        }

        public Criteria andLineExpireDateIsNull() {
            addCriterion("LINE_EXPIRE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLineExpireDateIsNotNull() {
            addCriterion("LINE_EXPIRE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLineExpireDateEqualTo(Date value) {
            addCriterion("LINE_EXPIRE_DATE =", value, "lineExpireDate");
            return (Criteria) this;
        }

        public Criteria andLineExpireDateNotEqualTo(Date value) {
            addCriterion("LINE_EXPIRE_DATE <>", value, "lineExpireDate");
            return (Criteria) this;
        }

        public Criteria andLineExpireDateGreaterThan(Date value) {
            addCriterion("LINE_EXPIRE_DATE >", value, "lineExpireDate");
            return (Criteria) this;
        }

        public Criteria andLineExpireDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LINE_EXPIRE_DATE >=", value, "lineExpireDate");
            return (Criteria) this;
        }

        public Criteria andLineExpireDateLessThan(Date value) {
            addCriterion("LINE_EXPIRE_DATE <", value, "lineExpireDate");
            return (Criteria) this;
        }

        public Criteria andLineExpireDateLessThanOrEqualTo(Date value) {
            addCriterion("LINE_EXPIRE_DATE <=", value, "lineExpireDate");
            return (Criteria) this;
        }

        public Criteria andLineExpireDateIn(List<Date> values) {
            addCriterion("LINE_EXPIRE_DATE in", values, "lineExpireDate");
            return (Criteria) this;
        }

        public Criteria andLineExpireDateNotIn(List<Date> values) {
            addCriterion("LINE_EXPIRE_DATE not in", values, "lineExpireDate");
            return (Criteria) this;
        }

        public Criteria andLineExpireDateBetween(Date value1, Date value2) {
            addCriterion("LINE_EXPIRE_DATE between", value1, value2, "lineExpireDate");
            return (Criteria) this;
        }

        public Criteria andLineExpireDateNotBetween(Date value1, Date value2) {
            addCriterion("LINE_EXPIRE_DATE not between", value1, value2, "lineExpireDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateIsNull() {
            addCriterion("ISSUE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andIssueDateIsNotNull() {
            addCriterion("ISSUE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andIssueDateEqualTo(Date value) {
            addCriterion("ISSUE_DATE =", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateNotEqualTo(Date value) {
            addCriterion("ISSUE_DATE <>", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateGreaterThan(Date value) {
            addCriterion("ISSUE_DATE >", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateGreaterThanOrEqualTo(Date value) {
            addCriterion("ISSUE_DATE >=", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateLessThan(Date value) {
            addCriterion("ISSUE_DATE <", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateLessThanOrEqualTo(Date value) {
            addCriterion("ISSUE_DATE <=", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateIn(List<Date> values) {
            addCriterion("ISSUE_DATE in", values, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateNotIn(List<Date> values) {
            addCriterion("ISSUE_DATE not in", values, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateBetween(Date value1, Date value2) {
            addCriterion("ISSUE_DATE between", value1, value2, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateNotBetween(Date value1, Date value2) {
            addCriterion("ISSUE_DATE not between", value1, value2, "issueDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 24 08:19:14 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
