package cn.cttic.roadtransapi.orm.roadway.domain;

import cn.cttic.roadtransapi.common.UnionPrimaryKeyAttr;

public class RtBfB0101 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.PLATE_COLOR
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String plateColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.PLATECOLORCODE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String platecolorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.BRAND
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.MODEL
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.ENGINE_NO
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String engineNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.VIN
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String vin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.VEHICLE_TYPE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String vehicleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.VEHICLE_TYPE_CODE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String vehicleTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.VEHICLE_TYPE_LEVEL
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String vehicleTypeLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.OUT_FACTORY_DATE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private Integer outFactoryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.FUEL_TYPE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String fuelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.WHEEL_BASE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String wheelBase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.VEHICLE_LENGTH
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String vehicleLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.VEHICLE_HIGH
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String vehicleHigh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.VEHICLE_WIDTH
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String vehicleWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.AXLES_AMOUNT
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String axlesAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.TRACTION_TONNAGE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String tractionTonnage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.ENGINE_POWER
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String enginePower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.APPROVE_SEAT
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String approveSeat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.APPROVE_TON
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String approveTon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.GPS_TERMINAL_MODEL
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String gpsTerminalModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.BUSINESS_STATE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String businessState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.BUSINESS_STATE_CODE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String businessStateCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.CITY_CODE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private Integer cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.YELLOW_CAR_FLAG
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String yellowCarFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.SATELLITE_PLATFORM_NAME
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String satellitePlatformName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.SATELLITE_PLATFORM_CODE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String satellitePlatformCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.PROVINCE_CODE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    @UnionPrimaryKeyAttr
    private Integer provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.OWNER_ID
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String ownerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.MCU_ID
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    @UnionPrimaryKeyAttr
    private String mcuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.VEHICLE_NO
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String vehicleNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.OPER_TIME
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private String operTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0101.PHOTO
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    private byte[] photo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.PLATE_COLOR
     *
     * @return the value of RT_BF_B0101.PLATE_COLOR
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getPlateColor() {
        return plateColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.PLATE_COLOR
     *
     * @param plateColor the value for RT_BF_B0101.PLATE_COLOR
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setPlateColor(String plateColor) {
        this.plateColor = plateColor == null ? null : plateColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.PLATECOLORCODE
     *
     * @return the value of RT_BF_B0101.PLATECOLORCODE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getPlatecolorcode() {
        return platecolorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.PLATECOLORCODE
     *
     * @param platecolorcode the value for RT_BF_B0101.PLATECOLORCODE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setPlatecolorcode(String platecolorcode) {
        this.platecolorcode = platecolorcode == null ? null : platecolorcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.BRAND
     *
     * @return the value of RT_BF_B0101.BRAND
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.BRAND
     *
     * @param brand the value for RT_BF_B0101.BRAND
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.MODEL
     *
     * @return the value of RT_BF_B0101.MODEL
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.MODEL
     *
     * @param model the value for RT_BF_B0101.MODEL
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.ENGINE_NO
     *
     * @return the value of RT_BF_B0101.ENGINE_NO
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getEngineNo() {
        return engineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.ENGINE_NO
     *
     * @param engineNo the value for RT_BF_B0101.ENGINE_NO
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setEngineNo(String engineNo) {
        this.engineNo = engineNo == null ? null : engineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.VIN
     *
     * @return the value of RT_BF_B0101.VIN
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getVin() {
        return vin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.VIN
     *
     * @param vin the value for RT_BF_B0101.VIN
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setVin(String vin) {
        this.vin = vin == null ? null : vin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.VEHICLE_TYPE
     *
     * @return the value of RT_BF_B0101.VEHICLE_TYPE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getVehicleType() {
        return vehicleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.VEHICLE_TYPE
     *
     * @param vehicleType the value for RT_BF_B0101.VEHICLE_TYPE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setVehicleType(String vehicleType) {
        this.vehicleType = vehicleType == null ? null : vehicleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.VEHICLE_TYPE_CODE
     *
     * @return the value of RT_BF_B0101.VEHICLE_TYPE_CODE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getVehicleTypeCode() {
        return vehicleTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.VEHICLE_TYPE_CODE
     *
     * @param vehicleTypeCode the value for RT_BF_B0101.VEHICLE_TYPE_CODE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setVehicleTypeCode(String vehicleTypeCode) {
        this.vehicleTypeCode = vehicleTypeCode == null ? null : vehicleTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.VEHICLE_TYPE_LEVEL
     *
     * @return the value of RT_BF_B0101.VEHICLE_TYPE_LEVEL
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getVehicleTypeLevel() {
        return vehicleTypeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.VEHICLE_TYPE_LEVEL
     *
     * @param vehicleTypeLevel the value for RT_BF_B0101.VEHICLE_TYPE_LEVEL
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setVehicleTypeLevel(String vehicleTypeLevel) {
        this.vehicleTypeLevel = vehicleTypeLevel == null ? null : vehicleTypeLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.OUT_FACTORY_DATE
     *
     * @return the value of RT_BF_B0101.OUT_FACTORY_DATE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public Integer getOutFactoryDate() {
        return outFactoryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.OUT_FACTORY_DATE
     *
     * @param outFactoryDate the value for RT_BF_B0101.OUT_FACTORY_DATE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setOutFactoryDate(Integer outFactoryDate) {
        this.outFactoryDate = outFactoryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.FUEL_TYPE
     *
     * @return the value of RT_BF_B0101.FUEL_TYPE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getFuelType() {
        return fuelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.FUEL_TYPE
     *
     * @param fuelType the value for RT_BF_B0101.FUEL_TYPE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setFuelType(String fuelType) {
        this.fuelType = fuelType == null ? null : fuelType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.WHEEL_BASE
     *
     * @return the value of RT_BF_B0101.WHEEL_BASE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getWheelBase() {
        return wheelBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.WHEEL_BASE
     *
     * @param wheelBase the value for RT_BF_B0101.WHEEL_BASE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setWheelBase(String wheelBase) {
        this.wheelBase = wheelBase == null ? null : wheelBase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.VEHICLE_LENGTH
     *
     * @return the value of RT_BF_B0101.VEHICLE_LENGTH
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getVehicleLength() {
        return vehicleLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.VEHICLE_LENGTH
     *
     * @param vehicleLength the value for RT_BF_B0101.VEHICLE_LENGTH
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setVehicleLength(String vehicleLength) {
        this.vehicleLength = vehicleLength == null ? null : vehicleLength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.VEHICLE_HIGH
     *
     * @return the value of RT_BF_B0101.VEHICLE_HIGH
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getVehicleHigh() {
        return vehicleHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.VEHICLE_HIGH
     *
     * @param vehicleHigh the value for RT_BF_B0101.VEHICLE_HIGH
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setVehicleHigh(String vehicleHigh) {
        this.vehicleHigh = vehicleHigh == null ? null : vehicleHigh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.VEHICLE_WIDTH
     *
     * @return the value of RT_BF_B0101.VEHICLE_WIDTH
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getVehicleWidth() {
        return vehicleWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.VEHICLE_WIDTH
     *
     * @param vehicleWidth the value for RT_BF_B0101.VEHICLE_WIDTH
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setVehicleWidth(String vehicleWidth) {
        this.vehicleWidth = vehicleWidth == null ? null : vehicleWidth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.AXLES_AMOUNT
     *
     * @return the value of RT_BF_B0101.AXLES_AMOUNT
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getAxlesAmount() {
        return axlesAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.AXLES_AMOUNT
     *
     * @param axlesAmount the value for RT_BF_B0101.AXLES_AMOUNT
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setAxlesAmount(String axlesAmount) {
        this.axlesAmount = axlesAmount == null ? null : axlesAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.TRACTION_TONNAGE
     *
     * @return the value of RT_BF_B0101.TRACTION_TONNAGE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getTractionTonnage() {
        return tractionTonnage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.TRACTION_TONNAGE
     *
     * @param tractionTonnage the value for RT_BF_B0101.TRACTION_TONNAGE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setTractionTonnage(String tractionTonnage) {
        this.tractionTonnage = tractionTonnage == null ? null : tractionTonnage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.ENGINE_POWER
     *
     * @return the value of RT_BF_B0101.ENGINE_POWER
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getEnginePower() {
        return enginePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.ENGINE_POWER
     *
     * @param enginePower the value for RT_BF_B0101.ENGINE_POWER
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setEnginePower(String enginePower) {
        this.enginePower = enginePower == null ? null : enginePower.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.APPROVE_SEAT
     *
     * @return the value of RT_BF_B0101.APPROVE_SEAT
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getApproveSeat() {
        return approveSeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.APPROVE_SEAT
     *
     * @param approveSeat the value for RT_BF_B0101.APPROVE_SEAT
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setApproveSeat(String approveSeat) {
        this.approveSeat = approveSeat == null ? null : approveSeat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.APPROVE_TON
     *
     * @return the value of RT_BF_B0101.APPROVE_TON
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getApproveTon() {
        return approveTon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.APPROVE_TON
     *
     * @param approveTon the value for RT_BF_B0101.APPROVE_TON
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setApproveTon(String approveTon) {
        this.approveTon = approveTon == null ? null : approveTon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.GPS_TERMINAL_MODEL
     *
     * @return the value of RT_BF_B0101.GPS_TERMINAL_MODEL
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getGpsTerminalModel() {
        return gpsTerminalModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.GPS_TERMINAL_MODEL
     *
     * @param gpsTerminalModel the value for RT_BF_B0101.GPS_TERMINAL_MODEL
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setGpsTerminalModel(String gpsTerminalModel) {
        this.gpsTerminalModel = gpsTerminalModel == null ? null : gpsTerminalModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.BUSINESS_STATE
     *
     * @return the value of RT_BF_B0101.BUSINESS_STATE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getBusinessState() {
        return businessState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.BUSINESS_STATE
     *
     * @param businessState the value for RT_BF_B0101.BUSINESS_STATE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setBusinessState(String businessState) {
        this.businessState = businessState == null ? null : businessState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.BUSINESS_STATE_CODE
     *
     * @return the value of RT_BF_B0101.BUSINESS_STATE_CODE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getBusinessStateCode() {
        return businessStateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.BUSINESS_STATE_CODE
     *
     * @param businessStateCode the value for RT_BF_B0101.BUSINESS_STATE_CODE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setBusinessStateCode(String businessStateCode) {
        this.businessStateCode = businessStateCode == null ? null : businessStateCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.CITY_CODE
     *
     * @return the value of RT_BF_B0101.CITY_CODE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public Integer getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.CITY_CODE
     *
     * @param cityCode the value for RT_BF_B0101.CITY_CODE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setCityCode(Integer cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.YELLOW_CAR_FLAG
     *
     * @return the value of RT_BF_B0101.YELLOW_CAR_FLAG
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getYellowCarFlag() {
        return yellowCarFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.YELLOW_CAR_FLAG
     *
     * @param yellowCarFlag the value for RT_BF_B0101.YELLOW_CAR_FLAG
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setYellowCarFlag(String yellowCarFlag) {
        this.yellowCarFlag = yellowCarFlag == null ? null : yellowCarFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.SATELLITE_PLATFORM_NAME
     *
     * @return the value of RT_BF_B0101.SATELLITE_PLATFORM_NAME
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getSatellitePlatformName() {
        return satellitePlatformName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.SATELLITE_PLATFORM_NAME
     *
     * @param satellitePlatformName the value for RT_BF_B0101.SATELLITE_PLATFORM_NAME
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setSatellitePlatformName(String satellitePlatformName) {
        this.satellitePlatformName = satellitePlatformName == null ? null : satellitePlatformName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.SATELLITE_PLATFORM_CODE
     *
     * @return the value of RT_BF_B0101.SATELLITE_PLATFORM_CODE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getSatellitePlatformCode() {
        return satellitePlatformCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.SATELLITE_PLATFORM_CODE
     *
     * @param satellitePlatformCode the value for RT_BF_B0101.SATELLITE_PLATFORM_CODE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setSatellitePlatformCode(String satellitePlatformCode) {
        this.satellitePlatformCode = satellitePlatformCode == null ? null : satellitePlatformCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.PROVINCE_CODE
     *
     * @return the value of RT_BF_B0101.PROVINCE_CODE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public Integer getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.PROVINCE_CODE
     *
     * @param provinceCode the value for RT_BF_B0101.PROVINCE_CODE
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setProvinceCode(Integer provinceCode) {
        this.provinceCode = provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.OWNER_ID
     *
     * @return the value of RT_BF_B0101.OWNER_ID
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.OWNER_ID
     *
     * @param ownerId the value for RT_BF_B0101.OWNER_ID
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId == null ? null : ownerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.MCU_ID
     *
     * @return the value of RT_BF_B0101.MCU_ID
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getMcuId() {
        return mcuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.MCU_ID
     *
     * @param mcuId the value for RT_BF_B0101.MCU_ID
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setMcuId(String mcuId) {
        this.mcuId = mcuId == null ? null : mcuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.VEHICLE_NO
     *
     * @return the value of RT_BF_B0101.VEHICLE_NO
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getVehicleNo() {
        return vehicleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.VEHICLE_NO
     *
     * @param vehicleNo the value for RT_BF_B0101.VEHICLE_NO
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setVehicleNo(String vehicleNo) {
        this.vehicleNo = vehicleNo == null ? null : vehicleNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.OPER_TIME
     *
     * @return the value of RT_BF_B0101.OPER_TIME
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public String getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.OPER_TIME
     *
     * @param operTime the value for RT_BF_B0101.OPER_TIME
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setOperTime(String operTime) {
        this.operTime = operTime == null ? null : operTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0101.PHOTO
     *
     * @return the value of RT_BF_B0101.PHOTO
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public byte[] getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0101.PHOTO
     *
     * @param photo the value for RT_BF_B0101.PHOTO
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
}