package cn.cttic.roadtransapi.orm.roadway.domain;

import java.util.Date;

public class RtBfA0104 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_A0104.PROVINCE_CODE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private Integer provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_A0104.OWNER_ID
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String ownerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_A0104.OWNER_NAME
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String ownerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_A0104.OWNER_ADDRESS
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String ownerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_A0104.CHECK_DATE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private Date checkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_A0104.CHECK_YEAR
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String checkYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_A0104.CHECK_ORA_NAME
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String checkOraName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_A0104.CHECK_MARK
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String checkMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_A0104.CHECK_RESULT
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String checkResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_A0104.PROVINCE_CODE
     *
     * @return the value of RT_BF_A0104.PROVINCE_CODE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public Integer getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_A0104.PROVINCE_CODE
     *
     * @param provinceCode the value for RT_BF_A0104.PROVINCE_CODE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setProvinceCode(Integer provinceCode) {
        this.provinceCode = provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_A0104.OWNER_ID
     *
     * @return the value of RT_BF_A0104.OWNER_ID
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_A0104.OWNER_ID
     *
     * @param ownerId the value for RT_BF_A0104.OWNER_ID
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId == null ? null : ownerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_A0104.OWNER_NAME
     *
     * @return the value of RT_BF_A0104.OWNER_NAME
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_A0104.OWNER_NAME
     *
     * @param ownerName the value for RT_BF_A0104.OWNER_NAME
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName == null ? null : ownerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_A0104.OWNER_ADDRESS
     *
     * @return the value of RT_BF_A0104.OWNER_ADDRESS
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getOwnerAddress() {
        return ownerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_A0104.OWNER_ADDRESS
     *
     * @param ownerAddress the value for RT_BF_A0104.OWNER_ADDRESS
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setOwnerAddress(String ownerAddress) {
        this.ownerAddress = ownerAddress == null ? null : ownerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_A0104.CHECK_DATE
     *
     * @return the value of RT_BF_A0104.CHECK_DATE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public Date getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_A0104.CHECK_DATE
     *
     * @param checkDate the value for RT_BF_A0104.CHECK_DATE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_A0104.CHECK_YEAR
     *
     * @return the value of RT_BF_A0104.CHECK_YEAR
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getCheckYear() {
        return checkYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_A0104.CHECK_YEAR
     *
     * @param checkYear the value for RT_BF_A0104.CHECK_YEAR
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setCheckYear(String checkYear) {
        this.checkYear = checkYear == null ? null : checkYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_A0104.CHECK_ORA_NAME
     *
     * @return the value of RT_BF_A0104.CHECK_ORA_NAME
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getCheckOraName() {
        return checkOraName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_A0104.CHECK_ORA_NAME
     *
     * @param checkOraName the value for RT_BF_A0104.CHECK_ORA_NAME
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setCheckOraName(String checkOraName) {
        this.checkOraName = checkOraName == null ? null : checkOraName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_A0104.CHECK_MARK
     *
     * @return the value of RT_BF_A0104.CHECK_MARK
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getCheckMark() {
        return checkMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_A0104.CHECK_MARK
     *
     * @param checkMark the value for RT_BF_A0104.CHECK_MARK
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setCheckMark(String checkMark) {
        this.checkMark = checkMark == null ? null : checkMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_A0104.CHECK_RESULT
     *
     * @return the value of RT_BF_A0104.CHECK_RESULT
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getCheckResult() {
        return checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_A0104.CHECK_RESULT
     *
     * @param checkResult the value for RT_BF_A0104.CHECK_RESULT
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setCheckResult(String checkResult) {
        this.checkResult = checkResult == null ? null : checkResult.trim();
    }
}