package cn.cttic.roadtransapi.orm.roadway.domain;

import java.util.Date;

public class RtBfB0106 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0106.PROVINCE_CODE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private Integer provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0106.MCU_ID
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String mcuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0106.VEHICLE_NO
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String vehicleNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0106.PLATE_COLOR
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String plateColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0106.PLATE_COLOR_CODE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String plateColorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0106.CUR_MAINTAIN_DATE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private Date curMaintainDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0106.CUR_MAINTAIN_MILEAGE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private Long curMaintainMileage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0106.MAINTAIN_UNIT_NAME
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String maintainUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0106.MAINTAIN_CONTRACT
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String maintainContract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0106.MAINTAIN_INVOICE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String maintainInvoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0106.MAINTAIN_CERT_NO
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String maintainCertNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0106.MAINTAIN_RESULT
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String maintainResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0106.MAINTAIN_UNIT
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String maintainUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0106.CHECK_STATION
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String checkStation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0106.CHECK_DATE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private Date checkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0106.CHECK_TIMES
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private Integer checkTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0106.CHECK_RESULT
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String checkResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_B0106.PROCESS_DATE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private Date processDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0106.PROVINCE_CODE
     *
     * @return the value of RT_BF_B0106.PROVINCE_CODE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public Integer getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0106.PROVINCE_CODE
     *
     * @param provinceCode the value for RT_BF_B0106.PROVINCE_CODE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setProvinceCode(Integer provinceCode) {
        this.provinceCode = provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0106.MCU_ID
     *
     * @return the value of RT_BF_B0106.MCU_ID
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getMcuId() {
        return mcuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0106.MCU_ID
     *
     * @param mcuId the value for RT_BF_B0106.MCU_ID
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setMcuId(String mcuId) {
        this.mcuId = mcuId == null ? null : mcuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0106.VEHICLE_NO
     *
     * @return the value of RT_BF_B0106.VEHICLE_NO
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getVehicleNo() {
        return vehicleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0106.VEHICLE_NO
     *
     * @param vehicleNo the value for RT_BF_B0106.VEHICLE_NO
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setVehicleNo(String vehicleNo) {
        this.vehicleNo = vehicleNo == null ? null : vehicleNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0106.PLATE_COLOR
     *
     * @return the value of RT_BF_B0106.PLATE_COLOR
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getPlateColor() {
        return plateColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0106.PLATE_COLOR
     *
     * @param plateColor the value for RT_BF_B0106.PLATE_COLOR
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setPlateColor(String plateColor) {
        this.plateColor = plateColor == null ? null : plateColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0106.PLATE_COLOR_CODE
     *
     * @return the value of RT_BF_B0106.PLATE_COLOR_CODE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getPlateColorCode() {
        return plateColorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0106.PLATE_COLOR_CODE
     *
     * @param plateColorCode the value for RT_BF_B0106.PLATE_COLOR_CODE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setPlateColorCode(String plateColorCode) {
        this.plateColorCode = plateColorCode == null ? null : plateColorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0106.CUR_MAINTAIN_DATE
     *
     * @return the value of RT_BF_B0106.CUR_MAINTAIN_DATE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public Date getCurMaintainDate() {
        return curMaintainDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0106.CUR_MAINTAIN_DATE
     *
     * @param curMaintainDate the value for RT_BF_B0106.CUR_MAINTAIN_DATE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setCurMaintainDate(Date curMaintainDate) {
        this.curMaintainDate = curMaintainDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0106.CUR_MAINTAIN_MILEAGE
     *
     * @return the value of RT_BF_B0106.CUR_MAINTAIN_MILEAGE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public Long getCurMaintainMileage() {
        return curMaintainMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0106.CUR_MAINTAIN_MILEAGE
     *
     * @param curMaintainMileage the value for RT_BF_B0106.CUR_MAINTAIN_MILEAGE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setCurMaintainMileage(Long curMaintainMileage) {
        this.curMaintainMileage = curMaintainMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0106.MAINTAIN_UNIT_NAME
     *
     * @return the value of RT_BF_B0106.MAINTAIN_UNIT_NAME
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getMaintainUnitName() {
        return maintainUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0106.MAINTAIN_UNIT_NAME
     *
     * @param maintainUnitName the value for RT_BF_B0106.MAINTAIN_UNIT_NAME
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setMaintainUnitName(String maintainUnitName) {
        this.maintainUnitName = maintainUnitName == null ? null : maintainUnitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0106.MAINTAIN_CONTRACT
     *
     * @return the value of RT_BF_B0106.MAINTAIN_CONTRACT
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getMaintainContract() {
        return maintainContract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0106.MAINTAIN_CONTRACT
     *
     * @param maintainContract the value for RT_BF_B0106.MAINTAIN_CONTRACT
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setMaintainContract(String maintainContract) {
        this.maintainContract = maintainContract == null ? null : maintainContract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0106.MAINTAIN_INVOICE
     *
     * @return the value of RT_BF_B0106.MAINTAIN_INVOICE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getMaintainInvoice() {
        return maintainInvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0106.MAINTAIN_INVOICE
     *
     * @param maintainInvoice the value for RT_BF_B0106.MAINTAIN_INVOICE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setMaintainInvoice(String maintainInvoice) {
        this.maintainInvoice = maintainInvoice == null ? null : maintainInvoice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0106.MAINTAIN_CERT_NO
     *
     * @return the value of RT_BF_B0106.MAINTAIN_CERT_NO
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getMaintainCertNo() {
        return maintainCertNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0106.MAINTAIN_CERT_NO
     *
     * @param maintainCertNo the value for RT_BF_B0106.MAINTAIN_CERT_NO
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setMaintainCertNo(String maintainCertNo) {
        this.maintainCertNo = maintainCertNo == null ? null : maintainCertNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0106.MAINTAIN_RESULT
     *
     * @return the value of RT_BF_B0106.MAINTAIN_RESULT
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getMaintainResult() {
        return maintainResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0106.MAINTAIN_RESULT
     *
     * @param maintainResult the value for RT_BF_B0106.MAINTAIN_RESULT
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setMaintainResult(String maintainResult) {
        this.maintainResult = maintainResult == null ? null : maintainResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0106.MAINTAIN_UNIT
     *
     * @return the value of RT_BF_B0106.MAINTAIN_UNIT
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getMaintainUnit() {
        return maintainUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0106.MAINTAIN_UNIT
     *
     * @param maintainUnit the value for RT_BF_B0106.MAINTAIN_UNIT
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setMaintainUnit(String maintainUnit) {
        this.maintainUnit = maintainUnit == null ? null : maintainUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0106.CHECK_STATION
     *
     * @return the value of RT_BF_B0106.CHECK_STATION
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getCheckStation() {
        return checkStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0106.CHECK_STATION
     *
     * @param checkStation the value for RT_BF_B0106.CHECK_STATION
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setCheckStation(String checkStation) {
        this.checkStation = checkStation == null ? null : checkStation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0106.CHECK_DATE
     *
     * @return the value of RT_BF_B0106.CHECK_DATE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public Date getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0106.CHECK_DATE
     *
     * @param checkDate the value for RT_BF_B0106.CHECK_DATE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0106.CHECK_TIMES
     *
     * @return the value of RT_BF_B0106.CHECK_TIMES
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public Integer getCheckTimes() {
        return checkTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0106.CHECK_TIMES
     *
     * @param checkTimes the value for RT_BF_B0106.CHECK_TIMES
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setCheckTimes(Integer checkTimes) {
        this.checkTimes = checkTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0106.CHECK_RESULT
     *
     * @return the value of RT_BF_B0106.CHECK_RESULT
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getCheckResult() {
        return checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0106.CHECK_RESULT
     *
     * @param checkResult the value for RT_BF_B0106.CHECK_RESULT
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setCheckResult(String checkResult) {
        this.checkResult = checkResult == null ? null : checkResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_B0106.PROCESS_DATE
     *
     * @return the value of RT_BF_B0106.PROCESS_DATE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public Date getProcessDate() {
        return processDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_B0106.PROCESS_DATE
     *
     * @param processDate the value for RT_BF_B0106.PROCESS_DATE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setProcessDate(Date processDate) {
        this.processDate = processDate;
    }
}