package cn.cttic.roadtransapi.orm.roadway.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RtBfB0104Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RT_BF_B0104
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RT_BF_B0104
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RT_BF_B0104
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0104
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public RtBfB0104Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0104
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0104
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0104
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0104
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0104
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0104
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0104
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0104
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0104
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0104
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RT_BF_B0104
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProvinceCodeIsNull() {
            addCriterion("PROVINCE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeIsNotNull() {
            addCriterion("PROVINCE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeEqualTo(Integer value) {
            addCriterion("PROVINCE_CODE =", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeNotEqualTo(Integer value) {
            addCriterion("PROVINCE_CODE <>", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeGreaterThan(Integer value) {
            addCriterion("PROVINCE_CODE >", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("PROVINCE_CODE >=", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeLessThan(Integer value) {
            addCriterion("PROVINCE_CODE <", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeLessThanOrEqualTo(Integer value) {
            addCriterion("PROVINCE_CODE <=", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeIn(List<Integer> values) {
            addCriterion("PROVINCE_CODE in", values, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeNotIn(List<Integer> values) {
            addCriterion("PROVINCE_CODE not in", values, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeBetween(Integer value1, Integer value2) {
            addCriterion("PROVINCE_CODE between", value1, value2, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("PROVINCE_CODE not between", value1, value2, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andMcuIdIsNull() {
            addCriterion("MCU_ID is null");
            return (Criteria) this;
        }

        public Criteria andMcuIdIsNotNull() {
            addCriterion("MCU_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMcuIdEqualTo(String value) {
            addCriterion("MCU_ID =", value, "mcuId");
            return (Criteria) this;
        }

        public Criteria andMcuIdNotEqualTo(String value) {
            addCriterion("MCU_ID <>", value, "mcuId");
            return (Criteria) this;
        }

        public Criteria andMcuIdGreaterThan(String value) {
            addCriterion("MCU_ID >", value, "mcuId");
            return (Criteria) this;
        }

        public Criteria andMcuIdGreaterThanOrEqualTo(String value) {
            addCriterion("MCU_ID >=", value, "mcuId");
            return (Criteria) this;
        }

        public Criteria andMcuIdLessThan(String value) {
            addCriterion("MCU_ID <", value, "mcuId");
            return (Criteria) this;
        }

        public Criteria andMcuIdLessThanOrEqualTo(String value) {
            addCriterion("MCU_ID <=", value, "mcuId");
            return (Criteria) this;
        }

        public Criteria andMcuIdLike(String value) {
            addCriterion("MCU_ID like", value, "mcuId");
            return (Criteria) this;
        }

        public Criteria andMcuIdNotLike(String value) {
            addCriterion("MCU_ID not like", value, "mcuId");
            return (Criteria) this;
        }

        public Criteria andMcuIdIn(List<String> values) {
            addCriterion("MCU_ID in", values, "mcuId");
            return (Criteria) this;
        }

        public Criteria andMcuIdNotIn(List<String> values) {
            addCriterion("MCU_ID not in", values, "mcuId");
            return (Criteria) this;
        }

        public Criteria andMcuIdBetween(String value1, String value2) {
            addCriterion("MCU_ID between", value1, value2, "mcuId");
            return (Criteria) this;
        }

        public Criteria andMcuIdNotBetween(String value1, String value2) {
            addCriterion("MCU_ID not between", value1, value2, "mcuId");
            return (Criteria) this;
        }

        public Criteria andVehicleNoIsNull() {
            addCriterion("VEHICLE_NO is null");
            return (Criteria) this;
        }

        public Criteria andVehicleNoIsNotNull() {
            addCriterion("VEHICLE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andVehicleNoEqualTo(String value) {
            addCriterion("VEHICLE_NO =", value, "vehicleNo");
            return (Criteria) this;
        }

        public Criteria andVehicleNoNotEqualTo(String value) {
            addCriterion("VEHICLE_NO <>", value, "vehicleNo");
            return (Criteria) this;
        }

        public Criteria andVehicleNoGreaterThan(String value) {
            addCriterion("VEHICLE_NO >", value, "vehicleNo");
            return (Criteria) this;
        }

        public Criteria andVehicleNoGreaterThanOrEqualTo(String value) {
            addCriterion("VEHICLE_NO >=", value, "vehicleNo");
            return (Criteria) this;
        }

        public Criteria andVehicleNoLessThan(String value) {
            addCriterion("VEHICLE_NO <", value, "vehicleNo");
            return (Criteria) this;
        }

        public Criteria andVehicleNoLessThanOrEqualTo(String value) {
            addCriterion("VEHICLE_NO <=", value, "vehicleNo");
            return (Criteria) this;
        }

        public Criteria andVehicleNoLike(String value) {
            addCriterion("VEHICLE_NO like", value, "vehicleNo");
            return (Criteria) this;
        }

        public Criteria andVehicleNoNotLike(String value) {
            addCriterion("VEHICLE_NO not like", value, "vehicleNo");
            return (Criteria) this;
        }

        public Criteria andVehicleNoIn(List<String> values) {
            addCriterion("VEHICLE_NO in", values, "vehicleNo");
            return (Criteria) this;
        }

        public Criteria andVehicleNoNotIn(List<String> values) {
            addCriterion("VEHICLE_NO not in", values, "vehicleNo");
            return (Criteria) this;
        }

        public Criteria andVehicleNoBetween(String value1, String value2) {
            addCriterion("VEHICLE_NO between", value1, value2, "vehicleNo");
            return (Criteria) this;
        }

        public Criteria andVehicleNoNotBetween(String value1, String value2) {
            addCriterion("VEHICLE_NO not between", value1, value2, "vehicleNo");
            return (Criteria) this;
        }

        public Criteria andPlateColorIsNull() {
            addCriterion("PLATE_COLOR is null");
            return (Criteria) this;
        }

        public Criteria andPlateColorIsNotNull() {
            addCriterion("PLATE_COLOR is not null");
            return (Criteria) this;
        }

        public Criteria andPlateColorEqualTo(String value) {
            addCriterion("PLATE_COLOR =", value, "plateColor");
            return (Criteria) this;
        }

        public Criteria andPlateColorNotEqualTo(String value) {
            addCriterion("PLATE_COLOR <>", value, "plateColor");
            return (Criteria) this;
        }

        public Criteria andPlateColorGreaterThan(String value) {
            addCriterion("PLATE_COLOR >", value, "plateColor");
            return (Criteria) this;
        }

        public Criteria andPlateColorGreaterThanOrEqualTo(String value) {
            addCriterion("PLATE_COLOR >=", value, "plateColor");
            return (Criteria) this;
        }

        public Criteria andPlateColorLessThan(String value) {
            addCriterion("PLATE_COLOR <", value, "plateColor");
            return (Criteria) this;
        }

        public Criteria andPlateColorLessThanOrEqualTo(String value) {
            addCriterion("PLATE_COLOR <=", value, "plateColor");
            return (Criteria) this;
        }

        public Criteria andPlateColorLike(String value) {
            addCriterion("PLATE_COLOR like", value, "plateColor");
            return (Criteria) this;
        }

        public Criteria andPlateColorNotLike(String value) {
            addCriterion("PLATE_COLOR not like", value, "plateColor");
            return (Criteria) this;
        }

        public Criteria andPlateColorIn(List<String> values) {
            addCriterion("PLATE_COLOR in", values, "plateColor");
            return (Criteria) this;
        }

        public Criteria andPlateColorNotIn(List<String> values) {
            addCriterion("PLATE_COLOR not in", values, "plateColor");
            return (Criteria) this;
        }

        public Criteria andPlateColorBetween(String value1, String value2) {
            addCriterion("PLATE_COLOR between", value1, value2, "plateColor");
            return (Criteria) this;
        }

        public Criteria andPlateColorNotBetween(String value1, String value2) {
            addCriterion("PLATE_COLOR not between", value1, value2, "plateColor");
            return (Criteria) this;
        }

        public Criteria andPlateColorCodeIsNull() {
            addCriterion("PLATE_COLOR_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPlateColorCodeIsNotNull() {
            addCriterion("PLATE_COLOR_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPlateColorCodeEqualTo(String value) {
            addCriterion("PLATE_COLOR_CODE =", value, "plateColorCode");
            return (Criteria) this;
        }

        public Criteria andPlateColorCodeNotEqualTo(String value) {
            addCriterion("PLATE_COLOR_CODE <>", value, "plateColorCode");
            return (Criteria) this;
        }

        public Criteria andPlateColorCodeGreaterThan(String value) {
            addCriterion("PLATE_COLOR_CODE >", value, "plateColorCode");
            return (Criteria) this;
        }

        public Criteria andPlateColorCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PLATE_COLOR_CODE >=", value, "plateColorCode");
            return (Criteria) this;
        }

        public Criteria andPlateColorCodeLessThan(String value) {
            addCriterion("PLATE_COLOR_CODE <", value, "plateColorCode");
            return (Criteria) this;
        }

        public Criteria andPlateColorCodeLessThanOrEqualTo(String value) {
            addCriterion("PLATE_COLOR_CODE <=", value, "plateColorCode");
            return (Criteria) this;
        }

        public Criteria andPlateColorCodeLike(String value) {
            addCriterion("PLATE_COLOR_CODE like", value, "plateColorCode");
            return (Criteria) this;
        }

        public Criteria andPlateColorCodeNotLike(String value) {
            addCriterion("PLATE_COLOR_CODE not like", value, "plateColorCode");
            return (Criteria) this;
        }

        public Criteria andPlateColorCodeIn(List<String> values) {
            addCriterion("PLATE_COLOR_CODE in", values, "plateColorCode");
            return (Criteria) this;
        }

        public Criteria andPlateColorCodeNotIn(List<String> values) {
            addCriterion("PLATE_COLOR_CODE not in", values, "plateColorCode");
            return (Criteria) this;
        }

        public Criteria andPlateColorCodeBetween(String value1, String value2) {
            addCriterion("PLATE_COLOR_CODE between", value1, value2, "plateColorCode");
            return (Criteria) this;
        }

        public Criteria andPlateColorCodeNotBetween(String value1, String value2) {
            addCriterion("PLATE_COLOR_CODE not between", value1, value2, "plateColorCode");
            return (Criteria) this;
        }

        public Criteria andCertTypeIsNull() {
            addCriterion("CERT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCertTypeIsNotNull() {
            addCriterion("CERT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCertTypeEqualTo(String value) {
            addCriterion("CERT_TYPE =", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeNotEqualTo(String value) {
            addCriterion("CERT_TYPE <>", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeGreaterThan(String value) {
            addCriterion("CERT_TYPE >", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CERT_TYPE >=", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeLessThan(String value) {
            addCriterion("CERT_TYPE <", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeLessThanOrEqualTo(String value) {
            addCriterion("CERT_TYPE <=", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeLike(String value) {
            addCriterion("CERT_TYPE like", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeNotLike(String value) {
            addCriterion("CERT_TYPE not like", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeIn(List<String> values) {
            addCriterion("CERT_TYPE in", values, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeNotIn(List<String> values) {
            addCriterion("CERT_TYPE not in", values, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeBetween(String value1, String value2) {
            addCriterion("CERT_TYPE between", value1, value2, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeNotBetween(String value1, String value2) {
            addCriterion("CERT_TYPE not between", value1, value2, "certType");
            return (Criteria) this;
        }

        public Criteria andCertGrantTypeIsNull() {
            addCriterion("CERT_GRANT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCertGrantTypeIsNotNull() {
            addCriterion("CERT_GRANT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCertGrantTypeEqualTo(String value) {
            addCriterion("CERT_GRANT_TYPE =", value, "certGrantType");
            return (Criteria) this;
        }

        public Criteria andCertGrantTypeNotEqualTo(String value) {
            addCriterion("CERT_GRANT_TYPE <>", value, "certGrantType");
            return (Criteria) this;
        }

        public Criteria andCertGrantTypeGreaterThan(String value) {
            addCriterion("CERT_GRANT_TYPE >", value, "certGrantType");
            return (Criteria) this;
        }

        public Criteria andCertGrantTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CERT_GRANT_TYPE >=", value, "certGrantType");
            return (Criteria) this;
        }

        public Criteria andCertGrantTypeLessThan(String value) {
            addCriterion("CERT_GRANT_TYPE <", value, "certGrantType");
            return (Criteria) this;
        }

        public Criteria andCertGrantTypeLessThanOrEqualTo(String value) {
            addCriterion("CERT_GRANT_TYPE <=", value, "certGrantType");
            return (Criteria) this;
        }

        public Criteria andCertGrantTypeLike(String value) {
            addCriterion("CERT_GRANT_TYPE like", value, "certGrantType");
            return (Criteria) this;
        }

        public Criteria andCertGrantTypeNotLike(String value) {
            addCriterion("CERT_GRANT_TYPE not like", value, "certGrantType");
            return (Criteria) this;
        }

        public Criteria andCertGrantTypeIn(List<String> values) {
            addCriterion("CERT_GRANT_TYPE in", values, "certGrantType");
            return (Criteria) this;
        }

        public Criteria andCertGrantTypeNotIn(List<String> values) {
            addCriterion("CERT_GRANT_TYPE not in", values, "certGrantType");
            return (Criteria) this;
        }

        public Criteria andCertGrantTypeBetween(String value1, String value2) {
            addCriterion("CERT_GRANT_TYPE between", value1, value2, "certGrantType");
            return (Criteria) this;
        }

        public Criteria andCertGrantTypeNotBetween(String value1, String value2) {
            addCriterion("CERT_GRANT_TYPE not between", value1, value2, "certGrantType");
            return (Criteria) this;
        }

        public Criteria andCertExchangeReasonIsNull() {
            addCriterion("CERT_EXCHANGE_REASON is null");
            return (Criteria) this;
        }

        public Criteria andCertExchangeReasonIsNotNull() {
            addCriterion("CERT_EXCHANGE_REASON is not null");
            return (Criteria) this;
        }

        public Criteria andCertExchangeReasonEqualTo(String value) {
            addCriterion("CERT_EXCHANGE_REASON =", value, "certExchangeReason");
            return (Criteria) this;
        }

        public Criteria andCertExchangeReasonNotEqualTo(String value) {
            addCriterion("CERT_EXCHANGE_REASON <>", value, "certExchangeReason");
            return (Criteria) this;
        }

        public Criteria andCertExchangeReasonGreaterThan(String value) {
            addCriterion("CERT_EXCHANGE_REASON >", value, "certExchangeReason");
            return (Criteria) this;
        }

        public Criteria andCertExchangeReasonGreaterThanOrEqualTo(String value) {
            addCriterion("CERT_EXCHANGE_REASON >=", value, "certExchangeReason");
            return (Criteria) this;
        }

        public Criteria andCertExchangeReasonLessThan(String value) {
            addCriterion("CERT_EXCHANGE_REASON <", value, "certExchangeReason");
            return (Criteria) this;
        }

        public Criteria andCertExchangeReasonLessThanOrEqualTo(String value) {
            addCriterion("CERT_EXCHANGE_REASON <=", value, "certExchangeReason");
            return (Criteria) this;
        }

        public Criteria andCertExchangeReasonLike(String value) {
            addCriterion("CERT_EXCHANGE_REASON like", value, "certExchangeReason");
            return (Criteria) this;
        }

        public Criteria andCertExchangeReasonNotLike(String value) {
            addCriterion("CERT_EXCHANGE_REASON not like", value, "certExchangeReason");
            return (Criteria) this;
        }

        public Criteria andCertExchangeReasonIn(List<String> values) {
            addCriterion("CERT_EXCHANGE_REASON in", values, "certExchangeReason");
            return (Criteria) this;
        }

        public Criteria andCertExchangeReasonNotIn(List<String> values) {
            addCriterion("CERT_EXCHANGE_REASON not in", values, "certExchangeReason");
            return (Criteria) this;
        }

        public Criteria andCertExchangeReasonBetween(String value1, String value2) {
            addCriterion("CERT_EXCHANGE_REASON between", value1, value2, "certExchangeReason");
            return (Criteria) this;
        }

        public Criteria andCertExchangeReasonNotBetween(String value1, String value2) {
            addCriterion("CERT_EXCHANGE_REASON not between", value1, value2, "certExchangeReason");
            return (Criteria) this;
        }

        public Criteria andBeforeCertIsNull() {
            addCriterion("BEFORE_CERT is null");
            return (Criteria) this;
        }

        public Criteria andBeforeCertIsNotNull() {
            addCriterion("BEFORE_CERT is not null");
            return (Criteria) this;
        }

        public Criteria andBeforeCertEqualTo(String value) {
            addCriterion("BEFORE_CERT =", value, "beforeCert");
            return (Criteria) this;
        }

        public Criteria andBeforeCertNotEqualTo(String value) {
            addCriterion("BEFORE_CERT <>", value, "beforeCert");
            return (Criteria) this;
        }

        public Criteria andBeforeCertGreaterThan(String value) {
            addCriterion("BEFORE_CERT >", value, "beforeCert");
            return (Criteria) this;
        }

        public Criteria andBeforeCertGreaterThanOrEqualTo(String value) {
            addCriterion("BEFORE_CERT >=", value, "beforeCert");
            return (Criteria) this;
        }

        public Criteria andBeforeCertLessThan(String value) {
            addCriterion("BEFORE_CERT <", value, "beforeCert");
            return (Criteria) this;
        }

        public Criteria andBeforeCertLessThanOrEqualTo(String value) {
            addCriterion("BEFORE_CERT <=", value, "beforeCert");
            return (Criteria) this;
        }

        public Criteria andBeforeCertLike(String value) {
            addCriterion("BEFORE_CERT like", value, "beforeCert");
            return (Criteria) this;
        }

        public Criteria andBeforeCertNotLike(String value) {
            addCriterion("BEFORE_CERT not like", value, "beforeCert");
            return (Criteria) this;
        }

        public Criteria andBeforeCertIn(List<String> values) {
            addCriterion("BEFORE_CERT in", values, "beforeCert");
            return (Criteria) this;
        }

        public Criteria andBeforeCertNotIn(List<String> values) {
            addCriterion("BEFORE_CERT not in", values, "beforeCert");
            return (Criteria) this;
        }

        public Criteria andBeforeCertBetween(String value1, String value2) {
            addCriterion("BEFORE_CERT between", value1, value2, "beforeCert");
            return (Criteria) this;
        }

        public Criteria andBeforeCertNotBetween(String value1, String value2) {
            addCriterion("BEFORE_CERT not between", value1, value2, "beforeCert");
            return (Criteria) this;
        }

        public Criteria andBeforeCertCardidIsNull() {
            addCriterion("BEFORE_CERT_CARDID is null");
            return (Criteria) this;
        }

        public Criteria andBeforeCertCardidIsNotNull() {
            addCriterion("BEFORE_CERT_CARDID is not null");
            return (Criteria) this;
        }

        public Criteria andBeforeCertCardidEqualTo(String value) {
            addCriterion("BEFORE_CERT_CARDID =", value, "beforeCertCardid");
            return (Criteria) this;
        }

        public Criteria andBeforeCertCardidNotEqualTo(String value) {
            addCriterion("BEFORE_CERT_CARDID <>", value, "beforeCertCardid");
            return (Criteria) this;
        }

        public Criteria andBeforeCertCardidGreaterThan(String value) {
            addCriterion("BEFORE_CERT_CARDID >", value, "beforeCertCardid");
            return (Criteria) this;
        }

        public Criteria andBeforeCertCardidGreaterThanOrEqualTo(String value) {
            addCriterion("BEFORE_CERT_CARDID >=", value, "beforeCertCardid");
            return (Criteria) this;
        }

        public Criteria andBeforeCertCardidLessThan(String value) {
            addCriterion("BEFORE_CERT_CARDID <", value, "beforeCertCardid");
            return (Criteria) this;
        }

        public Criteria andBeforeCertCardidLessThanOrEqualTo(String value) {
            addCriterion("BEFORE_CERT_CARDID <=", value, "beforeCertCardid");
            return (Criteria) this;
        }

        public Criteria andBeforeCertCardidLike(String value) {
            addCriterion("BEFORE_CERT_CARDID like", value, "beforeCertCardid");
            return (Criteria) this;
        }

        public Criteria andBeforeCertCardidNotLike(String value) {
            addCriterion("BEFORE_CERT_CARDID not like", value, "beforeCertCardid");
            return (Criteria) this;
        }

        public Criteria andBeforeCertCardidIn(List<String> values) {
            addCriterion("BEFORE_CERT_CARDID in", values, "beforeCertCardid");
            return (Criteria) this;
        }

        public Criteria andBeforeCertCardidNotIn(List<String> values) {
            addCriterion("BEFORE_CERT_CARDID not in", values, "beforeCertCardid");
            return (Criteria) this;
        }

        public Criteria andBeforeCertCardidBetween(String value1, String value2) {
            addCriterion("BEFORE_CERT_CARDID between", value1, value2, "beforeCertCardid");
            return (Criteria) this;
        }

        public Criteria andBeforeCertCardidNotBetween(String value1, String value2) {
            addCriterion("BEFORE_CERT_CARDID not between", value1, value2, "beforeCertCardid");
            return (Criteria) this;
        }

        public Criteria andAfterCertIsNull() {
            addCriterion("AFTER_CERT is null");
            return (Criteria) this;
        }

        public Criteria andAfterCertIsNotNull() {
            addCriterion("AFTER_CERT is not null");
            return (Criteria) this;
        }

        public Criteria andAfterCertEqualTo(String value) {
            addCriterion("AFTER_CERT =", value, "afterCert");
            return (Criteria) this;
        }

        public Criteria andAfterCertNotEqualTo(String value) {
            addCriterion("AFTER_CERT <>", value, "afterCert");
            return (Criteria) this;
        }

        public Criteria andAfterCertGreaterThan(String value) {
            addCriterion("AFTER_CERT >", value, "afterCert");
            return (Criteria) this;
        }

        public Criteria andAfterCertGreaterThanOrEqualTo(String value) {
            addCriterion("AFTER_CERT >=", value, "afterCert");
            return (Criteria) this;
        }

        public Criteria andAfterCertLessThan(String value) {
            addCriterion("AFTER_CERT <", value, "afterCert");
            return (Criteria) this;
        }

        public Criteria andAfterCertLessThanOrEqualTo(String value) {
            addCriterion("AFTER_CERT <=", value, "afterCert");
            return (Criteria) this;
        }

        public Criteria andAfterCertLike(String value) {
            addCriterion("AFTER_CERT like", value, "afterCert");
            return (Criteria) this;
        }

        public Criteria andAfterCertNotLike(String value) {
            addCriterion("AFTER_CERT not like", value, "afterCert");
            return (Criteria) this;
        }

        public Criteria andAfterCertIn(List<String> values) {
            addCriterion("AFTER_CERT in", values, "afterCert");
            return (Criteria) this;
        }

        public Criteria andAfterCertNotIn(List<String> values) {
            addCriterion("AFTER_CERT not in", values, "afterCert");
            return (Criteria) this;
        }

        public Criteria andAfterCertBetween(String value1, String value2) {
            addCriterion("AFTER_CERT between", value1, value2, "afterCert");
            return (Criteria) this;
        }

        public Criteria andAfterCertNotBetween(String value1, String value2) {
            addCriterion("AFTER_CERT not between", value1, value2, "afterCert");
            return (Criteria) this;
        }

        public Criteria andAfterCertCardidIsNull() {
            addCriterion("AFTER_CERT_CARDID is null");
            return (Criteria) this;
        }

        public Criteria andAfterCertCardidIsNotNull() {
            addCriterion("AFTER_CERT_CARDID is not null");
            return (Criteria) this;
        }

        public Criteria andAfterCertCardidEqualTo(String value) {
            addCriterion("AFTER_CERT_CARDID =", value, "afterCertCardid");
            return (Criteria) this;
        }

        public Criteria andAfterCertCardidNotEqualTo(String value) {
            addCriterion("AFTER_CERT_CARDID <>", value, "afterCertCardid");
            return (Criteria) this;
        }

        public Criteria andAfterCertCardidGreaterThan(String value) {
            addCriterion("AFTER_CERT_CARDID >", value, "afterCertCardid");
            return (Criteria) this;
        }

        public Criteria andAfterCertCardidGreaterThanOrEqualTo(String value) {
            addCriterion("AFTER_CERT_CARDID >=", value, "afterCertCardid");
            return (Criteria) this;
        }

        public Criteria andAfterCertCardidLessThan(String value) {
            addCriterion("AFTER_CERT_CARDID <", value, "afterCertCardid");
            return (Criteria) this;
        }

        public Criteria andAfterCertCardidLessThanOrEqualTo(String value) {
            addCriterion("AFTER_CERT_CARDID <=", value, "afterCertCardid");
            return (Criteria) this;
        }

        public Criteria andAfterCertCardidLike(String value) {
            addCriterion("AFTER_CERT_CARDID like", value, "afterCertCardid");
            return (Criteria) this;
        }

        public Criteria andAfterCertCardidNotLike(String value) {
            addCriterion("AFTER_CERT_CARDID not like", value, "afterCertCardid");
            return (Criteria) this;
        }

        public Criteria andAfterCertCardidIn(List<String> values) {
            addCriterion("AFTER_CERT_CARDID in", values, "afterCertCardid");
            return (Criteria) this;
        }

        public Criteria andAfterCertCardidNotIn(List<String> values) {
            addCriterion("AFTER_CERT_CARDID not in", values, "afterCertCardid");
            return (Criteria) this;
        }

        public Criteria andAfterCertCardidBetween(String value1, String value2) {
            addCriterion("AFTER_CERT_CARDID between", value1, value2, "afterCertCardid");
            return (Criteria) this;
        }

        public Criteria andAfterCertCardidNotBetween(String value1, String value2) {
            addCriterion("AFTER_CERT_CARDID not between", value1, value2, "afterCertCardid");
            return (Criteria) this;
        }

        public Criteria andApplyDateIsNull() {
            addCriterion("APPLY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andApplyDateIsNotNull() {
            addCriterion("APPLY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andApplyDateEqualTo(Date value) {
            addCriterion("APPLY_DATE =", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateNotEqualTo(Date value) {
            addCriterion("APPLY_DATE <>", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateGreaterThan(Date value) {
            addCriterion("APPLY_DATE >", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("APPLY_DATE >=", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateLessThan(Date value) {
            addCriterion("APPLY_DATE <", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateLessThanOrEqualTo(Date value) {
            addCriterion("APPLY_DATE <=", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateIn(List<Date> values) {
            addCriterion("APPLY_DATE in", values, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateNotIn(List<Date> values) {
            addCriterion("APPLY_DATE not in", values, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateBetween(Date value1, Date value2) {
            addCriterion("APPLY_DATE between", value1, value2, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateNotBetween(Date value1, Date value2) {
            addCriterion("APPLY_DATE not between", value1, value2, "applyDate");
            return (Criteria) this;
        }

        public Criteria andExchangeCertDateIsNull() {
            addCriterion("EXCHANGE_CERT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andExchangeCertDateIsNotNull() {
            addCriterion("EXCHANGE_CERT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andExchangeCertDateEqualTo(Date value) {
            addCriterion("EXCHANGE_CERT_DATE =", value, "exchangeCertDate");
            return (Criteria) this;
        }

        public Criteria andExchangeCertDateNotEqualTo(Date value) {
            addCriterion("EXCHANGE_CERT_DATE <>", value, "exchangeCertDate");
            return (Criteria) this;
        }

        public Criteria andExchangeCertDateGreaterThan(Date value) {
            addCriterion("EXCHANGE_CERT_DATE >", value, "exchangeCertDate");
            return (Criteria) this;
        }

        public Criteria andExchangeCertDateGreaterThanOrEqualTo(Date value) {
            addCriterion("EXCHANGE_CERT_DATE >=", value, "exchangeCertDate");
            return (Criteria) this;
        }

        public Criteria andExchangeCertDateLessThan(Date value) {
            addCriterion("EXCHANGE_CERT_DATE <", value, "exchangeCertDate");
            return (Criteria) this;
        }

        public Criteria andExchangeCertDateLessThanOrEqualTo(Date value) {
            addCriterion("EXCHANGE_CERT_DATE <=", value, "exchangeCertDate");
            return (Criteria) this;
        }

        public Criteria andExchangeCertDateIn(List<Date> values) {
            addCriterion("EXCHANGE_CERT_DATE in", values, "exchangeCertDate");
            return (Criteria) this;
        }

        public Criteria andExchangeCertDateNotIn(List<Date> values) {
            addCriterion("EXCHANGE_CERT_DATE not in", values, "exchangeCertDate");
            return (Criteria) this;
        }

        public Criteria andExchangeCertDateBetween(Date value1, Date value2) {
            addCriterion("EXCHANGE_CERT_DATE between", value1, value2, "exchangeCertDate");
            return (Criteria) this;
        }

        public Criteria andExchangeCertDateNotBetween(Date value1, Date value2) {
            addCriterion("EXCHANGE_CERT_DATE not between", value1, value2, "exchangeCertDate");
            return (Criteria) this;
        }

        public Criteria andProcessDateIsNull() {
            addCriterion("PROCESS_DATE is null");
            return (Criteria) this;
        }

        public Criteria andProcessDateIsNotNull() {
            addCriterion("PROCESS_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andProcessDateEqualTo(Date value) {
            addCriterion("PROCESS_DATE =", value, "processDate");
            return (Criteria) this;
        }

        public Criteria andProcessDateNotEqualTo(Date value) {
            addCriterion("PROCESS_DATE <>", value, "processDate");
            return (Criteria) this;
        }

        public Criteria andProcessDateGreaterThan(Date value) {
            addCriterion("PROCESS_DATE >", value, "processDate");
            return (Criteria) this;
        }

        public Criteria andProcessDateGreaterThanOrEqualTo(Date value) {
            addCriterion("PROCESS_DATE >=", value, "processDate");
            return (Criteria) this;
        }

        public Criteria andProcessDateLessThan(Date value) {
            addCriterion("PROCESS_DATE <", value, "processDate");
            return (Criteria) this;
        }

        public Criteria andProcessDateLessThanOrEqualTo(Date value) {
            addCriterion("PROCESS_DATE <=", value, "processDate");
            return (Criteria) this;
        }

        public Criteria andProcessDateIn(List<Date> values) {
            addCriterion("PROCESS_DATE in", values, "processDate");
            return (Criteria) this;
        }

        public Criteria andProcessDateNotIn(List<Date> values) {
            addCriterion("PROCESS_DATE not in", values, "processDate");
            return (Criteria) this;
        }

        public Criteria andProcessDateBetween(Date value1, Date value2) {
            addCriterion("PROCESS_DATE between", value1, value2, "processDate");
            return (Criteria) this;
        }

        public Criteria andProcessDateNotBetween(Date value1, Date value2) {
            addCriterion("PROCESS_DATE not between", value1, value2, "processDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RT_BF_B0104
     *
     * @mbggenerated do_not_delete_during_merge Tue Sep 08 12:31:54 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RT_BF_B0104
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}