package cn.cttic.roadtransapi.orm.roadway.domain;

import java.util.Date;

public class RtBfE0108 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_E0108.PROVINCE_CODE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private Integer provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_E0108.STAFF_ID
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_E0108.ID_TYPE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String idType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_E0108.ID_CARD
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_E0108.DRIVE_LICENSE_NO
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String driveLicenseNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_E0108.QUASI_DRIVE_TYPE_CODE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String quasiDriveTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_E0108.QUASI_DRIVE_TYPE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String quasiDriveType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_E0108.EARLY_DATE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private Date earlyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_E0108.START_DATE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_E0108.END_DATE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RT_BF_E0108.ISSUE_ORG
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    private String issueOrg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_E0108.PROVINCE_CODE
     *
     * @return the value of RT_BF_E0108.PROVINCE_CODE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public Integer getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_E0108.PROVINCE_CODE
     *
     * @param provinceCode the value for RT_BF_E0108.PROVINCE_CODE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setProvinceCode(Integer provinceCode) {
        this.provinceCode = provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_E0108.STAFF_ID
     *
     * @return the value of RT_BF_E0108.STAFF_ID
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_E0108.STAFF_ID
     *
     * @param staffId the value for RT_BF_E0108.STAFF_ID
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId == null ? null : staffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_E0108.ID_TYPE
     *
     * @return the value of RT_BF_E0108.ID_TYPE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_E0108.ID_TYPE
     *
     * @param idType the value for RT_BF_E0108.ID_TYPE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setIdType(String idType) {
        this.idType = idType == null ? null : idType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_E0108.ID_CARD
     *
     * @return the value of RT_BF_E0108.ID_CARD
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_E0108.ID_CARD
     *
     * @param idCard the value for RT_BF_E0108.ID_CARD
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_E0108.DRIVE_LICENSE_NO
     *
     * @return the value of RT_BF_E0108.DRIVE_LICENSE_NO
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getDriveLicenseNo() {
        return driveLicenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_E0108.DRIVE_LICENSE_NO
     *
     * @param driveLicenseNo the value for RT_BF_E0108.DRIVE_LICENSE_NO
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setDriveLicenseNo(String driveLicenseNo) {
        this.driveLicenseNo = driveLicenseNo == null ? null : driveLicenseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_E0108.QUASI_DRIVE_TYPE_CODE
     *
     * @return the value of RT_BF_E0108.QUASI_DRIVE_TYPE_CODE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getQuasiDriveTypeCode() {
        return quasiDriveTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_E0108.QUASI_DRIVE_TYPE_CODE
     *
     * @param quasiDriveTypeCode the value for RT_BF_E0108.QUASI_DRIVE_TYPE_CODE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setQuasiDriveTypeCode(String quasiDriveTypeCode) {
        this.quasiDriveTypeCode = quasiDriveTypeCode == null ? null : quasiDriveTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_E0108.QUASI_DRIVE_TYPE
     *
     * @return the value of RT_BF_E0108.QUASI_DRIVE_TYPE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getQuasiDriveType() {
        return quasiDriveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_E0108.QUASI_DRIVE_TYPE
     *
     * @param quasiDriveType the value for RT_BF_E0108.QUASI_DRIVE_TYPE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setQuasiDriveType(String quasiDriveType) {
        this.quasiDriveType = quasiDriveType == null ? null : quasiDriveType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_E0108.EARLY_DATE
     *
     * @return the value of RT_BF_E0108.EARLY_DATE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public Date getEarlyDate() {
        return earlyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_E0108.EARLY_DATE
     *
     * @param earlyDate the value for RT_BF_E0108.EARLY_DATE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setEarlyDate(Date earlyDate) {
        this.earlyDate = earlyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_E0108.START_DATE
     *
     * @return the value of RT_BF_E0108.START_DATE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_E0108.START_DATE
     *
     * @param startDate the value for RT_BF_E0108.START_DATE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_E0108.END_DATE
     *
     * @return the value of RT_BF_E0108.END_DATE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_E0108.END_DATE
     *
     * @param endDate the value for RT_BF_E0108.END_DATE
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RT_BF_E0108.ISSUE_ORG
     *
     * @return the value of RT_BF_E0108.ISSUE_ORG
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public String getIssueOrg() {
        return issueOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RT_BF_E0108.ISSUE_ORG
     *
     * @param issueOrg the value for RT_BF_E0108.ISSUE_ORG
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    public void setIssueOrg(String issueOrg) {
        this.issueOrg = issueOrg == null ? null : issueOrg.trim();
    }
}