package cn.cttic.roadtransapi.orm.roadway.domain;

import java.util.Date;

public class SmParamCatalog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_PARAM_CATALOG.METADATA_CODE
     *
     * @mbggenerated Fri Aug 07 15:05:17 CST 2015
     */
    private String metadataCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_PARAM_CATALOG.METADATA_NAME
     *
     * @mbggenerated Fri Aug 07 15:05:17 CST 2015
     */
    private String metadataName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_PARAM_CATALOG.TYPE_CODE
     *
     * @mbggenerated Fri Aug 07 15:05:17 CST 2015
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_PARAM_CATALOG.OPER_ID
     *
     * @mbggenerated Fri Aug 07 15:05:17 CST 2015
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_PARAM_CATALOG.MODIFY_DATE
     *
     * @mbggenerated Fri Aug 07 15:05:17 CST 2015
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_PARAM_CATALOG.NOTE
     *
     * @mbggenerated Fri Aug 07 15:05:17 CST 2015
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_PARAM_CATALOG.METADATA_CODE
     *
     * @return the value of SM_PARAM_CATALOG.METADATA_CODE
     *
     * @mbggenerated Fri Aug 07 15:05:17 CST 2015
     */
    public String getMetadataCode() {
        return metadataCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_PARAM_CATALOG.METADATA_CODE
     *
     * @param metadataCode the value for SM_PARAM_CATALOG.METADATA_CODE
     *
     * @mbggenerated Fri Aug 07 15:05:17 CST 2015
     */
    public void setMetadataCode(String metadataCode) {
        this.metadataCode = metadataCode == null ? null : metadataCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_PARAM_CATALOG.METADATA_NAME
     *
     * @return the value of SM_PARAM_CATALOG.METADATA_NAME
     *
     * @mbggenerated Fri Aug 07 15:05:17 CST 2015
     */
    public String getMetadataName() {
        return metadataName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_PARAM_CATALOG.METADATA_NAME
     *
     * @param metadataName the value for SM_PARAM_CATALOG.METADATA_NAME
     *
     * @mbggenerated Fri Aug 07 15:05:17 CST 2015
     */
    public void setMetadataName(String metadataName) {
        this.metadataName = metadataName == null ? null : metadataName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_PARAM_CATALOG.TYPE_CODE
     *
     * @return the value of SM_PARAM_CATALOG.TYPE_CODE
     *
     * @mbggenerated Fri Aug 07 15:05:17 CST 2015
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_PARAM_CATALOG.TYPE_CODE
     *
     * @param typeCode the value for SM_PARAM_CATALOG.TYPE_CODE
     *
     * @mbggenerated Fri Aug 07 15:05:17 CST 2015
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_PARAM_CATALOG.OPER_ID
     *
     * @return the value of SM_PARAM_CATALOG.OPER_ID
     *
     * @mbggenerated Fri Aug 07 15:05:17 CST 2015
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_PARAM_CATALOG.OPER_ID
     *
     * @param operId the value for SM_PARAM_CATALOG.OPER_ID
     *
     * @mbggenerated Fri Aug 07 15:05:17 CST 2015
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_PARAM_CATALOG.MODIFY_DATE
     *
     * @return the value of SM_PARAM_CATALOG.MODIFY_DATE
     *
     * @mbggenerated Fri Aug 07 15:05:17 CST 2015
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_PARAM_CATALOG.MODIFY_DATE
     *
     * @param modifyDate the value for SM_PARAM_CATALOG.MODIFY_DATE
     *
     * @mbggenerated Fri Aug 07 15:05:17 CST 2015
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_PARAM_CATALOG.NOTE
     *
     * @return the value of SM_PARAM_CATALOG.NOTE
     *
     * @mbggenerated Fri Aug 07 15:05:17 CST 2015
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_PARAM_CATALOG.NOTE
     *
     * @param note the value for SM_PARAM_CATALOG.NOTE
     *
     * @mbggenerated Fri Aug 07 15:05:17 CST 2015
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}