package cn.cttic.roadtransapi.orm.waterway.dao;

import cn.cttic.roadtransapi.orm.waterway.domain.CertiAttrRela;
import cn.cttic.roadtransapi.orm.waterway.domain.CertiAttrRelaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CertiAttrRelaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_ATTR_RELA
     *
     * @mbggenerated Sat Dec 06 11:03:05 CST 2014
     */
    int countByExample(CertiAttrRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_ATTR_RELA
     *
     * @mbggenerated Sat Dec 06 11:03:05 CST 2014
     */
    int deleteByExample(CertiAttrRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_ATTR_RELA
     *
     * @mbggenerated Sat Dec 06 11:03:05 CST 2014
     */
    int deleteByPrimaryKey(Long certiAttrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_ATTR_RELA
     *
     * @mbggenerated Sat Dec 06 11:03:05 CST 2014
     */
    int insert(CertiAttrRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_ATTR_RELA
     *
     * @mbggenerated Sat Dec 06 11:03:05 CST 2014
     */
    int insertSelective(CertiAttrRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_ATTR_RELA
     *
     * @mbggenerated Sat Dec 06 11:03:05 CST 2014
     */
    List<CertiAttrRela> selectByExample(CertiAttrRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_ATTR_RELA
     *
     * @mbggenerated Sat Dec 06 11:03:05 CST 2014
     */
    CertiAttrRela selectByPrimaryKey(Long certiAttrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_ATTR_RELA
     *
     * @mbggenerated Sat Dec 06 11:03:05 CST 2014
     */
    int updateByExampleSelective(@Param("record") CertiAttrRela record, @Param("example") CertiAttrRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_ATTR_RELA
     *
     * @mbggenerated Sat Dec 06 11:03:05 CST 2014
     */
    int updateByExample(@Param("record") CertiAttrRela record, @Param("example") CertiAttrRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_ATTR_RELA
     *
     * @mbggenerated Sat Dec 06 11:03:05 CST 2014
     */
    int updateByPrimaryKeySelective(CertiAttrRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_ATTR_RELA
     *
     * @mbggenerated Sat Dec 06 11:03:05 CST 2014
     */
    int updateByPrimaryKey(CertiAttrRela record);
}