package cn.cttic.roadtransapi.orm.waterway.dao;

import cn.cttic.roadtransapi.orm.waterway.domain.CertiShip;
import cn.cttic.roadtransapi.orm.waterway.domain.CertiShipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CertiShipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_SHIP
     *
     * @mbggenerated Tue Feb 03 10:47:44 CST 2015
     */
    int countByExample(CertiShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_SHIP
     *
     * @mbggenerated Tue Feb 03 10:47:44 CST 2015
     */
    int deleteByExample(CertiShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_SHIP
     *
     * @mbggenerated Tue Feb 03 10:47:44 CST 2015
     */
    int deleteByPrimaryKey(Long infoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_SHIP
     *
     * @mbggenerated Tue Feb 03 10:47:44 CST 2015
     */
    int insert(CertiShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_SHIP
     *
     * @mbggenerated Tue Feb 03 10:47:44 CST 2015
     */
    int insertSelective(CertiShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_SHIP
     *
     * @mbggenerated Tue Feb 03 10:47:44 CST 2015
     */
    List<CertiShip> selectByExample(CertiShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_SHIP
     *
     * @mbggenerated Tue Feb 03 10:47:44 CST 2015
     */
    CertiShip selectByPrimaryKey(Long infoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_SHIP
     *
     * @mbggenerated Tue Feb 03 10:47:44 CST 2015
     */
    int updateByExampleSelective(@Param("record") CertiShip record, @Param("example") CertiShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_SHIP
     *
     * @mbggenerated Tue Feb 03 10:47:44 CST 2015
     */
    int updateByExample(@Param("record") CertiShip record, @Param("example") CertiShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_SHIP
     *
     * @mbggenerated Tue Feb 03 10:47:44 CST 2015
     */
    int updateByPrimaryKeySelective(CertiShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CERTI_SHIP
     *
     * @mbggenerated Tue Feb 03 10:47:44 CST 2015
     */
    int updateByPrimaryKey(CertiShip record);
}