package cn.cttic.roadtransapi.orm.waterway.dao;

import cn.cttic.roadtransapi.orm.waterway.domain.OrdCertiShip;
import cn.cttic.roadtransapi.orm.waterway.domain.OrdCertiShipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrdCertiShipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTI_SHIP
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    int countByExample(OrdCertiShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTI_SHIP
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    int deleteByExample(OrdCertiShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTI_SHIP
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    int deleteByPrimaryKey(Long serialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTI_SHIP
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    int insert(OrdCertiShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTI_SHIP
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    int insertSelective(OrdCertiShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTI_SHIP
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    List<OrdCertiShip> selectByExample(OrdCertiShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTI_SHIP
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    OrdCertiShip selectByPrimaryKey(Long serialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTI_SHIP
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    int updateByExampleSelective(@Param("record") OrdCertiShip record, @Param("example") OrdCertiShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTI_SHIP
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    int updateByExample(@Param("record") OrdCertiShip record, @Param("example") OrdCertiShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTI_SHIP
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    int updateByPrimaryKeySelective(OrdCertiShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTI_SHIP
     *
     * @mbggenerated Mon Jun 29 16:21:54 CST 2015
     */
    int updateByPrimaryKey(OrdCertiShip record);
}