package cn.cttic.roadtransapi.orm.waterway.dao;

import cn.cttic.roadtransapi.orm.waterway.domain.OrdCertificate;
import cn.cttic.roadtransapi.orm.waterway.domain.OrdCertificateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrdCertificateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTIFICATE
     *
     * @mbggenerated Wed Jun 24 20:39:59 CST 2015
     */
    int countByExample(OrdCertificateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTIFICATE
     *
     * @mbggenerated Wed Jun 24 20:39:59 CST 2015
     */
    int deleteByExample(OrdCertificateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTIFICATE
     *
     * @mbggenerated Wed Jun 24 20:39:59 CST 2015
     */
    int deleteByPrimaryKey(Long certiOrdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTIFICATE
     *
     * @mbggenerated Wed Jun 24 20:39:59 CST 2015
     */
    int insert(OrdCertificate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTIFICATE
     *
     * @mbggenerated Wed Jun 24 20:39:59 CST 2015
     */
    int insertSelective(OrdCertificate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTIFICATE
     *
     * @mbggenerated Wed Jun 24 20:39:59 CST 2015
     */
    List<OrdCertificate> selectByExample(OrdCertificateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTIFICATE
     *
     * @mbggenerated Wed Jun 24 20:39:59 CST 2015
     */
    OrdCertificate selectByPrimaryKey(Long certiOrdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTIFICATE
     *
     * @mbggenerated Wed Jun 24 20:39:59 CST 2015
     */
    int updateByExampleSelective(@Param("record") OrdCertificate record, @Param("example") OrdCertificateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTIFICATE
     *
     * @mbggenerated Wed Jun 24 20:39:59 CST 2015
     */
    int updateByExample(@Param("record") OrdCertificate record, @Param("example") OrdCertificateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTIFICATE
     *
     * @mbggenerated Wed Jun 24 20:39:59 CST 2015
     */
    int updateByPrimaryKeySelective(OrdCertificate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_CERTIFICATE
     *
     * @mbggenerated Wed Jun 24 20:39:59 CST 2015
     */
    int updateByPrimaryKey(OrdCertificate record);
}