package cn.cttic.roadtransapi.orm.waterway.dao;

import cn.cttic.roadtransapi.orm.waterway.domain.OrdEntInfo;
import cn.cttic.roadtransapi.orm.waterway.domain.OrdEntInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrdEntInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ENT_INFO
     *
     * @mbggenerated Wed Jun 24 18:37:34 CST 2015
     */
    int countByExample(OrdEntInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ENT_INFO
     *
     * @mbggenerated Wed Jun 24 18:37:34 CST 2015
     */
    int deleteByExample(OrdEntInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ENT_INFO
     *
     * @mbggenerated Wed Jun 24 18:37:34 CST 2015
     */
    int deleteByPrimaryKey(Long serialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ENT_INFO
     *
     * @mbggenerated Wed Jun 24 18:37:34 CST 2015
     */
    int insert(OrdEntInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ENT_INFO
     *
     * @mbggenerated Wed Jun 24 18:37:34 CST 2015
     */
    int insertSelective(OrdEntInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ENT_INFO
     *
     * @mbggenerated Wed Jun 24 18:37:34 CST 2015
     */
    List<OrdEntInfo> selectByExample(OrdEntInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ENT_INFO
     *
     * @mbggenerated Wed Jun 24 18:37:34 CST 2015
     */
    OrdEntInfo selectByPrimaryKey(Long serialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ENT_INFO
     *
     * @mbggenerated Wed Jun 24 18:37:34 CST 2015
     */
    int updateByExampleSelective(@Param("record") OrdEntInfo record, @Param("example") OrdEntInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ENT_INFO
     *
     * @mbggenerated Wed Jun 24 18:37:34 CST 2015
     */
    int updateByExample(@Param("record") OrdEntInfo record, @Param("example") OrdEntInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ENT_INFO
     *
     * @mbggenerated Wed Jun 24 18:37:34 CST 2015
     */
    int updateByPrimaryKeySelective(OrdEntInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ENT_INFO
     *
     * @mbggenerated Wed Jun 24 18:37:34 CST 2015
     */
    int updateByPrimaryKey(OrdEntInfo record);
}