package cn.cttic.roadtransapi.orm.waterway.dao;

import cn.cttic.roadtransapi.orm.waterway.domain.VoluPriceInfo;
import cn.cttic.roadtransapi.orm.waterway.domain.VoluPriceInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VoluPriceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOLU_PRICE_INFO
     *
     * @mbggenerated Fri Apr 10 09:51:42 CST 2015
     */
    int countByExample(VoluPriceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOLU_PRICE_INFO
     *
     * @mbggenerated Fri Apr 10 09:51:42 CST 2015
     */
    int deleteByExample(VoluPriceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOLU_PRICE_INFO
     *
     * @mbggenerated Fri Apr 10 09:51:42 CST 2015
     */
    int deleteByPrimaryKey(Long volumePriceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOLU_PRICE_INFO
     *
     * @mbggenerated Fri Apr 10 09:51:42 CST 2015
     */
    int insert(VoluPriceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOLU_PRICE_INFO
     *
     * @mbggenerated Fri Apr 10 09:51:42 CST 2015
     */
    int insertSelective(VoluPriceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOLU_PRICE_INFO
     *
     * @mbggenerated Fri Apr 10 09:51:42 CST 2015
     */
    List<VoluPriceInfo> selectByExample(VoluPriceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOLU_PRICE_INFO
     *
     * @mbggenerated Fri Apr 10 09:51:42 CST 2015
     */
    VoluPriceInfo selectByPrimaryKey(Long volumePriceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOLU_PRICE_INFO
     *
     * @mbggenerated Fri Apr 10 09:51:42 CST 2015
     */
    int updateByExampleSelective(@Param("record") VoluPriceInfo record, @Param("example") VoluPriceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOLU_PRICE_INFO
     *
     * @mbggenerated Fri Apr 10 09:51:42 CST 2015
     */
    int updateByExample(@Param("record") VoluPriceInfo record, @Param("example") VoluPriceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOLU_PRICE_INFO
     *
     * @mbggenerated Fri Apr 10 09:51:42 CST 2015
     */
    int updateByPrimaryKeySelective(VoluPriceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOLU_PRICE_INFO
     *
     * @mbggenerated Fri Apr 10 09:51:42 CST 2015
     */
    int updateByPrimaryKey(VoluPriceInfo record);
}