package cn.cttic.roadtransapi.orm.roadway.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.cttic.roadtransapi.orm.roadway.domain.DwAssessinfoSkilllevelVehic;
import cn.cttic.roadtransapi.orm.roadway.domain.DwAssessinfoSkilllevelVehicExample;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

public interface DwAssessinfoSkilllevelVehicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_ASSESSINFO_SKILLLEVEL_VEHIC
     *
     * @mbggenerated Tue Jul 28 14:02:03 CST 2015
     */
    int countByExample(DwAssessinfoSkilllevelVehicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_ASSESSINFO_SKILLLEVEL_VEHIC
     *
     * @mbggenerated Tue Jul 28 14:02:03 CST 2015
     */
    int deleteByExample(DwAssessinfoSkilllevelVehicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_ASSESSINFO_SKILLLEVEL_VEHIC
     *
     * @mbggenerated Tue Jul 28 14:02:03 CST 2015
     */
    int insert(DwAssessinfoSkilllevelVehic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_ASSESSINFO_SKILLLEVEL_VEHIC
     *
     * @mbggenerated Tue Jul 28 14:02:03 CST 2015
     */
    int insertSelective(DwAssessinfoSkilllevelVehic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_ASSESSINFO_SKILLLEVEL_VEHIC
     *
     * @mbggenerated Tue Jul 28 14:02:03 CST 2015
     */
    List<DwAssessinfoSkilllevelVehic> selectByExample(DwAssessinfoSkilllevelVehicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_ASSESSINFO_SKILLLEVEL_VEHIC
     *
     * @mbggenerated Tue Jul 28 14:02:03 CST 2015
     */
    int updateByExampleSelective(@Param("record") DwAssessinfoSkilllevelVehic record, @Param("example") DwAssessinfoSkilllevelVehicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_ASSESSINFO_SKILLLEVEL_VEHIC
     *
     * @mbggenerated Tue Jul 28 14:02:03 CST 2015
     */
    int updateByExample(@Param("record") DwAssessinfoSkilllevelVehic record, @Param("example") DwAssessinfoSkilllevelVehicExample example);
    
    
    PageList<DwAssessinfoSkilllevelVehic> selectByExampleForPage(DwAssessinfoSkilllevelVehicExample example,PageBounds pageBounds);
}