package cn.cttic.roadtransapi.orm.roadway.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.cttic.roadtransapi.orm.roadway.domain.DwBaseinfoLineOperating;
import cn.cttic.roadtransapi.orm.roadway.domain.DwBaseinfoLineOperatingExample;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

public interface DwBaseinfoLineOperatingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int countByExample(DwBaseinfoLineOperatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int deleteByExample(DwBaseinfoLineOperatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int insert(DwBaseinfoLineOperating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int insertSelective(DwBaseinfoLineOperating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    List<DwBaseinfoLineOperating> selectByExample(DwBaseinfoLineOperatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") DwBaseinfoLineOperating record, @Param("example") DwBaseinfoLineOperatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_OPERATING
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int updateByExample(@Param("record") DwBaseinfoLineOperating record, @Param("example") DwBaseinfoLineOperatingExample example);
    
    PageList<DwBaseinfoLineOperating> selectByExampleForPage(DwBaseinfoLineOperatingExample example,PageBounds pageBounds);
}