package cn.cttic.roadtransapi.orm.roadway.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.cttic.roadtransapi.orm.roadway.domain.DwBaseinfoTransCert;
import cn.cttic.roadtransapi.orm.roadway.domain.DwBaseinfoTransCertExample;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

public interface DwBaseinfoTransCertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_TRANS_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int countByExample(DwBaseinfoTransCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_TRANS_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int deleteByExample(DwBaseinfoTransCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_TRANS_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int insert(DwBaseinfoTransCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_TRANS_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int insertSelective(DwBaseinfoTransCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_TRANS_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    List<DwBaseinfoTransCert> selectByExample(DwBaseinfoTransCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_TRANS_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") DwBaseinfoTransCert record, @Param("example") DwBaseinfoTransCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_TRANS_CERT
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int updateByExample(@Param("record") DwBaseinfoTransCert record, @Param("example") DwBaseinfoTransCertExample example);
    
    PageList<DwBaseinfoTransCert> selectByExampleForPage(DwBaseinfoTransCertExample example,PageBounds pageBounds);
}