package cn.cttic.roadtransapi.orm.roadway.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.cttic.roadtransapi.orm.roadway.domain.DwBaseinfoStaff;
import cn.cttic.roadtransapi.orm.roadway.domain.DwBaseinfoStaffExample;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

public interface DwBaseinfoStaffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_STAFF
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int countByExample(DwBaseinfoStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_STAFF
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int deleteByExample(DwBaseinfoStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_STAFF
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int insert(DwBaseinfoStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_STAFF
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int insertSelective(DwBaseinfoStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_STAFF
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    List<DwBaseinfoStaff> selectByExample(DwBaseinfoStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_STAFF
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") DwBaseinfoStaff record, @Param("example") DwBaseinfoStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_STAFF
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int updateByExample(@Param("record") DwBaseinfoStaff record, @Param("example") DwBaseinfoStaffExample example);
    
    PageList<DwBaseinfoStaff> selectByExampleForPage(DwBaseinfoStaffExample example,PageBounds pageBounds);
}