package cn.cttic.roadtransapi.orm.roadway.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.cttic.roadtransapi.orm.roadway.domain.DwBaseinfoLineDenoter;
import cn.cttic.roadtransapi.orm.roadway.domain.DwBaseinfoLineDenoterExample;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

public interface DwBaseinfoLineDenoterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_DENOTER
     *
     * @mbggenerated Tue Jul 28 09:33:42 CST 2015
     */
    int countByExample(DwBaseinfoLineDenoterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_DENOTER
     *
     * @mbggenerated Tue Jul 28 09:33:42 CST 2015
     */
    int deleteByExample(DwBaseinfoLineDenoterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_DENOTER
     *
     * @mbggenerated Tue Jul 28 09:33:42 CST 2015
     */
    int insert(DwBaseinfoLineDenoter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_DENOTER
     *
     * @mbggenerated Tue Jul 28 09:33:42 CST 2015
     */
    int insertSelective(DwBaseinfoLineDenoter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_DENOTER
     *
     * @mbggenerated Tue Jul 28 09:33:42 CST 2015
     */
    List<DwBaseinfoLineDenoter> selectByExample(DwBaseinfoLineDenoterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_DENOTER
     *
     * @mbggenerated Tue Jul 28 09:33:42 CST 2015
     */
    int updateByExampleSelective(@Param("record") DwBaseinfoLineDenoter record, @Param("example") DwBaseinfoLineDenoterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_DENOTER
     *
     * @mbggenerated Tue Jul 28 09:33:42 CST 2015
     */
    int updateByExample(@Param("record") DwBaseinfoLineDenoter record, @Param("example") DwBaseinfoLineDenoterExample example);
    
    PageList<DwBaseinfoLineDenoter> selectByExampleForPage(DwBaseinfoLineDenoterExample example,PageBounds pageBounds);
}