package cn.cttic.roadtransapi.orm.roadway.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.cttic.roadtransapi.orm.roadway.domain.DwBaseinfoLinePhysics;
import cn.cttic.roadtransapi.orm.roadway.domain.DwBaseinfoLinePhysicsExample;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

public interface DwBaseinfoLinePhysicsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_PHYSICS
     *
     * @mbggenerated Tue Jul 28 09:33:42 CST 2015
     */
    int countByExample(DwBaseinfoLinePhysicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_PHYSICS
     *
     * @mbggenerated Tue Jul 28 09:33:42 CST 2015
     */
    int deleteByExample(DwBaseinfoLinePhysicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_PHYSICS
     *
     * @mbggenerated Tue Jul 28 09:33:42 CST 2015
     */
    int insert(DwBaseinfoLinePhysics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_PHYSICS
     *
     * @mbggenerated Tue Jul 28 09:33:42 CST 2015
     */
    int insertSelective(DwBaseinfoLinePhysics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_PHYSICS
     *
     * @mbggenerated Tue Jul 28 09:33:42 CST 2015
     */
    List<DwBaseinfoLinePhysics> selectByExample(DwBaseinfoLinePhysicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_PHYSICS
     *
     * @mbggenerated Tue Jul 28 09:33:42 CST 2015
     */
    int updateByExampleSelective(@Param("record") DwBaseinfoLinePhysics record, @Param("example") DwBaseinfoLinePhysicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_LINE_PHYSICS
     *
     * @mbggenerated Tue Jul 28 09:33:42 CST 2015
     */
    int updateByExample(@Param("record") DwBaseinfoLinePhysics record, @Param("example") DwBaseinfoLinePhysicsExample example);
    
    PageList<DwBaseinfoLinePhysics> selectByExampleForPage(DwBaseinfoLinePhysicsExample example,PageBounds pageBounds);
}