package cn.cttic.roadtransapi.orm.roadway.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.cttic.roadtransapi.orm.roadway.domain.DwBaseinfoManageOrgan;
import cn.cttic.roadtransapi.orm.roadway.domain.DwBaseinfoManageOrganExample;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

public interface DwBaseinfoManageOrganMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_MANAGE_ORGAN
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int countByExample(DwBaseinfoManageOrganExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_MANAGE_ORGAN
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int deleteByExample(DwBaseinfoManageOrganExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_MANAGE_ORGAN
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int insert(DwBaseinfoManageOrgan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_MANAGE_ORGAN
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int insertSelective(DwBaseinfoManageOrgan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_MANAGE_ORGAN
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    List<DwBaseinfoManageOrgan> selectByExample(DwBaseinfoManageOrganExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_MANAGE_ORGAN
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") DwBaseinfoManageOrgan record, @Param("example") DwBaseinfoManageOrganExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_BASEINFO_MANAGE_ORGAN
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int updateByExample(@Param("record") DwBaseinfoManageOrgan record, @Param("example") DwBaseinfoManageOrganExample example);
    
    PageList<DwBaseinfoManageOrgan> selectByExampleForPage(DwBaseinfoManageOrganExample example,PageBounds pageBounds);
}