package cn.cttic.roadtransapi.orm.roadway.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.cttic.roadtransapi.orm.roadway.domain.DwInfoBusinessLicense;
import cn.cttic.roadtransapi.orm.roadway.domain.DwInfoBusinessLicenseExample;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

public interface DwInfoBusinessLicenseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_INFO_BUSINESS_LICENSE
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int countByExample(DwInfoBusinessLicenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_INFO_BUSINESS_LICENSE
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int deleteByExample(DwInfoBusinessLicenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_INFO_BUSINESS_LICENSE
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int insert(DwInfoBusinessLicense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_INFO_BUSINESS_LICENSE
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int insertSelective(DwInfoBusinessLicense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_INFO_BUSINESS_LICENSE
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    List<DwInfoBusinessLicense> selectByExample(DwInfoBusinessLicenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_INFO_BUSINESS_LICENSE
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") DwInfoBusinessLicense record, @Param("example") DwInfoBusinessLicenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_INFO_BUSINESS_LICENSE
     *
     * @mbggenerated Fri Jul 24 08:19:14 CST 2015
     */
    int updateByExample(@Param("record") DwInfoBusinessLicense record, @Param("example") DwInfoBusinessLicenseExample example);
    
    PageList<DwInfoBusinessLicense> selectByExampleForPage(DwInfoBusinessLicenseExample example,PageBounds pageBounds);
    
}