package cn.cttic.roadtransapi.orm.roadway.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.cttic.roadtransapi.orm.roadway.domain.DwInfoRoadownerCheck;
import cn.cttic.roadtransapi.orm.roadway.domain.DwInfoRoadownerCheckExample;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

public interface DwInfoRoadownerCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_INFO_ROADOWNER_CHECK
     *
     * @mbggenerated Thu Jul 30 15:30:40 CST 2015
     */
    int countByExample(DwInfoRoadownerCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_INFO_ROADOWNER_CHECK
     *
     * @mbggenerated Thu Jul 30 15:30:40 CST 2015
     */
    int deleteByExample(DwInfoRoadownerCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_INFO_ROADOWNER_CHECK
     *
     * @mbggenerated Thu Jul 30 15:30:40 CST 2015
     */
    int insert(DwInfoRoadownerCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_INFO_ROADOWNER_CHECK
     *
     * @mbggenerated Thu Jul 30 15:30:40 CST 2015
     */
    int insertSelective(DwInfoRoadownerCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_INFO_ROADOWNER_CHECK
     *
     * @mbggenerated Thu Jul 30 15:30:40 CST 2015
     */
    List<DwInfoRoadownerCheck> selectByExample(DwInfoRoadownerCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_INFO_ROADOWNER_CHECK
     *
     * @mbggenerated Thu Jul 30 15:30:40 CST 2015
     */
    int updateByExampleSelective(@Param("record") DwInfoRoadownerCheck record, @Param("example") DwInfoRoadownerCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_INFO_ROADOWNER_CHECK
     *
     * @mbggenerated Thu Jul 30 15:30:40 CST 2015
     */
    int updateByExample(@Param("record") DwInfoRoadownerCheck record, @Param("example") DwInfoRoadownerCheckExample example);

    PageList<DwInfoRoadownerCheck> selectByExampleForPage(DwInfoRoadownerCheckExample example,PageBounds pageBounds);


}