package cn.cttic.roadtransapi.orm.roadway.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.cttic.roadtransapi.orm.roadway.domain.DwServiceinfoSeclevelVehicl;
import cn.cttic.roadtransapi.orm.roadway.domain.DwServiceinfoSeclevelVehiclExample;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

public interface DwServiceinfoSeclevelVehiclMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_SERVICEINFO_SECLEVEL_VEHICL
     *
     * @mbggenerated Tue Jul 28 15:52:51 CST 2015
     */
    int countByExample(DwServiceinfoSeclevelVehiclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_SERVICEINFO_SECLEVEL_VEHICL
     *
     * @mbggenerated Tue Jul 28 15:52:51 CST 2015
     */
    int deleteByExample(DwServiceinfoSeclevelVehiclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_SERVICEINFO_SECLEVEL_VEHICL
     *
     * @mbggenerated Tue Jul 28 15:52:51 CST 2015
     */
    int insert(DwServiceinfoSeclevelVehicl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_SERVICEINFO_SECLEVEL_VEHICL
     *
     * @mbggenerated Tue Jul 28 15:52:51 CST 2015
     */
    int insertSelective(DwServiceinfoSeclevelVehicl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_SERVICEINFO_SECLEVEL_VEHICL
     *
     * @mbggenerated Tue Jul 28 15:52:51 CST 2015
     */
    List<DwServiceinfoSeclevelVehicl> selectByExample(DwServiceinfoSeclevelVehiclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_SERVICEINFO_SECLEVEL_VEHICL
     *
     * @mbggenerated Tue Jul 28 15:52:51 CST 2015
     */
    int updateByExampleSelective(@Param("record") DwServiceinfoSeclevelVehicl record, @Param("example") DwServiceinfoSeclevelVehiclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DW_SERVICEINFO_SECLEVEL_VEHICL
     *
     * @mbggenerated Tue Jul 28 15:52:51 CST 2015
     */
    int updateByExample(@Param("record") DwServiceinfoSeclevelVehicl record, @Param("example") DwServiceinfoSeclevelVehiclExample example);
    
    
    
    PageList<DwServiceinfoSeclevelVehicl> selectByExampleForPage(DwServiceinfoSeclevelVehiclExample example,PageBounds pageBounds);

}