package cn.cttic.roadtransapi.orm.roadway.dao;

import cn.cttic.roadtransapi.orm.roadway.domain.RtBfF0102;
import cn.cttic.roadtransapi.orm.roadway.domain.RtBfF0102Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RtBfF0102Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_F0102
     *
     * @mbggenerated Mon Jun 15 16:31:19 CST 2015
     */
    int countByExample(RtBfF0102Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_F0102
     *
     * @mbggenerated Mon Jun 15 16:31:19 CST 2015
     */
    int deleteByExample(RtBfF0102Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_F0102
     *
     * @mbggenerated Mon Jun 15 16:31:19 CST 2015
     */
    int insert(RtBfF0102 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_F0102
     *
     * @mbggenerated Mon Jun 15 16:31:19 CST 2015
     */
    int insertSelective(RtBfF0102 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_F0102
     *
     * @mbggenerated Mon Jun 15 16:31:19 CST 2015
     */
    List<RtBfF0102> selectByExample(RtBfF0102Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_F0102
     *
     * @mbggenerated Mon Jun 15 16:31:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") RtBfF0102 record, @Param("example") RtBfF0102Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_F0102
     *
     * @mbggenerated Mon Jun 15 16:31:19 CST 2015
     */
    int updateByExample(@Param("record") RtBfF0102 record, @Param("example") RtBfF0102Example example);
}