package cn.cttic.roadtransapi.orm.roadway.dao;

import cn.cttic.roadtransapi.orm.roadway.domain.RtBfE0103;
import cn.cttic.roadtransapi.orm.roadway.domain.RtBfE0103Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RtBfE0103Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_E0103
     *
     * @mbggenerated Mon Jun 15 16:31:19 CST 2015
     */
    int countByExample(RtBfE0103Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_E0103
     *
     * @mbggenerated Mon Jun 15 16:31:19 CST 2015
     */
    int deleteByExample(RtBfE0103Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_E0103
     *
     * @mbggenerated Mon Jun 15 16:31:19 CST 2015
     */
    int insert(RtBfE0103 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_E0103
     *
     * @mbggenerated Mon Jun 15 16:31:19 CST 2015
     */
    int insertSelective(RtBfE0103 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_E0103
     *
     * @mbggenerated Mon Jun 15 16:31:19 CST 2015
     */
    List<RtBfE0103> selectByExample(RtBfE0103Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_E0103
     *
     * @mbggenerated Mon Jun 15 16:31:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") RtBfE0103 record, @Param("example") RtBfE0103Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_E0103
     *
     * @mbggenerated Mon Jun 15 16:31:19 CST 2015
     */
    int updateByExample(@Param("record") RtBfE0103 record, @Param("example") RtBfE0103Example example);
}