package cn.cttic.roadtransapi.orm.roadway.dao;

import cn.cttic.roadtransapi.orm.roadway.domain.RtBfA0106;
import cn.cttic.roadtransapi.orm.roadway.domain.RtBfA0106Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RtBfA0106Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_A0106
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    int countByExample(RtBfA0106Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_A0106
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    int deleteByExample(RtBfA0106Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_A0106
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    int insert(RtBfA0106 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_A0106
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    int insertSelective(RtBfA0106 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_A0106
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    List<RtBfA0106> selectByExample(RtBfA0106Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_A0106
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    int updateByExampleSelective(@Param("record") RtBfA0106 record, @Param("example") RtBfA0106Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_A0106
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    int updateByExample(@Param("record") RtBfA0106 record, @Param("example") RtBfA0106Example example);
}