package cn.cttic.roadtransapi.orm.roadway.dao;

import cn.cttic.roadtransapi.orm.roadway.domain.RtBfA0109;
import cn.cttic.roadtransapi.orm.roadway.domain.RtBfA0109Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RtBfA0109Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_A0109
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    int countByExample(RtBfA0109Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_A0109
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    int deleteByExample(RtBfA0109Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_A0109
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    int insert(RtBfA0109 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_A0109
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    int insertSelective(RtBfA0109 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_A0109
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    List<RtBfA0109> selectByExample(RtBfA0109Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_A0109
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    int updateByExampleSelective(@Param("record") RtBfA0109 record, @Param("example") RtBfA0109Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_A0109
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    int updateByExample(@Param("record") RtBfA0109 record, @Param("example") RtBfA0109Example example);
}