package cn.cttic.roadtransapi.orm.roadway.dao;

import cn.cttic.roadtransapi.orm.roadway.domain.RtBfB0101;
import cn.cttic.roadtransapi.orm.roadway.domain.RtBfB0101Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RtBfB0101Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0101
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    int countByExample(RtBfB0101Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0101
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    int deleteByExample(RtBfB0101Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0101
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    int insert(RtBfB0101 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0101
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    int insertSelective(RtBfB0101 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0101
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    List<RtBfB0101> selectByExampleWithBLOBs(RtBfB0101Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0101
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    List<RtBfB0101> selectByExample(RtBfB0101Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0101
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    int updateByExampleSelective(@Param("record") RtBfB0101 record, @Param("example") RtBfB0101Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0101
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") RtBfB0101 record, @Param("example") RtBfB0101Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0101
     *
     * @mbggenerated Tue Jun 16 16:28:09 CST 2015
     */
    int updateByExample(@Param("record") RtBfB0101 record, @Param("example") RtBfB0101Example example);
}