package cn.cttic.roadtransapi.orm.roadway.dao;

import cn.cttic.roadtransapi.orm.roadway.domain.RtBfF0103;
import cn.cttic.roadtransapi.orm.roadway.domain.RtBfF0103Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RtBfF0103Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_F0103
     *
     * @mbggenerated Mon Jun 15 16:31:19 CST 2015
     */
    int countByExample(RtBfF0103Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_F0103
     *
     * @mbggenerated Mon Jun 15 16:31:19 CST 2015
     */
    int deleteByExample(RtBfF0103Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_F0103
     *
     * @mbggenerated Mon Jun 15 16:31:19 CST 2015
     */
    int insert(RtBfF0103 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_F0103
     *
     * @mbggenerated Mon Jun 15 16:31:19 CST 2015
     */
    int insertSelective(RtBfF0103 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_F0103
     *
     * @mbggenerated Mon Jun 15 16:31:19 CST 2015
     */
    List<RtBfF0103> selectByExample(RtBfF0103Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_F0103
     *
     * @mbggenerated Mon Jun 15 16:31:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") RtBfF0103 record, @Param("example") RtBfF0103Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_F0103
     *
     * @mbggenerated Mon Jun 15 16:31:19 CST 2015
     */
    int updateByExample(@Param("record") RtBfF0103 record, @Param("example") RtBfF0103Example example);
}