package cn.cttic.roadtransapi.orm.roadway.dao;

import cn.cttic.roadtransapi.orm.roadway.domain.RtBfF0101;
import cn.cttic.roadtransapi.orm.roadway.domain.RtBfF0101Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RtBfF0101Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_F0101
     *
     * @mbggenerated Tue Jun 16 16:41:56 CST 2015
     */
    int countByExample(RtBfF0101Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_F0101
     *
     * @mbggenerated Tue Jun 16 16:41:56 CST 2015
     */
    int deleteByExample(RtBfF0101Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_F0101
     *
     * @mbggenerated Tue Jun 16 16:41:56 CST 2015
     */
    int insert(RtBfF0101 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_F0101
     *
     * @mbggenerated Tue Jun 16 16:41:56 CST 2015
     */
    int insertSelective(RtBfF0101 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_F0101
     *
     * @mbggenerated Tue Jun 16 16:41:56 CST 2015
     */
    List<RtBfF0101> selectByExample(RtBfF0101Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_F0101
     *
     * @mbggenerated Tue Jun 16 16:41:56 CST 2015
     */
    int updateByExampleSelective(@Param("record") RtBfF0101 record, @Param("example") RtBfF0101Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_F0101
     *
     * @mbggenerated Tue Jun 16 16:41:56 CST 2015
     */
    int updateByExample(@Param("record") RtBfF0101 record, @Param("example") RtBfF0101Example example);
}