package cn.cttic.roadtransapi.orm.roadway.dao;

import cn.cttic.roadtransapi.orm.roadway.domain.RtBfB0110;
import cn.cttic.roadtransapi.orm.roadway.domain.RtBfB0110Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RtBfB0110Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0110
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    int countByExample(RtBfB0110Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0110
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    int deleteByExample(RtBfB0110Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0110
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    int insert(RtBfB0110 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0110
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    int insertSelective(RtBfB0110 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0110
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    List<RtBfB0110> selectByExample(RtBfB0110Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0110
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    int updateByExampleSelective(@Param("record") RtBfB0110 record, @Param("example") RtBfB0110Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RT_BF_B0110
     *
     * @mbggenerated Tue Sep 08 12:31:54 CST 2015
     */
    int updateByExample(@Param("record") RtBfB0110 record, @Param("example") RtBfB0110Example example);
}