SET DEFINE OFF;
Insert into APPROVAL_DEV.INTER_SWAP_PLATFORM_CONFIG
   (SERVICE_ID, SERVICE_NAME, SYSTEM_ID, SERVICE_IP, SERVICE_PORT, 
    SERVICE_URL, CREATE_DATE, DONE_DATE, ADAPTER_TYPE, EXTENSION, 
    REMARK)
 Values
   ('P0101', '企业基本信息查询', '1001', NULL, NULL, 
    NULL, NULL, NULL, 'DB', NULL, 
    NULL);
Insert into APPROVAL_DEV.INTER_SWAP_PLATFORM_CONFIG
   (SERVICE_ID, SERVICE_NAME, SYSTEM_ID, SERVICE_IP, SERVICE_PORT, 
    SERVICE_URL, CREATE_DATE, DONE_DATE, ADAPTER_TYPE, EXTENSION, 
    REMARK)
 Values
   ('P0102', '船舶基本信息查询接口', '1001', NULL, NULL, 
    NULL, NULL, NULL, 'DB', NULL, 
    NULL);
Insert into APPROVAL_DEV.INTER_SWAP_PLATFORM_CONFIG
   (SERVICE_ID, SERVICE_NAME, SYSTEM_ID, SERVICE_IP, SERVICE_PORT, 
    SERVICE_URL, CREATE_DATE, DONE_DATE, ADAPTER_TYPE, EXTENSION, 
    REMARK)
 Values
   ('W0105', '统计信息查询接口', '3001', NULL, NULL, 
    NULL, NULL, NULL, 'REDIS', NULL, 
    NULL);
Insert into APPROVAL_DEV.INTER_SWAP_PLATFORM_CONFIG
   (SERVICE_ID, SERVICE_NAME, SYSTEM_ID, SERVICE_IP, SERVICE_PORT, 
    SERVICE_URL, CREATE_DATE, DONE_DATE, ADAPTER_TYPE, EXTENSION, 
    REMARK)
 Values
   ('R0101', '同步数据接口', '1001', NULL, NULL, 
    NULL, NULL, NULL, 'DB_MOD', NULL, 
    NULL);
Insert into APPROVAL_DEV.INTER_SWAP_PLATFORM_CONFIG
   (SERVICE_ID, SERVICE_NAME, SYSTEM_ID, SERVICE_IP, SERVICE_PORT, 
    SERVICE_URL, CREATE_DATE, DONE_DATE, ADAPTER_TYPE, EXTENSION, 
    REMARK)
 Values
   ('R0102', '同步数据接口', '1001', NULL, NULL, 
    NULL, NULL, NULL, 'DB_AORM', NULL, 
    NULL);
Insert into APPROVAL_DEV.INTER_SWAP_PLATFORM_CONFIG
   (SERVICE_ID, SERVICE_NAME, SYSTEM_ID, SERVICE_IP, SERVICE_PORT, 
    SERVICE_URL, CREATE_DATE, DONE_DATE, ADAPTER_TYPE, EXTENSION, 
    REMARK)
 Values
   ('W0101', '验证码请求接口', '3001', NULL, NULL, 
    NULL, NULL, NULL, 'USERINFO', NULL, 
    NULL);
Insert into APPROVAL_DEV.INTER_SWAP_PLATFORM_CONFIG
   (SERVICE_ID, SERVICE_NAME, SYSTEM_ID, SERVICE_IP, SERVICE_PORT, 
    SERVICE_URL, CREATE_DATE, DONE_DATE, ADAPTER_TYPE, EXTENSION, 
    REMARK)
 Values
   ('W0102', '单车辆当前信息查询接口', '3001', NULL, NULL, 
    NULL, NULL, NULL, 'REDIS', NULL, 
    NULL);
Insert into APPROVAL_DEV.INTER_SWAP_PLATFORM_CONFIG
   (SERVICE_ID, SERVICE_NAME, SYSTEM_ID, SERVICE_IP, SERVICE_PORT, 
    SERVICE_URL, CREATE_DATE, DONE_DATE, ADAPTER_TYPE, EXTENSION, 
    REMARK)
 Values
   ('W0103', '按高速路线查询车辆当前信息接口', '3001', NULL, NULL, 
    NULL, NULL, NULL, 'REDIS', NULL, 
    NULL);
Insert into APPROVAL_DEV.INTER_SWAP_PLATFORM_CONFIG
   (SERVICE_ID, SERVICE_NAME, SYSTEM_ID, SERVICE_IP, SERVICE_PORT, 
    SERVICE_URL, CREATE_DATE, DONE_DATE, ADAPTER_TYPE, EXTENSION, 
    REMARK)
 Values
   ('R0104', '小三通同步数据接口', '1001', NULL, NULL, 
    NULL, NULL, NULL, 'SMALLTEE', NULL, 
    NULL);
Insert into APPROVAL_DEV.INTER_SWAP_PLATFORM_CONFIG
   (SERVICE_ID, SERVICE_NAME, SYSTEM_ID, SERVICE_IP, SERVICE_PORT, 
    SERVICE_URL, CREATE_DATE, DONE_DATE, ADAPTER_TYPE, EXTENSION, 
    REMARK)
 Values
   ('W0104', '单车辆历史轨迹信息查询接口', '3001', NULL, NULL, 
    NULL, NULL, NULL, 'JSON', NULL, 
    NULL);
Insert into APPROVAL_DEV.INTER_SWAP_PLATFORM_CONFIG
   (SERVICE_ID, SERVICE_NAME, SYSTEM_ID, SERVICE_IP, SERVICE_PORT, 
    SERVICE_URL, CREATE_DATE, DONE_DATE, ADAPTER_TYPE, EXTENSION, 
    REMARK)
 Values
   ('R0103', '小三通证书编号接口', '1001', 'localhost', '7001', 
    'http://localhost:7001/wtms-approval/ws/approvalService?wsdl', NULL, NULL, 'XML', NULL, 
    NULL);
COMMIT;
