package cn.cttic.roadtransapi.domain;

import java.util.Date;

import cn.cttic.roadtransapi.common.SelectValBySequence;

public class InterSpcLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER_SPC_LOG.ID
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
	@SelectValBySequence(SequenceName="SEQUENCE_INTER_LOG_TABLE_ID")
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER_SPC_LOG.REQ_SERIAL
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    private String reqSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER_SPC_LOG.SERVICE_ID
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    private String serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER_SPC_LOG.SERVICE_NAME
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    private String serviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER_SPC_LOG.SRC_SYSTEM_ID
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    private String srcSystemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER_SPC_LOG.DST_SYSTEM_ID
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    private String dstSystemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER_SPC_LOG.PROC_STEP
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    private String procStep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER_SPC_LOG.PROC_START_TIME
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    private Date procStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER_SPC_LOG.PROC_END_TIME
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    private Date procEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER_SPC_LOG.RESP_CODE
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    private String respCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER_SPC_LOG.RESP_MSG
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    private String respMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER_SPC_LOG.CREATE_DATE
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER_SPC_LOG.EXTENSION
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    private String extension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER_SPC_LOG.REMARK
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER_SPC_LOG.ID
     *
     * @return the value of INTER_SPC_LOG.ID
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER_SPC_LOG.ID
     *
     * @param id the value for INTER_SPC_LOG.ID
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER_SPC_LOG.REQ_SERIAL
     *
     * @return the value of INTER_SPC_LOG.REQ_SERIAL
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public String getReqSerial() {
        return reqSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER_SPC_LOG.REQ_SERIAL
     *
     * @param reqSerial the value for INTER_SPC_LOG.REQ_SERIAL
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public void setReqSerial(String reqSerial) {
        this.reqSerial = reqSerial == null ? null : reqSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER_SPC_LOG.SERVICE_ID
     *
     * @return the value of INTER_SPC_LOG.SERVICE_ID
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER_SPC_LOG.SERVICE_ID
     *
     * @param serviceId the value for INTER_SPC_LOG.SERVICE_ID
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId == null ? null : serviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER_SPC_LOG.SERVICE_NAME
     *
     * @return the value of INTER_SPC_LOG.SERVICE_NAME
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER_SPC_LOG.SERVICE_NAME
     *
     * @param serviceName the value for INTER_SPC_LOG.SERVICE_NAME
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName == null ? null : serviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER_SPC_LOG.SRC_SYSTEM_ID
     *
     * @return the value of INTER_SPC_LOG.SRC_SYSTEM_ID
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public String getSrcSystemId() {
        return srcSystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER_SPC_LOG.SRC_SYSTEM_ID
     *
     * @param srcSystemId the value for INTER_SPC_LOG.SRC_SYSTEM_ID
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public void setSrcSystemId(String srcSystemId) {
        this.srcSystemId = srcSystemId == null ? null : srcSystemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER_SPC_LOG.DST_SYSTEM_ID
     *
     * @return the value of INTER_SPC_LOG.DST_SYSTEM_ID
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public String getDstSystemId() {
        return dstSystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER_SPC_LOG.DST_SYSTEM_ID
     *
     * @param dstSystemId the value for INTER_SPC_LOG.DST_SYSTEM_ID
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public void setDstSystemId(String dstSystemId) {
        this.dstSystemId = dstSystemId == null ? null : dstSystemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER_SPC_LOG.PROC_STEP
     *
     * @return the value of INTER_SPC_LOG.PROC_STEP
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public String getProcStep() {
        return procStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER_SPC_LOG.PROC_STEP
     *
     * @param procStep the value for INTER_SPC_LOG.PROC_STEP
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public void setProcStep(String procStep) {
        this.procStep = procStep == null ? null : procStep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER_SPC_LOG.PROC_START_TIME
     *
     * @return the value of INTER_SPC_LOG.PROC_START_TIME
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public Date getProcStartTime() {
        return procStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER_SPC_LOG.PROC_START_TIME
     *
     * @param procStartTime the value for INTER_SPC_LOG.PROC_START_TIME
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public void setProcStartTime(Date procStartTime) {
        this.procStartTime = procStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER_SPC_LOG.PROC_END_TIME
     *
     * @return the value of INTER_SPC_LOG.PROC_END_TIME
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public Date getProcEndTime() {
        return procEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER_SPC_LOG.PROC_END_TIME
     *
     * @param procEndTime the value for INTER_SPC_LOG.PROC_END_TIME
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public void setProcEndTime(Date procEndTime) {
        this.procEndTime = procEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER_SPC_LOG.RESP_CODE
     *
     * @return the value of INTER_SPC_LOG.RESP_CODE
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public String getRespCode() {
        return respCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER_SPC_LOG.RESP_CODE
     *
     * @param respCode the value for INTER_SPC_LOG.RESP_CODE
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public void setRespCode(String respCode) {
        this.respCode = respCode == null ? null : respCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER_SPC_LOG.RESP_MSG
     *
     * @return the value of INTER_SPC_LOG.RESP_MSG
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public String getRespMsg() {
        return respMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER_SPC_LOG.RESP_MSG
     *
     * @param respMsg the value for INTER_SPC_LOG.RESP_MSG
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public void setRespMsg(String respMsg) {
        this.respMsg = respMsg == null ? null : respMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER_SPC_LOG.CREATE_DATE
     *
     * @return the value of INTER_SPC_LOG.CREATE_DATE
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER_SPC_LOG.CREATE_DATE
     *
     * @param createDate the value for INTER_SPC_LOG.CREATE_DATE
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER_SPC_LOG.EXTENSION
     *
     * @return the value of INTER_SPC_LOG.EXTENSION
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER_SPC_LOG.EXTENSION
     *
     * @param extension the value for INTER_SPC_LOG.EXTENSION
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER_SPC_LOG.REMARK
     *
     * @return the value of INTER_SPC_LOG.REMARK
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER_SPC_LOG.REMARK
     *
     * @param remark the value for INTER_SPC_LOG.REMARK
     *
     * @mbggenerated Mon Jul 06 10:25:24 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}